The-OpenROAD-Project/OpenROAD

- src/pdngen/src/PdnGen.tcl
Hello,
I assume that the intended section name in the specification is "blockages" since it's on all of the test cases. I have also changed the default behavior when the section isn't specified to block all layers instead of arbitrarily blocking the first 4 layers, which I find more logical.
I have done these changes on master initially since I was using it, but I thought it would be more useful to issue the PR against this branch; please let me know if I was wrong.
Thanks!
> Blockages section in pdn macro grid specification

- src/tapcell/test/src/check_cells_inserted/run.sh
- src/tapcell/test/src/check_cut_rows/run.sh
- src/tapcell/test/src/check_macros/run.sh
Updates:
- FastRoute reads wires from nets and special nets when computing obstacles
- FastRoute creates global routing grid considering die area
- tapcell unit tests use "-no_init" option when they call openroad
> FastRoute enhancements and tapcell fix

- src/pdngen/src/PdnGen.tcl
- src/pdngen/test/regression_vars.tcl
- src/pdngen/test/soc_bsg_black_parrot_nangate45/PDN.cfg
Fixed issue when trying to connect power pads into the core rings
Ensure that the soc level unit test is always run.
> Fix bug when trying to reference pwr/gnd pads to connect to core rings

- src/TritonCTS/src/tritoncts.tcl
This should remove the occurrences of exit in TCL code for TritonCTS.
> [TritonCTS] Use ord::error instead of exit in TCL

- src/tapcell/src/tapcell.tcl
This pull request fix tapcell placement to guarantee at least two sites between tapcells and endcaps, avoiding errors in filler cells insertion
> [tapcell] Fix minimum distance from cells around macros

- README.md
- src/TritonCTS/CMakeLists.txt
- src/TritonCTS/README.md
- src/TritonCTS/src/CtsOptions.h
- src/TritonCTS/src/DbWrapper.cpp
- src/TritonCTS/src/HTreeBuilder.cpp
- src/TritonCTS/src/TechChar.cpp
- src/TritonCTS/src/TritonCTSKernel.cpp
- src/TritonCTS/src/TritonCTSKernel.h
- src/TritonCTS/src/TritonCTSKernelTcl.cpp
- src/TritonCTS/src/TritonCTSKernelTcl.i
- src/TritonCTS/src/tritoncts.tcl
- src/TritonCTS/test/src/check_lut/run.tcl
- src/TritonCTS/test/src/create_lut/run.tcl
- src/TritonCTS/test/src/find_clock/run.tcl
- src/TritonCTS/test/src/find_clock_pad/run.tcl
- src/TritonCTS/test/src/no_clocks/run.tcl
- src/TritonCTS/test/src/no_sinks/run.tcl
- src/TritonCTS/test/src/simple_test/run.tcl
This PR fixes/updates various things for TritonCTS:
1. Flags are now used on TCL.
2. Errors stop the execution of TritonCTS and return to TCL, not to the terminal/cmd... This fixes issue #299.
3. Added the report_cts command.
4. Errors raised during execution do not std::exit() and instead uses ord::error.
> [TritonCTS] Interface, New command, and Error Handling Update

- CMakeLists.txt
Modify openroad app version number to be .9 since 1.0 will be the phase1b deliverable name.
> Update version number to  .9 to align with v1.0 being the end of phase 1b

- src/antennachecker/src/CMakeLists.txt
This fixes an error with tcl.h that happens in some Linux distributions. 
> OpenROAD/build/src/antennachecker/src/AntennaChecker_wrap.cc:195:10: fatal error: tcl.h: No such file or directory
>  #include <tcl.h>
Some newer versions of TCL have the tcl.h inside another folder, which makes the build fail. Adding the TCL_INCLUDE_PATH to the CMakeLists file of ARC solves this problem.
> [ARC] Fix CMake TCL error

- README.md
The README.md refers to optimimize_mirroring, but the option is
optimize_mirroring.
> Fix optimize_mirroring typo in README.md

- src/OpenDB/src/db/dbIntHashTable.hpp
The LLVM undefined behaviour sanitizer is complaining about hash_int():
../src/OpenDB/src/db/dbIntHashTable.hpp:47:16: runtime error: left shift of 37304127 by 11 places cannot be represented in type 'int'
We can simplify hash_int() and fix this issue by defining key as an
unsigned int.
> Fix undefined behaviour in OpenDB hash_int()

- src/TritonRoute/src/TritonRoute.cpp
fstream opens a file with both read and write permissions since this file is only reading ifstream should be used instead.
> drt: Modifying param file fstream to ifstream

- src/TritonRoute/src/dr/FlexDR.cpp
- src/TritonRoute/src/dr/FlexDR_maze.cpp
by including <sstream> these errors are fixed.
> drt: Fixing clang error when implicitly using stringstream

- src/TritonRoute/src/dr/FlexDR_maze.cpp
- src/TritonRoute/src/dr/FlexGridGraph.cpp
- src/TritonRoute/src/dr/FlexGridGraph.h
This vector is unused in the current tritonroute implementation, but
consists of 7% of the total runtime because it is still sized and
cleared.
> Removes AstarCosts from TritonRoute.

- src/TritonRoute/src/dr/FlexDR.h
- src/TritonRoute/src/dr/FlexDR_maze.cpp
- src/TritonRoute/src/frBaseTypes.h
- src/TritonRoute/src/gc/FlexGC_main.cpp
- src/TritonRoute/src/ta/FlexTA.h
- src/TritonRoute/src/ta/FlexTA_assign.cpp
There are a number of places we compute distance squared, and on
larger designs this can overflow an frCoord which is a signed 32
bit integer.  Create a uint64_t datatype called frSquaredDistance
to store these values without overflow.
Also create pt2ptDistSquare() to square the distance between
two points safely.
> drt: Fix a number of integer overflow issues

- src/TritonRoute/src/ta/FlexTA_assign.cpp
The LLVM undefined behaviour sanitizer highlighted issues in
modMinSpacingCostPlanar(). We are trying to calculate the cost even when
the spacing to the nearest object is greater than our minimum spacing
rules. Just skip over it in this case, simliar to how
modMinSpacingCostVia() handles it.
> drt: Avoid negative sqrt in modMinSpacingCostPlanar()

- src/TritonRoute/src/io/io_parser_helper.cpp
There are a couple of warnings when using the sky130 hd tech:
[WARNING DRT-0160] Warning: met2 does not have viaDef aligned with layer direction, generating new viaDef via2_FR.
[WARNING DRT-0160] Warning: met4 does not have viaDef aligned with layer direction, generating new viaDef via4_FR.
In both cases the layer is square, so the warning is harmless, but we
may as well catch this case and avoid the warning altogether.
> Don't recreate via rule if either layer is square

- src/TritonRoute/src/dr/FlexDR_maze.cpp
Integer overflow in routeNet_postAstarPatchMinAreaVio causes tracks to
be created that are much longer than they should be. I've noticed this
on a few larger sky130hd designs on the metal 5 layer.
> drt: Integer overflow results in tracks outside die area

- src/OpenDB/src/swig/python/dbtypes.i
This commit addresses a regression in the python test suite related to
the python int to uint conversion. In these cases swig needs a
customized type checking routine to check the type of our python ints.
This check was removed in the OpenDB refactor adding it back to fix the
regressions
Closes #618
> Fixes #618 swig type check error.

- .github/workflows/github-actions-cron-sync-fork-from-upstream.yml
This needs https://github.com/The-OpenROAD-Project/actions/pull/3 to be merged first.
Changes;
* Action will run only if a `DEPLOY_KEY` secret is set.
* Use significantly faster push method (takes like 4 seconds) allowing much increased frequency.
* Only use overwrite the master branch if the `UPSTREAM_SYNC` GitHub Action secret is set to **exactly** `always overwrite master branch`. *Otherwise* the workflow can be manually triggered with the force value set to `true`.
Steps for setting up the `DEPLOY_KEY`;
* Generate a new deploy key with `ssh-keygen -t ed25519 -f openroad-push`.
* Add the private key output (in file `openroad-push`) to the [repositories GitHub Actions secrets](../settings/secrets/actions) named `DEPLOY_KEY`.
* Add the public key output (in file `openroad-push.pub`) to …
> Rework the automatically sync branch github action.

- src/PartitionMgr/src/PartitionMgr.cpp
- src/PartitionMgr/src/PartitionMgr.h
- src/PartitionMgr/test/change_eval_method.tcl
1. Removed pre-processing of results while partition manager is running.
2. Fixing evaluate_partitioning to correctly identify best solutions based on the evaluation method.
3. Test case included for when unit testing is available.
Discussion: https://openroad.atlassian.net/browse/OR-996
> par: fix partition solutions from getting pinned to wrong metric

- src/ppl/include/ppl/IOPlacer.h
- src/ppl/src/IOPlacer.cpp
- src/ppl/test/add_constraint8.defok
- src/ppl/test/add_constraint8.ok
- src/ppl/test/add_constraint8.tcl
- src/ppl/test/regression_tests.tcl
This PR updates ioPlacer constraints to handle overlapping constraints.
If two different constraints have overlapping intervals, the constraint with the lower pins per available slots ratio is processed first.
> ppl: sort overlapping constraints

- docker/Dockerfile.runtime
- etc/DockerHelper.sh
This makes `Dockerfile.runtime` work.
Additionally, the Docker helper script has been updated so environment variables can override the image names (useful if you're building the images as part of a more controlled flow.) This is a strictly additive change that will not interrupt any existing flows.
> Fix for `Dockerfile.runtime`, Docker helper script

- README.md
- src/ppl/src/IOPlacer.cpp
- src/ppl/src/IOPlacer.i
- src/ppl/src/IOPlacer.tcl
- src/ppl/src/Parameters.h
- src/ppl/test/min_dist_in_tracks1.defok
- src/ppl/test/min_dist_in_tracks1.ok
- src/ppl/test/min_dist_in_tracks1.tcl
- src/ppl/test/min_dist_in_tracks2.defok
- src/ppl/test/min_dist_in_tracks2.ok
- src/ppl/test/min_dist_in_tracks2.tcl
- src/ppl/test/regression_tests.tcl
This PR covers a request from Ravi. It adds an option to allow the min distance units to be in number of tracks. By default, the min distance is in microns, but with the `-min_distance_in_tracks` flag, it changes to number of tracks.
> ppl: add option to allow min dist in tracks

- src/rcx/src/netRC.cpp
for platform differences. Seen 0 (versus 0.0) appear which can cause regression to fail
Fix for issue #911
> Format the max_merge_res value for RCX message 436 to account

- src/rcx/src/extRCmodel.cpp
This bug cropped up in the rcx regression tests when running as an unprivileged user. In `openFile()` in `src/rcx/src/extRCmodel.cpp`, a call to `sprintf()` uses one of its sources as a destination buffer which is [a known source of undefined behavior](https://gms.tf/on-sprintf-fails.html). The result was that `openroad` kept trying to write a log file to the root directory of my file system in regression tests since the log path was malformed. I believe this should fix it.
> Fix undefined behavior with sprintf.

- src/rmp/src/Restructure.cpp
- src/rmp/test/const_cell_removal.ok
- src/rmp/test/gcd_restructure.ok
Fix typo to use timing instead of delay in option "target"
Signed-off-by: Sanjiv Mathur <mathur.sanjiv@gmail.com>
> Fix typos for ABC command names

- docker/Dockerfile.binary
- docker/Dockerfile.builder
- docker/Dockerfile.dev
- docker/Dockerfile.runtime
- etc/DockerHelper.sh
With the separation between runtime and binary we can deploy the runtime image to hub.docker.com without a binary.
> Docker: separate runtime into two.

- src/dbSta/include/db_sta/dbNetwork.hh
- src/dbSta/src/dbNetwork.cc
- src/dbSta/src/dbReadVerilog.cc
- src/dbSta/test/read_verilog1.tcl
- src/dbSta/test/read_verilog4.ok
- src/dbSta/test/read_verilog6.ok
- src/dbSta/test/read_verilog8.tcl
- src/dbSta/test/read_verilog8.v
- src/dbSta/test/regression_tests.tcl
- src/dbSta/test/write_verilog8.ok
- src/ifp/test/auto_place_pins1.ok
- src/par/src/PartitionNetwork.cpp
write_verilog flips the indices of lsb first bus ports #578 
> write_verilog flips the indices of lsb first bus ports

- src/odb/src/defin/definReader.cpp
I want to be able to initialize a floorplan based on a provided DEF that includes special net paths and via declarations, but I noticed that when `read_def` has the `-floorplan_initialize` flag passed in, it strips these away. If there's no particular reason for this, I think it would be helpful for this information to be processed and included even on floorplan initialization reads. 
This PR accomplishes this by adjusting the definReader configuration to process this information for both the default and floorplan reader modes.
> Process vias and snet paths on init floorplan

- src/grt/src/fastroute/src/maze.cpp
> grt: call fluteNormal before fluteCongest in reInitTree

- src/odb/src/defin/definReader.cpp
Similarly to PR #987, I'd like to be able to initialize a floorplan based on a provided DEF file that includes placement or routing blockages and not have them e stripped away. This PR adjusts the definReader configuration to enable this.
Thanks!
> Process blockages on -initialize_floorplan

- src/gpl/src/replace.tcl
When using the routability_max_density option, openroad died with:
invalid command name "set_routability_max_density_cmd"
> gpl: Fix routability_max_density option

- src/gpl/README.md
- Move all options under the Tuning Parameters heading
- Remove -grid_count, the option is -bin_grid_count and it is documented
further down
- -init_wire_length_coef should be -init_wirelength_coef
> gpl: Fix a few documentation issues

- src/gpl/src/replace.cpp
In commit b85d12c5006e ("allow 25% overflow"), the initial and reset
values of routabilityTargetRcMetric_ got out of sync. Assuming that
was a mistake, this fixes it. Also rearrange the values so they line up.
> gpl: Fix reset of routabilityTargetRcMetric_

- CMakeLists.txt
- README.md
Link Time Optimization allows the compiler to make optimizations across link boundaries. 
https://en.wikipedia.org/wiki/Interprocedural_optimization
Current CI runtime is measured at about 23-37 minutes. We should see if this reduces that time.
> Enabling Link Time Optimization (LTO) for OpenROAD

- README.md
The CMAKE variable is `TCL_LIBRARY`. `TCL_LIB` doesn't appear to do anything.
> Correct TCL_LIBRARY var in README

- src/drt/CMakeLists.txt
- src/dst/CMakeLists.txt
- src/dst/include/dst/Distributed.h
This PR allows to build using any boost version.
* Distro's **cannot guarantee** a specific **pinned version**.
* As example on RHEL-8/CentOS-8 **cannot be compiled**.
For the involved `basic_stream_socket` see the major changes [1.69.0](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/basic_stream_socket.html) vs [1.70.0](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_stream_socket.html)
```
- template< typename Protocol >
+ template< typename Protocol, typename Executor >
class basic_stream_socket :
-  public basic_socket< Protocol >
+  public basic_socket< Protocol, Executor >
```
---
This now pass compilation on following [latest builds](https://copr.fedorainfracloud.org/coprs/rezso/VLSI/build/3077214)
For your interest there are …
> Don't restrict boost version.

- src/grt/README.md
This PR updates the `-verbose` flag documentation, Resolves https://github.com/The-OpenROAD-Project/OpenROAD/issues/1480
> grt: update readme

- src/ppl/src/IOPlacer.cpp
- src/ppl/test/place_pin_error3.ok
- src/ppl/test/place_pin_error3.tcl
- src/ppl/test/regression_tests.tcl
This PR adds a check for the `place_pin` command for the min width of the layer. When a pin is placed violating the min width, drt can fail when computing the APs.
Issue detected from a user testcase.
> ppl: check min width during place_pin command

- src/grt/README.md
Commit dd6b529f0d6a ("Review") dropped the documentation for
draw_route_guides. Restore it.
> grt: Restore draw_route_guides documentation

- CMakeLists.txt
- src/CMakeLists.txt
- src/dst/CMakeLists.txt
- src/rmp/src/CMakeLists.txt
- third-party/CMakeLists.txt
This PR enables **optional** possibilities to pick **external system libraries** during build time.
* This pass latest weekly [copr instance](https://copr.fedorainfracloud.org/coprs/rezso/VLSI/build/3209030/) on a range of builds.
* For full completion a small batch of code related fixes will be sent after this PR.
The goal is to enable more portability that can be further polished.
Thank You !
~cristian.
----
(1) Introduced **optional** cmake knobs:
- ```USE_SYSTEM_BOOST```  picks **shared** system wide **boost** related libraries.
- ```USE_SYSTEM_ABC``` picks **shared**/**static** system wide **abc** related libraries.
- ```USE_SYSTEM_OPENSTA```  picks **shared**/**static** pre-builds and **require** to set ```OPENSTA_HOME``` path.
(2) Variable additions to the knobs:
- …
> Add external system libraries options.

- src/grt/src/GlobalRouter.cpp
Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/1360
It seems that `pin.getITerm()->getPrefAccessPoints()` doesn't work for pins connected to macros or pads. This PR updates grt code to get the APs for these pins with `pin.getITerm()->getAccessPoints()`;
> grt: fix APs for pins connected to macros or pads

- src/gui/include/gui/heatMap.h
- src/mpl/src/ParquetFP/src/SolveMulti.cxx
- src/rmp/include/rmp/Restructure.h
- src/rmp/src/Restructure.cpp
Fix a ```boost``` header inclusion and allow pick ```abc``` (external) having no namespace.
----
* One ```boost``` header must be included for >= .fc36
* External```abc``` picked from distros have no namespace
----
The PR pass vanilla OpenROAD for [range of builds](https://copr.fedorainfracloud.org/coprs/rezso/VLSI/build/3260074) on fedora copr public build system.
Thank You !
> Boost header fix and external abc having no namespace.

- src/pdn/src/via.h
A small fix for failing centos8 build.
* The mentioned header is [required](https://www.boost.org/doc/libs/1_66_0/libs/geometry/doc/html/geometry/reference/models/model_d2_point_xy.html) for boost's 2d point cartesians (centos8 have boost 1.66).
* The new PDN was introduced a week ago [#1749] done by @arlpetergadfort .
The patch pass [all builds](https://copr.fedorainfracloud.org/coprs/rezso/VLSI/build/4114356/) including centos8.
Cc: @maliberty 
Thank you,
~Cristian.
> Add missing boost header from new PDN module.

- src/cts/src/CMakeLists.txt
- src/dpo/CMakeLists.txt
Debian/Ubuntu installs LEMONConfig.cmake as lemonConfig.cmake, which breaks detection of the system library.
Use the NAME syntax to list both.
Fixes: https://github.com/The-OpenROAD-Project/OpenROAD/issues/1186
Signed-off-by: Joel Stanley <joel@jms.id.au>
> Fix LEMON library detection

- src/gui/src/browserWidget.cpp
- src/gui/src/inspector.cpp
- src/gui/src/selectHighlightWindow.cpp
In Google's QT installation the following lines create ambiguity with
the QTStringStringBuilder. These changes allow the compiler to correctly
figure out what method to call.
> Fixes QT 5.12.9 compile issues

- src/cts/src/TechChar.cpp
My PDK lists clock buffer cell inputs as signal type clock rather than generic signal. What ends up happening is this code fails to set charBufIn leading to a null returned BTerm down the line and segfault.
This triggers an error if they are not found, and makes sure to include the clock type as a valid input port.
> Fix SegFault in CTS

- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_init.cpp
> drt: fix off-grid violations on first iterations

- third-party/CMakeLists.txt
ABC_USE_NO_READLINE is not read in abc's CMakeLists.txt but instead generated depending on READLINE_FOUND.
It's not clear who's supposed to set this variable but it tells if the readline header is present or not. So just pretend the header is not present as we don't need it.
> Fix disabling readline use in abc.

- src/rsz/src/RepairDesign.cc
I should note that gui::Gui::get() would be safer if it was
wrapped in std::optional<>...
> Fixes nullptr segfault when building without GUI support.

- src/CMakeLists.txt
Small PR to ~~fix~~ avoid ```fmt``` errors like below.
```
/usr/include/fmt/core.h:1733:7: error: static assertion failed: Cannot format an argument. 
To make type T formattable provide a formatter<T> specialization: 
https://fmt.dev/latest/api.html#udt
```
Output now signals SPDLOG mode:
```
{...}
-- OpenROAD version: 2.0-20220728.gitbd841a8c.fc37
-- System name: Linux
-- Compiler: GNU 12.1.1
{...}
-- spdlog: 1.10.0
-- spdlog: SPDLOG_FMT_EXTERNAL=OFF
{...}
```
----
More system details:
```
$ rpm -q fmt-devel
fmt-devel-9.0.0-2.fc37.x86_64
$ rpm -q spdlog-devel
spdlog-devel-1.10.0-3.fc37.x86_64
```
> Verbose SPDLOG_FMT_EXTERNAL during cmake detection.

- src/ant/src/AntennaChecker.cc
This PR addresses Issue #2187.
Originally, when thickness ismissing from any routing layer, a value of 0 was used. In this PR, I changed this so that an error is reported if the thickness is missing.
Signed-off-by: Ramez Moussa <ramez.moussa@aucegypt.edu>
> ant: error when thickness is missing

- src/odb/include/odb/dbTypes.h
- src/odb/src/db/dbTypes.cpp
getIdx() continually calls into odb code to determine the layer direction.
Create a helper isZDirHorizontal() which caches this.
Detailed routing of the Microwatt register file is 8.5% faster with this
applied.
> Improve drt performance by inlining dbTechLayerDir constructors

- src/grt/src/GlobalRouter.cpp
We are looking for the diode ANTENNADIFFAREA property but the error
mentions the layer ANTENNADIFFSIDEAREARATIO property.
> grt: Error mentions wrong LEF property

- cmake/FindTCL.cmake
- etc/DependencyInstaller.sh
Draft PR to support MacOS. Closes #2173.
This isn't a perfect solution to the problem, but I think it's a good start. There are several issues I worked around while making this.
* Problem: Homebrew's `spdlog` does not work out of the box as of right now.
* Cause: This has been mentioned a few times in issues such as #2173, #2220, and #2097, but the main issue seems to be that `spdlog` is dependent on `fmt`. While `fmt 8` works with OpenROAD's code, `fmt 9` has more strict standards for conversions of objects into strings for logging, thus resulting in several compiler errors.
* Solution: I think that longer term, we simply have to fix all the object to string conversions so that we can upgrade to `spdlog 1.10` which depends on `fmt 9`. This is what Homebrew wants to do, and it makes …
> Update DependencyInstaller.sh to support MacOS

- src/dpl/src/Opendp.tcl
> dpl: detailed_placement_debug uses wrong command name

- src/Main.cc
This copy all the arguments, instead of just forwarding `argv[0]`, reusing the same code that was previously in https://github.com/The-OpenROAD-Project/OpenROAD/commit/47e8b5f57e2f680172f99c0433c01ed91fcf7fe7#diff-7c2e2869b9670e340a14a2b2ed1cc45a9f85fb8b219a4c1f06fdd467f49375c1L216-L222
Fixes: #2287
> src: fix PyMain arguments forwarding

- README.md
- etc/DependencyInstaller.sh
The script should be run with sudo or with root permissions, using sudo inside it is redundant and might break on systems that do not have sudo installed.
> etc: DependencyInstaller no need to use sudo

- src/grt/src/fastroute/src/FastRoute.cpp
- src/grt/src/fastroute/src/utility.cpp
Fixing wrong values in 2D usage and bug in `FastRouterCore::StNetOrder` function.
Modifying debug mode to only show net when its routing is changed.
Signed-off-by: luis201420 <tauro_luisito_20@hotmail.com>
> grt: fixing incremental grt bugs

- src/Main.cc
Related: #2375
As commented in https://github.com/The-OpenROAD-Project/OpenROAD/pull/2375#issuecomment-1284438149, `openroad -python` now prints a warning when called without argument.
This PR makes sure that we don't attempt to open a file if no arguments is provided after `-python`.
Note: I also noticed that the `findCmd*` helpers in `sta` don't seems to discard singular argument (i.e: don't replace `-python` with `\0` if it's the last argument), see https://github.com/The-OpenROAD-Project/OpenSTA/pull/126.
> src: handle -python with no args

- src/ant/src/AntennaChecker-py.i
This is a small fix for failing ```rhel8``` build.
Failures are on ```rhel8``` only, ```rhel9``` & ```fedora>34``` are fine.
---
The encountered error:
```
src/CMakeFiles/ant_py.dir/AntennaChecker-pyPYTHON_wrap.cxx:8029:3: 
error: ‘vector’ was not declared in this scope
```
> Add missing std namespace & fix build on rhel8.

- src/gpl/README.md
- src/gpl/src/replace.tcl
- src/gpl/src/timingBase.cpp
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
This allows us to tune the percentage of nets that are reweighted
in timing driven placement.
> gpl: Add -timing_driven_nets_percentage

- src/ppl/src/IOPlacer.cpp
Pins on vertical layers are placed partially outside the die area.
> ppl: -force_to_die_boundary fails on vertical layers

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/MakeWireParasitics.cpp
This is a first attempt at fixing https://github.com/The-OpenROAD-Project/OpenROAD/issues/2377
`pinAccessPointPositions()` creates pairs of `{ap_position, ap_position_on_grid}`, does that look reasonable?
> grt: Use pin access in parasitic estimates

- src/grt/src/GlobalRouter.cpp
> grt: Fix crash when calling read_guides before loading design

- src/Main.cc
I hit a SEGV:
Stack trace:
0# sta::ClkInfo::refsFilter(sta::StaState const*) const in openroad
1# sta::TagGroupBldr::setMatchArrival(sta::Tag*, sta::Tag*, float const&, int, sta::PathVertexRep*) in openroad
Which then proceeded to abort and dump the stack a second time:
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
Stack trace:
0# raise in /lib64/libc.so.6
1# abort in /lib64/libc.so.6
...
16# sta::Sta::~Sta() in openroad
17# ord::deleteDbSta(sta::dbSta*) in openroad
18# ord::OpenRoad::~OpenRoad() in openroad
20# on_exit in /lib64/libc.so.6
The issue is we are calling exit() which is not async safe and so cannot be used in a signal handler. Considering the application is in a bad state, it also doesn't make sense to try and gracefully …
> Don't call atexit() functions from signal handler

- src/dpl/src/Opendp.cpp
(https://clang.llvm.org/extra/clang-tidy/checks/misc/unused-using-decls.html)
Signed-off-by: Henner Zeller <hzeller@google.com>
> Tiny cleanup: Remove unused using odb::dbSigType declaration

- src/CMakeLists.txt
- src/cmake/swig_lib.cmake
This PR fix support for future ```swig >= 4.10```, requiring a compatible ```-flatstaticmethod``` for python exports.
* Upstream explanations: https://github.com/swig/swig/pull/2137
* Exposed ```openlane``` behaviour in such case: https://github.com/The-OpenROAD-Project/OpenLane/pull/1471
---
For swig >= 4.1.0 there will be a WARNING during initial detection phase. 
In some future, there might be a desire to switch to swig 4.1.0 ```nonflatstatic``` new behaviour.
Thanks,
~Cristian.
> Support future swig >= 4.1.0 changes.

- include/ord/OpenRoad.hh
- src/Main.cc
- src/OpenRoad.cc
- src/OpenRoad.i
- src/OpenRoad.tcl
redo of #2438
- set interpreter config according to command line flags
- forward arguments to python interpreter
- only init python when flag is passed (remove signal save/restore)
Fixes #2419
I'd love to add something to the test suite, but https://wiki.tcl-lang.org/page/Expect doesn't seems to be supported by the `test/regression` (and would be needed in order to test proper interaction with the REPL).
```
OpenROAD 🍡 cat foo.py 
import odb
print(odb)
import sys
a = sys.argv
print(a)
```
```
OpenROAD 🍧 build/src/openroad -python foo.py 
OpenROAD v2.0-5434-gb348ed433 
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING ORD-0039] .openroad ignored with …
```
> src/Main: simplify python flag handling

- src/ant/src/AntennaChecker.cc
- src/grt/test/repair_antennas4.ok
The issue looks to be down to GF180MCU being simpler than we expect.
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2516
In SKY130 we have antenna rules that look like this.
```
ANTENNAMODEL OXIDE1 ;
ANTENNADIFFSIDEAREARATIO PWL ( ( 0 400 ) ( 0.0125 400 ) ( 0.0225 2609 ) ( 22.5 11600 ) ) ;
```
However, in GF180MCU we have rules that look like.
```
ANTENNAMODEL OXIDE1 ;
ANTENNADIFFSIDEAREARATIO 400 ;
ANTENNAGATEPLUSDIFF 2 ;
```
There is only a single value instead of a linearly interpolated list of values.
```c++
bool AntennaChecker::antennaRatioDiffDependent(dbTechLayer* layer)
{
if (layer->hasDefaultAntennaRule()) {
const dbTechLayerAntennaRule* antenna_rule = layer->getDefaultAntennaRule();
dbTechLayerAntennaRule::pwl_pair diffPAR = antenna_rule->getDiffPAR(); …
```
> Fixes GF180MCU antenna violations

- src/rcx/src/extSpef.cpp
Instead of hard coding 5, 10 or 16, use the ADS_MAX_CORNER define which is used elsewhere in the rcx source.
> rcx: Use ADS_MAX_CORNER

- src/grt/src/GlobalRouter.cpp
> grt: check if route vector is empty

- src/CMakeLists.txt
- src/OpenRoad.cc
- third-party/CMakeLists.txt
remove mpl2 on macos until it does not cause a link related startup error
disable optimization for abc until apple clang does not seg fault compiling it
Signed-off-by: James Cherry <cherry@parallaxsw.com>r
> rm mpl2 until it works on macos

- include/ord/Design.h
- src/CMakeLists.txt
- src/Design.cc
- src/Main.cc
- src/rcx/src/CMakeLists.txt
- src/rcx/src/ext-py.i
- src/rcx/test/45_gcd.py
- src/rcx/test/ext_pattern.py
- src/rcx/test/gcd.py
- src/rcx/test/generate_pattern.py
- src/rcx/test/helpers.py
- src/rcx/test/rcx_aux.py
- src/rcx/test/via_45_resistance.py
Python wrapper for rcx. A slightly different approach was used here. The ext.h header file makes heavy use of various Options structures. But these are defined inside of the Ext class and SWIG will not wrap them there. We can try to think about duplicating them in global scope by .i file hacking, but then we run afoul of "const char *" declarations.  So the easier path is to just use the api that is defined in ext.i
> Rcx python

- include/ord/Design.h
- include/ord/Tech.h
- src/CMakeLists.txt
- src/Design.cc
- src/Main.cc
- src/rmp/src/CMakeLists.txt
- src/rmp/src/blif.cpp
- src/rmp/src/rmp-py.i
- src/rmp/src/rmp.i
- src/rmp/test/blif_reader.py
- src/rmp/test/blif_writer.py
- src/rmp/test/const_cell_removal.py
- src/rmp/test/gcd_restructure.py
- src/rmp/test/helpers.py
- src/rmp/test/rmp_aux.py
Signed-off-by: Don MacMillen <don@macmillen.net>
rmp makes significant use of sta, so there was some things to address that. The constructor for Blif needs the pointer to a sta object, so getSta() was added to the Tech object (seemed better here than on the Design Object).  For the time being, this is an opaque pointer that is only passed to the Blif constructor. Also, there were some graph consistency checking / repair that needs to happen before writeBlif. Moved them from C++ code in an interface file into the body of the C++ method writeBlif (where they belong). Finally, since we needed sta::get_lib_pins (which gets pins from a Liberty library) and there was no obvious way to use odb for that, had to do some moderately ugly Python string Template hacking in order to use evalTclString
> Python wrapper and regression tests for rmp

- src/gui/CMakeLists.txt
- src/gui/src/cmdInputWidget.cpp
- src/gui/src/cmdInputWidget.h
- src/gui/src/layoutViewer.cpp
- src/gui/src/mainWindow.cpp
- src/gui/src/scriptWidget.cpp
- src/gui/src/scriptWidget.h
- src/gui/src/tclCmdInputWidget.cpp
- src/gui/src/tclCmdInputWidget.h
Changes:
- Removes all command execution from script widget and moves them to tcl command widget
Adds:
- Adds base class to help with eventual python input
> gui: decouple script widget and tcl input widget

- src/utl/include/utl/Logger.h
Changes:
- Current metrics get truncated by the `std::fixed` which leads to loss of information. This changes the behavior to use `std::defaultfloat` with slightly higher precision.
Current:
```
"power__internal__total": 0.0016,
"power__switching__total": 0.0005,
"power__leakage__total": 0.0000,
```
Changed to:
```
"power__internal__total": 0.00159408,
"power__switching__total": 0.00054661,
"power__leakage__total": 9.91616e-06,
```
> metrics: use defaultfloat and 6 point precision to avoid truncating small numbers, such as leakage power

- src/dbSta/src/dbSta.cc
Fixes:
- `with_output_to_variable` does not work in OpenROAD like it does in OpenSTA because the functions that enable this behavior is overridden for the logger. This enables this redirection to have the same behavior as OpenSTA.
> dbSta: enable string redirection in openroad to function with with_output_to_variable

- etc/DependencyInstaller.sh
this error message is out of date, more systems are supported, easiest is to remove it
> dependencyinstaller: fix error message

- src/Metrics.tcl
I noticed that the metrics for hold and setup violation count is basically binary since `find_timing_paths` returns just one by default. By adding `group_count` the result will include more than 1 and will default to `sta::endpoint_count`.
> metrics: add group_count to setup/hold violation metrics to return more than 1 or 0 for a more accurate result

- src/grt/src/fastroute/src/maze3D.cpp
Signed-off-by: Arthur <arthurjolo@gmail.com>
In the previous code, if the src_heap_3D becomes empty after "removeMin3D(src_heap_3D);" and nothing was added to the heap at the end of the while the code crashed when trying to access "src_heap_3D[0]".
With this changes, the test for an empty heap is made before this access to prevent the code from crashing
> grt:change testing moment for error GRT183 heap underflow to prevent crashing

- src/cts/src/Clock.cpp
we're iterating over floats, but comparing doubles, so we do want to copy the std::pair<float,float> into std::pair<double,double>
> cts: fix a warning

- src/Metrics.tcl
Fixes:
- by calling `format_time` and recording floats, the value "inf" appears in the json format, which is not supported.
```
"sc__metric__timing__setup__ws": inf,
```
- This fixes this to record the value and letting the metrics logger format the information.
Adds:
- Core and die area metrics
> metrics: avoid double formatting metrics and adding core_area and die_area metrics

- src/drt/include/triton_route/TritonRoute.h
- src/drt/src/TritonRoute.cpp
- src/drt/src/TritonRoute.i
- src/drt/src/TritonRoute.tcl
- src/drt/src/dr/FlexDR.cpp
- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_init.cpp
- src/drt/src/dr/FlexDR_maze.cpp
- src/drt/src/dr/FlexGridGraph.h
- src/drt/src/dr/FlexGridGraph_maze.cpp
- src/drt/src/frBaseTypes.h
- src/drt/src/global.cpp
- src/drt/src/global.h
- src/drt/src/serialization.h
- src/drt/test/drt_aux.py
- src/drt/test/single_step.py
- src/drt/test/single_step.tcl
FIXEDSHAPECOST and MARKERDECAY change based on the iteration, so move
them into SearchRepairArgs where all other per iteration variables are
set.
> drt: Move FIXEDSHAPECOST and MARKERDECAY into SearchRepairArgs 

- src/odb/src/swig/python/dbtypes.i
- src/pdn/src/PdnGen-py.i
Signed-off-by: Don MacMillen <don@macmillen.net>
So this got through the regression tests because I completely forgot that the odb Python regressions do not run with the standard OR regression system. We have to fix that.
> Undo change to dbtypes.i and add %clear directive to PdnGen-py.i

- .gitignore
- src/rcx/include/rcx/ext.h
- src/rcx/include/rcx/extRCap.h
- src/rcx/src/ext.cpp
- src/rcx/src/extBenchDB.cpp
- src/rcx/src/extSpef.cpp
- src/rcx/src/extmain.cpp
- src/rcx/src/extprocess.cpp
- src/rcx/src/netRC.cpp
- Use unique_ptr in two spots where unique lifetime ownership was immediately clear.
- Delete some unreachable code flagged by static analysis tooling.
- Add Vim swp files to the ignored file extension list in .gitignore (similar to the existing ignorance of vscode files).
Signed-off-by: Christopher D. Leary <cdleary@gmail.com>
> A few code cleanups in RCX as a first OpenROAD PR.

- src/drt/test/gc_test.tcl
- src/odb/include/odb/util.h
- src/rcx/include/rcx/ext2dBox.h
- src/rcx/include/rcx/extRCap.h
- src/rcx/src/CMakeLists.txt
- src/rcx/src/ext2dBox.cpp
- src/rcx/src/extBench.cpp
- src/rcx/src/extmeasure.cpp
- src/rcx/test/ext2dBoxTest.cpp
- src/rcx/test/rcx_unit_test.tcl
- src/rcx/test/regression_tests.tcl
- test/helpers.tcl
- Put a note on `AthPool` that the type parameter has to be default-constructible.
- Break `ext2dBox` into its own translation unit, remove friend access to members in favor of it being immutable-after-construction. We use placement-`new` since it needs to be default constructible to use `AthPool`.
- Use `std::array`s to indicate safe bounds instead of raw pointers / C arrays that degenerate to raw pointers.
- Make `dir` a boolean since it was always boolean-valued.
- Make a unit test (boost based).
- Factor out unit test running harness TCL code and put into common `helpers.tcl`
Signed-off-by: Christopher D. Leary <cdleary@gmail.com>
> [rcx] ext2dBox translation unit: encapsulate/test

- src/cts/src/Clock.cpp
- src/mpl2/src/hier_rtlmp.cpp
Just two small changes to prevent copy of std::pair in for loops
> Prevent warnings about unneeded copy in for loops

- src/gui/src/scriptWidget.cpp
- src/gui/src/tclCmdInputWidget.cpp
- src/gui/src/tclCmdInputWidget.h
Fixes:
- result handling was mistakenly turned off, this should re-enable it in the GUI
> gui: fix handling of TCL commands and results in GUI

- src/odb/src/lef/lef/lef.y
Fixes:
- Compiles for LEF parser only on windows.
> lef: check if windows compile in lef.y and avoid referencing the lef_parser.hpp as it fails to compile

- src/grt/src/GlobalRouter.cpp
too useful to omit when verbose is disabled?
> global router: this warning seems almost like an error

- src/grt/CMakeLists.txt
- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/MakeGlobalRouter.cpp
- src/grt/src/MakeWireParasitics.cpp
- src/grt/src/MakeWireParasitics.h
- src/grt/test/est_rc4.ok
- src/grt/test/est_rc4.tcl
- src/grt/test/regression_tests.tcl
- src/rsz/test/repair_hold10.ok
I noticed that the post routing parasitics didn't generate anything across for corners and didn't honor the rsz values when set for corners.
Changes:
- Generate parasitics across corners like resizer does (if only one corner is defined there shouldn't be any changes)
- Use the resizer parasitics values for corners, overwise default back to LEF
Notes:
If rsz values are not set and only one corner is defined, there should be no functional changes
> grt: estimate parasitics over corners based on rsz corner values if available

- src/grt/src/GlobalRouter.cpp
append has to be explicitly specified
> grt: std::ofstream constructor truncates file by default

- src/ant/src/AntennaChecker.cc
> ant: ofstream constructor truncates by default

- src/odb/src/swig/tcl/dbtypes.i
Fixes issue #2777 -- see that issue for more details.
Before snippet from generated file `build/src/dbSta/src/CMakeFiles/dbSta.dir/dbStaTCL_wrap.cxx`
```c++
SWIGINTERN int
_wrap_find_all_clk_nets(ClientData clientData SWIGUNUSED, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
SwigValueWrapper< std::vector< odb::dbNet * > > result;
if (SWIG_GetArgs(interp, objc, objv,":sta::find_all_clk_nets ") == TCL_ERROR) SWIG_fail;
{
try {
result = find_all_clk_nets();
}
catch (std::bad_alloc &) {
fprintf(stderr, "Error: out of memory.");
exit(0);
}
// This catches std::runtime_error (utl::error) and sta::Exception.
catch (std::exception &excp) {
Tcl_ResetResult(interp);
Tcl_AppendResult(interp, excp.what(), nullptr);
return TCL_ERROR;
}
}
{
for (unsigned int i = 0; i < (&result)->size(); i++) …
```
> Fix "out" typemaps to work with SWIG 4.1.0+ (given use of >=C++11 in OpenROAD)

- src/pdn/src/PdnGen.cc
- src/pdn/src/grid.cpp
- src/pdn/src/grid.h
- src/pdn/src/shape.cpp
- src/pdn/src/shape.h
Fixes:
- Filtering method to use boost filtering instead and leaving the obs rtree alone. This will likely be possible in several other places to help speed things up.
Replaces: #2795
> pdn: fix repeated creation of rtrees in Shape::cut

- .github/workflows/github-actions-c++.yml
- CMakeLists.txt
- docs/contrib/Logger.md
- etc/Build.sh
- etc/DependencyInstaller.sh
- src/Main.cc
- src/gui/src/displayControls.cpp
- src/par/src/MLPart/mlpart/ABKCommon/abkrand.h
- src/utl/include/utl/Logger.h
- third-party/lemon/patches/allocator-patch.patch
Couple of notes on C++20
* LEMON 1.3.1 has an issue that needs to be resolved related to allocators. (Included a patch from https://lemon.cs.elte.hu/trac/lemon/ticket/631#no1)
* fmt in versions greater than 8 added the ability to constexpr compile format lines. The downside is runtime strings need to be wrapped in fmt::runtime. Added FMT_RUNTIME macro to support both versions. The current version of spd_log is on version 7 of FMT
* template ids on constructors and destructors have been removed. Removed usage in abk libs.
Introduced a github action to build openroad on c++20. Should prevent any usage of non-supported c++20 features, but this does not mean the project is moving to c++20 yet.
**OpenROAD will stay on C++17**
> Add support for C++20 Compilation

- src/odb/src/lefin/lefin.cpp
Signed-off-by: Matt Liberty <mliberty@eng.ucsd.edu>
> odb: add missing call to setViaParams in lefin::via

- src/drt/src/dr/FlexGridGraph_maze.cpp
- src/drt/src/dr/FlexWavefront.h
Based on a patch from Austin Rovinski
> drt: Remove layerPathArea from FlexWavefront

- src/ifp/src/InitFloorplan.tcl
I could be wrong, but it looks like the `utl::logger` calls in `InitFloorplan.tcl` cause syntax errors if they are ever reached. Were these lines supposed to be `utl::error`?
Signed-off-by: WRansohoff <5217539+WRansohoff@users.noreply.github.com>
> Fix apparent typos in `InitFloorplan.tcl`

- src/rcx/include/rcx/ext.h
- src/rcx/src/CMakeLists.txt
- src/rcx/src/MakeOpenRCX.cpp
- src/rcx/src/ext.cpp
The new library ordering of modules decouples the TCL/Wrapper code from the underlying module code. This allows us to create unit tests for each module without having to link the entire application and swig layers.
It should lead to a more ~~compostable~~ composable environment.
And now a poem, because I like being extra.
```
The path is dark and cold,
The trees are gnarled and old,
The sun is hidden from my sight,
And I am lost in endless night.
I stumble on, I know not where,
My only guide is my despair.
The path is hard and the journey long,
And I am weak, I cannot go on.
But then I see a light,
A glimmer of hope in the night.
I run towards it, I must find it,
It is my only chance to be free.
I stumble out into the light,
And I see that I have died.
I am in a new world,
A world of …
```
> Builds new library structure for OpenROAD modules

- src/drt/src/TritonRoute.cpp
It's useful to see preferred access points when using detailed routing debug.
> drt: write preferred aps back to database in debug mode

- src/drt/src/db/tech/frLayer.h
- src/drt/src/io/io.cpp
On multiple patterned layers we force tracks to be both unidirectional and on grid. Add a comment (and update the other).
> drt: Add comment explaining multi patterning limitation

- src/pad/src/ICeWall.cpp
- src/pad/src/Utilities.cpp
- src/pad/test/assign_bumps.defok
- src/pad/test/place_bondpad_stagger.defok
- src/pad/test/skywater130_caravel.defok
- src/pad/test/skywater130_coyote_tc.defok
- src/pad/test/skywater130_overlapping_filler.defok
Fixes:
- missing special net marking and ensuring nets match their iterms if the iterms are supply
> pad: fix special net handling

- src/ppl/src/IOPlacer.cpp
- src/ppl/test/gcd_sky130.def
- src/ppl/test/place_pin7.defok
- src/ppl/test/place_pin7.ok
- src/ppl/test/place_pin7.tcl
- src/ppl/test/regression_tests.tcl
Fixes:
- off grid violations in pins since skywater has a mfg grid of 5nm and a DBU of 1000, this leads to rounding errors when computing the pin shape by /2
> ppl: ensure pin shape width/height is an even multiple of the dbu's since they are divided by 2 causing off grid violations

- src/CMakeLists.txt
- src/Main.cc
- src/OpenRoad.cc
par and pay_py will cause `ERROR: Something is wrong with flag 'flagfile' in file 'Users/corentinl/work/main/build_make/_deps/absl-src/absl/flags/parse.cc'. One possibility: file 'Users/corentinl/work/main/build_make/_deps/absl-src/absl/flags/parse.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.` on apple silicon when launches executable, so temporarily remove until or-tools fix this problem.
> remove par and par_py until they work on apple silicon.

- src/drt/src/rp/FlexRP.h
- src/drt/src/rp/FlexRP_prep.cpp
This code is never called and has via names and layer numbers hard coded in it. I presume it also predates prep_minStepViasCheck which should handle minstep violations in a more generic way.
> drt/rp: Remove unused GF12 minstep code

- src/par/CMakeLists.txt
See https://github.com/The-OpenROAD-Project/OpenROAD/issues/2989
> Fix compile fail on arm64 for Ubuntu 22.04

- CMakeLists.txt
Fixes problem described here https://stackoverflow.com/questions/74996365/cmake-error-at-least-one-entry-of-url-is-a-path-invalid-in-a-list
> Updates CMake GTest fetch rule

- src/odb/src/defin/definReader.cpp
Removes exit call from defin which makes debugging impossible, replaced with an error
> odb: use logger error instead of exit(2) in definReader

- src/drt/src/pa/FlexPA_prep.cpp
genPatterns_gc miscalculates the bounding box used for gc, applying the lower x coordinate to all other coordinates. If we are unlucky this bounding box is huge and could contain over 100,000 objects. As a result gc wastes a lot of time initialising all the objects within the bounding box.
Fixing this significantly improves the start up time for the ispd19_test10 test case.
> drt/pa: Fix bounding box calculation in genPatterns_gc

- CMakeLists.txt
- src/dpl/CMakeLists.txt
- src/drt/CMakeLists.txt
- src/odb/CMakeLists.txt
- src/rcx/src/CMakeLists.txt
- src/utl/CMakeLists.txt
- third-party/CMakeLists.txt
Adds a CMake boolean option `ENABLE_TESTS` (`ON` by default) that will disable tests if defined as `OFF`. Speeds up compile times significantly and allows compiling in environments where GoogleTest support is iffy, e.g. Nix.
> Allow Disabling Tests

- src/pdn/src/PdnGen.cc
- src/pdn/src/grid.cpp
- src/pdn/src/grid_component.cpp
- src/pdn/src/shape.cpp
- src/pdn/src/shape.h
This should help speed up: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/940
Changes:
- Stops rebuilding the obs rtrees and just use a filter to ignore the shapes
> pdn: use RTree filter to avoid rebuilding rtrees for obstructions

- src/grt/src/fastroute/src/FastRoute.cpp
This fixes a crash when using global_route_debug -st
> grt: Correctly iterate Steiner Tree in gui

- src/drt/src/gc/FlexGC_eol.cpp
- src/drt/src/gc/FlexGC_main.cpp
We are leaking memory in checkMetalSpacing_short_obs() via gcRect rect3. There doesn't seem to be a reason for dynamically allocating this, so just move it to the stack.
> drt/gc: Fix memory leak in checkMetalSpacing_short_obs()

- src/drt/src/TritonRoute.cpp
- src/drt/src/ta/FlexTA.cpp
- src/drt/src/ta/FlexTA.h
- src/drt/src/ta/FlexTA_end.cpp
Only save updates in TA when distributed mode is on. On my machine this reduces the peak memory usage on ispd2019 test10 from 44 GB to 37 GB.
> drt/ta: Reduce memory usage

- src/grt/src/GlobalRouter.cpp
This fix is related to a bug in mock-array-big, where nets that only have pins in M4 were routed in lower layers (M2). The root cause of the issue was using the macro extensions, making FastRoute detect congestion in M4. Removing the macro extensions fixed the issue.
But while debugging the code, I found this minor bug where the min routing layer calculated from the pins layer wasn't correct. This fix ensure the `min_pin_layer` will have the correct value.
> grt: fix net min layer calculation

- src/drt/src/db/obj/frInstBlockage.h
- src/drt/src/db/obj/frInstTerm.h
Rearrange the memory layout such that the 4 byte id_ (from frBlockObject) and 4 byte index_in_owner_ are adjacent, saving 8 bytes.
This reduces memory consumption by 300MB on ispd2019 test10.
> drt: Shrink frInstBlockage and frInstTerm

- src/cts/src/TechChar.cpp
- src/cts/src/TechChar.h
- src/dbSta/include/db_sta/MakeDbSta.hh
- src/dbSta/include/db_sta/dbSta.hh
- src/dbSta/src/CMakeLists.txt
- src/dbSta/src/MakeDbSta.cc
- src/dbSta/src/dbSta.cc
- src/dbSta/src/dbSta.i
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/MakeResizer.cc
- src/rsz/src/Resizer.cc
Avoids dependency on OpenRoad object for creation of block-level dbSta instances.
Remove openroad object dependency from resizer.
Additional development context: we should be able to move dbSta.cc to dbSta_lib once we've abstracted the GUI dependency (and somehow addressed the OpenRoad observer). Those two things still couple it to the OpenRoad object after this change. This is an intermediate step that we felt was pretty self-contained and smaller / easier to review vs needing to "go for broke" of doing the full separation in this PR + GUI changes + OpenRoad observer changes.
> Separate the creation of dbSta from initialization.

- README.md
DependencyInstaller.sh is an implementation detail of user setup procedures and Docker install scripts.
Also, remove some copy and paste from DepedencyInstaller.sh, will quickly become quickly out of date. Use single source of truth: the scripts themselves.
Major platforms are now supported and if some platform is not supported, the user will discover it and hopefully submit PRs to solve quirks.
> setup: single source of truth and user oriented documentation

- src/drt/src/pa/FlexPA_prep.cpp
During pin access, we currently hard wire the size of the gc bounding box. Depending on the technology, 3000 could be too big or too small.
Change this to be 5 wire pitches of the metal layer of the pin, which should be enough area to determine if we can safely access the pin.
> drt/pa: Better sizing of gc bounding box

- src/rsz/src/Resizer.cc
The result of `Resizer::findMaxWireLength1()` will eventually be
passed to this function, and can return `(double)sta::INF`. Which
when converted to an int in `metersToDbu` blows up.
```c++
double Resizer::findMaxWireLength1()
{
double max_length = INF;
for (const Corner* corner : *sta_->corners()) {
if (wireSignalResistance(corner) > 0.0) {
for (LibertyCell* buffer_cell : buffer_cells_) {
double buffer_length = findMaxWireLength(buffer_cell, corner);
max_length = min(max_length, buffer_length);
}
}
}
return max_length;
}
```
I added the code in this PR to protect against this.
> rsz: Fix int overflow SIGILL

- src/drt/src/ta/FlexTA_assign.cpp
This check should be valid for all unidirectional layers, not just GF14.
> drt/ta: Remove GF14 check in pin cost

- src/odb/src/db/dbProperty.cpp
- src/odb/src/db/dbProperty.h
I decided to modernize the class with std::variant. The source of the leak was not freeing char* on replace. This new system relies on std::string which makes things simpler.
> [odb]: Fixed memory leak in dbProperty

- src/drt/src/dr/FlexGridGraph_maze.cpp
There is code in getEstCost() to add a penalty to vias placed too close to the destination pin, but it is prevented from running until iteration 30, and then only in non rip up iterations.
This helped a test case with fat vias, where it went from taking 3 iterations to 1 iteration to become drc clean.
> drt/dr: Always apply via spacing to dst pin check

- src/dpl/src/Opendp.tcl
- src/dpl/test/fillers3.ok
- src/dpl/test/fillers3.py
- src/dpl/test/fillers4.ok
- src/dpl/test/fillers4.py
This is a different solution to #2839 
This preserves the matching without requiring the -regexp flag.
> dpl: filler masters use string match instead of regexp to avoid matching everything

- src/dbSta/src/MakeDbSta.cc
- src/dbSta/src/dbSta.cc
* In Google build gui::Gui::get()->registerRenderer call fails when built without gui support, the added `if` statement protects against that.
* gui_is_on check was inadvertently flipped.
> [db_sta]: Fixes initialization without gui

- src/grt/src/RepairAntennas.cpp
Fixes https://github.com/The-OpenROAD-Project/OpenLane/issues/1740
When creating the tmp routing for ANT evaluation, add points in the wire encoder for the segments that overlap with the pin shape to avoid the order_wires error message about the short between the tmp wire and the pin shape.
> grt/ant: fix error when creating tmp routing for antenna checker

- include/ord/OpenRoad.hh
- include/ord/OpenRoadObserver.hh
- src/OpenRoad.cc
- src/dbSta/include/db_sta/dbSta.hh
- src/dbSta/src/CMakeLists.txt
- src/drt/test/stubs.cpp
- src/gui/src/mainWindow.h
- src/ifp/src/InitFloorplan.i
- src/upf/src/upf.cpp
This makes the OpenRoadObserver not depend on the concrete
implementation of the OpenRoad object itself, so that the dbSta.cc file
can be moved to the non-application target dbSta_lib.
> Break Observer OpenRoad coupling

- src/OpenRoad.cc
- src/odb/include/odb/db.h
- src/odb/include/odb/dbStream.h
- src/odb/src/db/dbDatabase.cpp
- src/odb/src/db/dbDatabase.h
- src/odb/src/db/dbStream.cpp
- src/odb/src/swig/common/swig_common.cpp
- src/odb/test/cpp/TestAccessPoint.cpp
- src/odb/test/cpp/TestLef58Properties.cpp
More idiomatic C++ means less manually written error handling and more reliance on exceptions.
This was inspired by seing fread() turning up and I think ifstream should be faster because as it is inlined and we're reading gigabytes.
I suspect, but don't have a way to measure precisely and accurately enough a 10% improvement: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1001#issuecomment-1517339354
10% might not seem like much, but if the performance problems in the GUI can be addressed, 10% grows to become a substantial part of the load time. Let's say the rest of the load is made 5x faster, then 20% today becomes 50% of the load time.
> database: switch to ifstream, less code, more idiomatic C++

- src/mpl2/CMakeLists.txt
Fixes:
- cmake will fail because GoogleTest is not included when ENABLE_TESTS is off, this mirrors the behavior of drt and openroad
> turn off tests in mpl2 when ENABLE_TESTS is off

- src/gui/src/mainWindow.cpp
Reverts The-OpenROAD-Project/OpenROAD#3251
This leads to a memory error.
> Revert "gui: Fix undefined behavior sanitizer error"

- etc/DependencyInstaller.sh
if the user knows about the pros and cons
of using bashrc, then they don't need
the tip.
The documentation now encourages a harmless way to set up dependencies and environment that is not persisted across bash sessions/restart/logout, which means that a user can safely get back to "square one" by rebooting his computer.
Modifying the default cmake of the system can cause very subtle and hard to track down problems.
> setup: remove possibly harmful advice

- src/gui/src/layoutViewer.cpp
Ensures the last painted time is recorded after the painting is done to better make use of interval on large designs.
> gui: fix last painted time

- src/gpl/src/graphics.cpp
- src/grt/src/heatMap.cpp
- src/gui/include/gui/heatMap.h
- src/gui/src/heatMap.cpp
- src/psm/src/pdnsim.cpp
This is an attempt to speed up handling of heatmaps in the gui.
1. change the underlying data type from an rtree to a 2d array.
2. only draw the portion of the heatmap that is currently visible
3. when zoomed out merges multiple bins together to avoid drawing boxes that are less an than a pixel.
> gui: scale heatmap with gui scaling

- src/dft/src/replace/ScanReplace.cpp
I found this bug while implementing scan stitching. The unit tests for this part will in the PR for scan stitching
> Fix finding the clocks of the cells after scan replace and rollback

- src/gui/src/layoutViewer.cpp
With this change, all rendering time is pretty much accounted for, previously there could be significant discrepancies between what was logged and the total rendering time.
<!DOCTYPE html>
<html>
<head>
</head>
<body>
[DEBUG | GUI-draw] | manufacturing | grid |   | 2.62222E-04 | sec
-- | -- | -- | -- | -- | -- | --
[DEBUG | GUI-draw] | inst | search |   | 4.86770E-01 | sec
[DEBUG | GUI-draw] | inst | outline | render | 1.13920E+00 | sec
[DEBUG | GUI-draw] | blockages |   |   | 9.15498E-04 | sec
[DEBUG | GUI-draw] | layer | V0 | render | 9.15700E-06 | sec
[DEBUG | GUI-draw] | layer | M1 | render | 2.43998E-01 | sec
[DEBUG | GUI-draw] | layer | V1 | render | 6.62100E-06 | sec
[DEBUG | GUI-draw] | layer | M2 | render | 3.04803E-01 | sec
[DEBUG | GUI-draw] | layer | V2 | render | 7.07200E-06 …
> openroad: add more GUI timers

- etc/DependencyInstaller.sh
Some small fixes and cleanups of the dependency installer script
* Check for and install pcre2 as a swig dependency (not all systems may have a suitable version)
* Eliminate some spurious warnings about "file not found" when grepping files that don't exist
* Formatting
* If installing to a non-default location, emit a sourceable script to set up the environment
* Convert relative paths to absolute when passing to installers
> DependencyInstaller.sh Fixes

- src/gui/src/layoutViewer.cpp
Was randomly scrolling through code and spotted this. Seems like a typo? Feel free to close if it isn't.
> gui: fix typo in LayoutViewer::drawInstanceNames

- .gitignore
> gitignore: ignore Scala .metals/ folders

- src/gpl/src/placerBase.cpp
if the die area is too big, an out of error message is printed, rather than a std::vector() max_size() message.
out of memory is a hair better than the more internal error message from std::vector().
> gpl: improve error message upon too big die area

- src/ppl/src/IOPlacer.cpp
- src/ppl/test/large_groups3.ok
- src/ppl/test/large_groups4.defok
- src/ppl/test/large_groups4.ok
- src/ppl/test/large_groups4.tcl
- src/ppl/test/regression_tests.tcl
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3338
Only constrained groups placed during fallback mode are placed in the middle of the constrained region.
> ppl: place groups in fallback mode in the middle of the constraint region

- src/grt/src/GlobalRouter.cpp
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3372
> grt: use intersection between pin and die area as pin shape when pin is partially outside the die area

- src/dpl/CMakeLists.txt
- src/dst/CMakeLists.txt
Seems like `find_package` directive were missing for those two modules.
Note: this is one of the patches used by the packages here to ensure we build against the version of TCL packaged in conda:
https://github.com/hdl/conda-eda/tree/master/pnr/openroad
Related: https://github.com/hdl/conda-eda/pull/334
/cc @QuantamHD
> dpl,dst: find tcl package

- src/gui/include/gui/gui.h
- src/gui/src/bufferTreeDescriptor.cpp
- src/gui/src/bufferTreeDescriptor.h
- src/gui/src/gui.cpp
- src/gui/src/layoutViewer.cpp
- src/gui/src/layoutViewer.h
- src/gui/src/mainWindow.cpp
- src/gui/src/mainWindow.h
Hi,
I added the option to select/highlight all buffer trees in the gui menu.
I didn't find very great case to test is, so I manually added to gcd test multiple buffer and connect them to random FF ( if you got better test case please let me know), the result looks like that:
Few notes:
- To get all the buffers I used the existing class of BufferTrees. In that class there is condition that only if the timing source of the inst is equal to TIMING it consider buffer, I'm not fully understood that condition so for now I added another option to work around it and create bufferTree even if the timing source don't defined.
-  When selected all buffer tree all the inst/nets/Bterms in of the buffer trees are selected, I can change it easily I just wasn't sure  if that was the original propose.
- …
> Add select all buffer trees #3290

- CMakeLists.txt
- src/CMakeLists.txt
Created a new variable "ASAN" in the top-level CMakeLists.txt. This variable is OFF by default. To enable building with Address Sanitizer, set the ASAN variable to ON by passing the argument to CMake "-DASAN=ON".
When ASAN is ON, the src/CMakeLists.txt file adds compile and link options for using Address Sanitizer to the directory properties and also to the target properties. These compile and link options will be applied to all tools in the src directory and to openroad itself.
Fixes #2738
> Add CMake variable for building with Address Sanitizer

- src/dpl/include/dpl/Opendp.h
- src/dpl/src/Grid.cpp
- src/dpl/src/Opendp.cpp
- src/dpl/src/dbToOpendp.cpp
I found a destructor related bug in one of Google's test cases. Rather than debug it I figured I'd just move it to vector, and not worry about it.
> dpl: Move Grid from pointers to vectors

- src/dbSta/src/dbSta.cc
This enables the file redirects that are available to some commands like `report_checks`, this will be helpful to write out specific timing reports to a file instead of only having the log available
> dbsta: enable file redirects

- src/rsz/src/RepairSetup.cc
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
- src/rsz/test/repair_fanout7.tcl
- src/rsz/test/repair_fanout8.tcl
@maliberty @tspyrou : Here is the PR to turn off gate cloning by default. It also changes the option in the TCL command to:
-enable_gate_cloning so we can evaulate the ORFS tests and enable as needed. The two regressions have also been updated.
> Gate cloning off by default

- src/gui/src/scriptWidget.cpp
fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2675
logging tried to render the log message synchronously, which
caused a lockup as the main event loop was processed during
the reporting of an Xcb error.
With the upcoming https://github.com/The-OpenROAD-Project/OpenROAD/pull/3370 fix to rendering where rendering is
cancelled and restarted when it takes to long, it's not
too bad to wait until the GUI is idle before updating the
log message in the GUI.
> logging: fix lockup when resizing window in Docker

- src/rsz/src/RepairSetup.hh
missed changing this file when flipping the gate cloning argument
> fix: mismatch between .hh and .cc in argument name

- src/odb/src/lef/lef/lefiMacro.cpp
Assigning amo to a value has no effect as it is assigned again inside the for loop or after the for loop. 
```
2040         antennaModelAllocated_ = lefMaxOxides;
>>>     CID 1513198:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value from "this->pinAntennaModel_[0]" to "amo" here, but that stored value is overwritten before it can be used.
2041         amo = pinAntennaModel_[0];
```
> lef parser: Fix new defect reported by Coverity Scan

- src/OpenRoad.cc
- src/odb/include/odb/db.h
- src/odb/include/odb/lefout.h
- src/odb/src/db/dbBlock.cpp
- src/odb/src/db/dbMTerm.cpp
- src/odb/src/db/dbProperty.cpp
- src/odb/src/db/dbTechLayer.cpp
- src/odb/src/db/dbTechLayerAntennaRule.cpp
- src/odb/src/db/dbTechLayerSpacingRule.cpp
- src/odb/src/db/dbTechMinCutOrAreaRule.cpp
- src/odb/src/lefout/lefout.cpp
- src/odb/src/swig/common/swig_common.cpp
Moves file output mechanism to ostreams instead of FILE*. I want an ostream so I can run unit tests without having to rely on the filesystem. Also it's just nice to modernize this interface
> odb: Modifies abstract LEF writer to work on ostreams 

- src/cts/src/CMakeLists.txt
- src/cts/src/CtsGraphics.cpp
- src/cts/src/CtsGraphics.h
- src/cts/src/TritonCTS.i
Some header files are named similarly which presents a problem in Google's version of the build. I could fix it other ways, but this would be helpful for us.
> cts: Rename graphics class to disambiguate header files

- etc/DependencyInstaller.sh
- third-party/gtest/CMakeLists.txt
This is installed from ./third-party/gtest/CMakeLists.txt
> Remove libgtest-dev from DependencyInstaller

- src/grt/src/GlobalRouter.cpp
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3535
> grt: do not destroy existing gcell grid when reading guides

- src/odb/src/def/def/defiNet.cpp
- src/odb/src/def/def/defiNet.hpp
- src/odb/src/def/def/defrReader.cpp
- src/odb/src/def/def/defrReader.hpp
This PR should fix the 3 defects.
```
** CID 1513255:  Resource leaks  (RESOURCE_LEAK)
/src/odb/src/def/def/defrReader.cpp: 2158 in LefDefParser::defrAddAlias(const char *, const char *, int)()
________________________________________________________________________________________________________
*** CID 1513255:  Resource leaks  (RESOURCE_LEAK)
/src/odb/src/def/def/defrReader.cpp: 2158 in LefDefParser::defrAddAlias(const char *, const char *, int)()
2152       // strcpy(v1, value);
2153       if (marked != 0)
2154         marked = 1;  // make sure only 1 digit
2155       sprintf(v1, "%d%s", marked, value);
2156     
2157       defData->def_alias_set[k1] = v1;
>>>     CID 1513255:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "k1" going out of scope leaks the storage it points to. …
```
> def parser: fix new coverity defects 

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/options.h
- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
Fixes #3410 
I added a function to renderThread.cpp called drawItermLabels(), which gets called in exactly the same way as drawInstanceNames().
I replaced the variable Rect instance_box = inst->getBBox()->getBox(); with Rect iterm_box = inst_iterm->getBBox();. I also obtain the name of an iterm through its corresponding mterm, since dbMTerm has a getName() funciton but dbITerm does not.
I left in the same checks as drawInstanceNames() to prevent printing the names when text_height_check > ..bbox_in_px.height(). This caused the iterm labels to not be drawn at any zoom level.
I then commented out those checks, so I expected the labels to always be drawn. The labels are then drawn even when fully zoomed out, and in the correct locations it seems. However as I zoom in, the labels become …
> gui: Add iterm labels to layout viewer

- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
- src/gui/src/mainWindow.cpp
This PR is to be linked with the Issue #3404.
With these changes I'm adding the remaining properties in the Technology and Block inspection which were requested by @gadfort and listed in #3477.
Some important considerations:
In the dbVia, I created a property list Shapes, because a dbVia may have more than 3 geometries as the cut layer may have more than one. As the layers can be inspected through this new property, I thought there was no need to create a "Layers" property of its own.
The way the DbTechViaLayerRuleDescriptor is currently implemented, there will be inevitably via-layer rules with the same name. I couldn't find a solution to that, because there is neither a getName() method nor a way to access the ViaRule through the dbTechViaLayerRule object (The latter would make possible …
> gui: Add remaining properties to Tech and Block inspection

- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
Additional refactoring after #3528
I added a function that removes most code duplication from drawInstanceNames() and drawITermLabels(). It takes parameters for a string, color, font, rect, but also a painter pointer. Perhaps this is passing around the QPainter pointer too many times?
> gui: refactor with new function drawTextInBBox()

- src/dft/src/Dft.cpp
- src/dft/src/architect/ScanArchitect.cpp
- src/dft/src/architect/ScanArchitect.hh
- src/dft/src/architect/ScanArchitectHeuristic.cpp
- src/dft/src/architect/ScanChain.cpp
- src/dft/src/architect/ScanChain.hh
- src/dft/src/cells/ScanCell.cpp
- src/dft/src/cells/ScanCell.hh
- src/dft/src/clock_domain/ClockDomain.cpp
- src/dft/src/clock_domain/ClockDomain.hh
- src/dft/src/stitch/ScanStitch.cpp
- src/dft/test/cpp/TestScanArchitectHeuristic.cpp
- src/dft/test/scan_architect_clock_mix_sky130.ok
Several refactors:
* changing shared_ptrs to unique_ptr in dft code. The owner should be the scan chains
* Changing the responsibility of sorting the scan cells inside the scan chains to architect instead of stitch. Stitch should only create the connectivity and not decide the order of the scan cells.
* Fix a small bug where we didn't show  the change of clock if we were changing clock edges.
> dft: misc refactors

- src/gui/src/layoutViewer.cpp
Fixes #3573.
The die was actually being painted, but outside the scope of the layoutviewer’s viewport.
> fixes #3573: GUI designs with origin not at ( 0 , 0 )

- src/drt/src/db/drObj/drNet.cpp
- src/drt/src/dr/FlexDR.cpp
- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexGridGraph.h
- src/drt/test/gcd_nangate45_distributed.tcl
In this PR, I am reducing the data sent to servers and received by leaders to the minimal needed form. I studied the data needed by both ends. The server only needs the initial data of worker including the routebox, extBox, costs and markers. The leader only needs the nets and the bestMarkers. The nets don't need to include the initial segments, it only needs the final segments to be committed to the design.
The main part that has beed reduced here is the gridGraph. The server doesn't need the gridGraph since it initializes it. and the leader doesn't need the gridGraph back. This minimization showed noticeable speedup and memory recduction in distributed detailed routing.
> Reduce data transferred in distributed detailed routing

- src/rsz/src/EstimateWireParasitics.cc
Closes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3588
Avoid special nets in wire estimation.
@openroadie FYI
> rsz: dont estimate parasitics on special nets

- src/gui/include/gui/gui.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/stub.cpp
This should add a swig command `gui::trigger_action`, which should not be for general use, but only debugging.
FYI @maliberty 
For https://github.com/The-OpenROAD-Project/OpenROAD/issues/3609 you would just need to do `gui::trigger_action "timing_report.Update"`
> gui: add trigger action command to swig to allow for easier debugging

- README.md
- docs/conf.py
- docs/requirements.txt
- docs/revert-links.py
Target is to have maintainable mermaid diagrams rather than svgs
@vvbandeira
> [Docs] Prototype for mermaid diagram

- src/rsz/README.md
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/RepairHold.cc
- src/rsz/src/RepairHold.hh
- src/rsz/src/RepairSetup.cc
- src/rsz/src/RepairSetup.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
- src/rsz/test/regression_tests.tcl
- src/rsz/test/repair_fanout6.ok
- src/rsz/test/repair_fanout7.ok
- src/rsz/test/repair_fanout8.ok
- src/rsz/test/repair_hold9_verbose.ok
- src/rsz/test/repair_hold9_verbose.tcl
- src/rsz/test/repair_setup1.ok
- src/rsz/test/repair_setup2.ok
- src/rsz/test/repair_setup3.ok
- src/rsz/test/repair_setup4.ok
- src/rsz/test/repair_setup4_verbose.ok
- src/rsz/test/repair_setup4_verbose.tcl
- src/rsz/test/repair_setup5.ok
- src/rsz/test/repair_setup6.ok
Adds:
- adds number of violating endpoints to setup repair (to mirror the behavior of the repair hold).
- adds a `-verbose` to `repair_timing` to print the status of the repair.
Motivation:
repair_timing can run for a very long time on some designs and it would be helpful to be able to see what progress if any is actually being made.
Current format:
```
Iteration | Resized | Buffers | Cloned Gates | Pin Swaps |   WNS   |   TNS   | Endpoint
```
printed every 10 repairs (could increase of decrease that). It doesn't seem to impact the runtime (atleast from what I could tell).
If there are suggestions for alternative headings or phrasing I think that would be helpful, since I just grabbed the first set that came to mind.
@maliberty @openroadie I noticed that the pin swap goes negative (this …
> rsz: print progress

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/BufferedNet.cc
- src/rsz/src/EstimateWireParasitics.cc
- src/rsz/test/repair_hold10.ok
Issue:
- `set_layer_rc` is using the routing level to store the layer RCs, this causes the vias to be stored and overwrite eachother.
Changes:
- use `getNumber` instead of `getRoutingLevel` to store and recover the layer RCs so vias are recorded correctly.
> rsz: fix layerRC for vias

- src/psm/README.md
- src/psm/include/psm/pdnsim.h
- src/psm/src/CMakeLists.txt
- src/psm/src/MakePDNSim.cpp
- src/psm/src/get_power.cpp
- src/psm/src/get_power.h
- src/psm/src/get_voltage.cpp
- src/psm/src/get_voltage.h
- src/psm/src/ir_solver.cpp
- src/psm/src/ir_solver.h
- src/psm/src/pdnsim.cpp
- src/psm/src/pdnsim.i
- src/psm/src/pdnsim.tcl
- src/psm/test/Nangate45_data/Nangate45_corners.rc
- src/psm/test/aes_asap7_vdd.ok
- src/psm/test/aes_test_vdd.ok
- src/psm/test/aes_test_vdd_set_node_density.ok
- src/psm/test/aes_test_vdd_set_node_density_fact.ok
- src/psm/test/aes_test_vss.ok
- src/psm/test/corners.ok
- src/psm/test/corners.tcl
- src/psm/test/gcd_all_vss.ok
- src/psm/test/gcd_em_test_vdd.ok
- src/psm/test/gcd_no_vsrc.ok
- src/psm/test/gcd_test_vdd.ok
- src/psm/test/gcd_vss_no_vsrc.ok
- src/psm/test/pdnsim_aux.py
- src/psm/test/regression_tests.tcl
Changes:
- adds a `-corner` flag to `analyze_power_grid` and `write_pg_spice` to allow PSM to get power numbers for a specific corner and parasitic values from resizer.
- If `-corner` is not used, there are no changes in behavior.
> psm: analysis across corners

- src/psm/src/ir_solver.cpp
It's possible for the sta cmdCorner to be a nullptr which causes a segfault
```
sta::set_cmd_corner NULL
check_power_grid -net VDD
```
This ensures that the segfault cannot occur, by either picking the first available corner or raising an error.
> psm: enforce corner is not nullptr to avoid segfault

- src/psm/include/psm/pdnsim.h
Fixes segfault on non-initialized memory
> psm: ensure corner_ is initialized to nullptr

- src/rsz/src/RepairSetup.cc
Changes:
- avoids printing the verbose messages when there is nothing to do.
Fixes:
- segfault when clock network has been corrupted by CTS, causing OpenSTA to return nullptr vertexes during printing.
> rsz: return if nothing to repair

- src/drt/src/db/tech/frTechObject.h
- src/drt/src/io/io_parser_helper.cpp
Changes:
- avoids segfault when default via is empty (closes #3654)
- ensures drt doesnt go beyond the layer list when iterating over it in `buildGCellPatterns`
> drt: check layers 

- src/ppl/README.md
- src/ppl/include/ppl/IOPlacer.h
- src/ppl/src/IOPlacer.cpp
- src/ppl/src/IOPlacer.i
- src/ppl/src/IOPlacer.tcl
- src/ppl/src/Netlist.h
- src/ppl/src/SimulatedAnnealing.cpp
- src/ppl/src/SimulatedAnnealing.h
- src/ppl/test/annealing_mirrored1.defok
- src/ppl/test/annealing_mirrored1.ok
- src/ppl/test/annealing_mirrored1.tcl
- src/ppl/test/annealing_mirrored2.defok
- src/ppl/test/annealing_mirrored2.ok
- src/ppl/test/annealing_mirrored2.tcl
- src/ppl/test/annealing_mirrored3.defok
- src/ppl/test/annealing_mirrored3.ok
- src/ppl/test/annealing_mirrored3.tcl
- src/ppl/test/annealing_mirrored4.defok
- src/ppl/test/annealing_mirrored4.ok
- src/ppl/test/annealing_mirrored4.tcl
- src/ppl/test/annealing_mirrored5.defok
- src/ppl/test/annealing_mirrored5.ok
- src/ppl/test/annealing_mirrored5.tcl
- src/ppl/test/regression_tests.tcl
For now, mirrored pins and groups are only moved inside the movePinToFreeSlot function.
Swapping mirrored pins has a level of complexity similar to swapping pin groups, and they will be added to the swap in a future PR.
> ppl: support for mirrored pins inside annealing

- src/drt/src/db/tech/frTechObject.h
- src/drt/src/io/io.cpp
- src/drt/src/io/io_parser_helper.cpp
- src/drt/test/ndr_vias1.ok
- src/drt/test/ndr_vias2.ok
- src/drt/test/top_level_term.ok
- src/drt/test/top_level_term2.ok
- src/grt/test/pin_access1.ok
- src/grt/test/pin_access2.ok
Issue:
if multiple vias are defined before the first routing level, the `VIA_ACCESS_LAYERNUM` will be pointing to a via instead of the first routing level.
Changes:
- set VIA_ACCESS_LAYERNUM when adding the first routing level to ensure it matches the layer stack
- just loop over layers to init gcells to avoid assumptions about the start of the layer stack
- minor changes to error message for guideIN to make it clear what the via access is.
> drt: set VIA_ACCESS_LAYERNUM when adding the first routing level 

- src/rsz/src/RecoverPower.cc
At the end of the first iteration of the `RecoverPower::recoverPower()` function, the function `Resizer::incrementalParasiticsEnd()` is called, which causes the elimination of the variable `incr_groute_`, which is still used but when it is eliminated, it will cause the error #3659
To correct the error, I moved the `Resizer::incrementalParasiticsEnd()` function to the end of all iterations.
> rsz: Fixing bug when used repair_timing -recover_power

- src/dpl/include/dpl/Opendp.h
- src/dpl/src/CheckPlacement.cpp
- src/gui/src/drcWidget.cpp
In the case of overlapping failures, the tool would draw a bounding box around both overlapping cells together. 
It will also add both cells to the sources in the JSON report.
The json would look like this:
```JSON
{
"name": "Overlap_failures",
"description": "Cells that are overlapping with other cells.",
"violations": [
{
"type": "box",
"shape": [
{
"x": "14",
"y": "14"
},
{
"x": "14.57",
"y": "15.4"
}
],
"sources": [
{
"type": "inst",
"name": "f0\/_285_"
},
{
"type": "inst",
"name": "f0\/_284_"
}
]
},
{
"type": "box",
"shape": [
{
"x": "14",
"y": "14"
},
{
"x": "14.57",
"y": "15.4"
}
],
"sources": [
{
"type": "inst",
"name": "f0\/_285_"
},
{
"type": "inst",
"name": "f0\/_283_"
}
]
}
]
}
```
> Handling overlaps differently

- src/psm/src/ir_solver.cpp
Fixes:
- a typo in the name would cause a segfault, generates an error instead
> psm: add check for missing power net before running

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/layoutViewer.cpp
- src/gui/src/mainWindow.cpp
- src/gui/src/options.h
- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
Adds:
- pin selection control for instances
Changes:
- only allow selection of pins when visible and when layers are visible for that pin
- draw the pin label in the first mpin box that it will fit it otherwise pins are left floating off the metal shape.
> gui: pin selecting and drawing 

- src/gui/README.md
- src/gui/include/gui/gui.h
- src/gui/src/clockWidget.cpp
- src/gui/src/clockWidget.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/gui.tcl
Adds:
- `save_clocktree_image` with options to save with width/height and specify timing corner
This allows for better control of the resulting image since before it was just using the widget sizes which could result in poor quality images.
> gui: make same_clocktree_image a regular tcl command

- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
> gui: render instance text centered, easier to read

- src/drt/src/dr/FlexDR.cpp
step 0 has a very large amount of DRC violations that are not normally interesting.
A DRC report for step 0 can be gotten by setting -droute_end_iter to 0, if that is needed for debugging purposes
> detailed route: do not save step 0 when -drc_report_iter_step is set

- src/ppl/src/SimulatedAnnealing.cpp
- src/ppl/test/annealing2.defok
- src/ppl/test/annealing2.ok
- src/ppl/test/annealing_constraint6.defok
- src/ppl/test/annealing_constraint6.ok
- src/ppl/test/annealing_constraint7.defok
- src/ppl/test/annealing_mirrored5.defok
- src/ppl/test/annealing_mirrored5.ok
Previously, the number of perturbations per iteration was 80% of the total number of pins. However, with the presence of pin groups, using the total number of pins makes little sense since a pin group is moved as a single object. Also, moving pin groups is more expensive than moving lone pins, so designs with many groups were having trouble with the original approach.
With this update, the number of pin groups is considered when calculating the number of perturbations per iteration, avoiding running too many perturbations when the number of groups is large.
> ppl: use the number of lone pins and number of groups to define the default number of perturbations

- src/gui/src/renderThread.cpp
We don't need great accuracy in choosing horizontal or vertical direction for text rendering, but once we have chosen direction, we want to center the text more precisely, so recalculate bounding box of text for elided text.
fixes #3829
> gui: fix text rendering, recalculate dimensions after elide

- src/gui/src/renderThread.cpp
makes it easier to read.  Actual colors depends on PDK and what layers are blocked, etc.
Also, the monitor matters.... black outline + color makes readability more robust against different monitors and backgrounds :crossed_fingers: 
Non-centered text is not affected:
> gui: use black outline for macro labels and other centered text

- src/drt/src/TritonRoute.cpp
- src/drt/src/io/io.cpp
- src/drt/src/io/io.h
- src/drt/src/io/io_parser_helper.cpp
Instead of checking for min-width pins only, I check on all pins and see if they intersect with any routing track on their layer. If and only if none of the pins of a term intersect with any routing track, I fire a warning that this term has no pins on the routing grid.
> Warning when pins are not placed on routing grid

- src/gui/src/heatMap.cpp
Fixes #3863
When creating the mapview of the heatmap, the last column and row were not being taken into account. The situations where the wrong behavior was visible were only those in which the cells of the last column and row were smaller than the grid.
Power density was having the same problem.
> gui: fix placement and power density heatmaps

- src/grt/src/heatMap.cpp
Fixes #3862 
The routing map last column/row were being skipped when populating the map.
> gui: consider last row/column when populating routing map

- docs/toc.yml
- src/drt/LICENSE
- src/drt/README.md
Todos
- Clarify if these parameters are still needed `OR_seed`, `OR_k`, `no_pin_access`,  `repair_pdn_vias`
- Missing keyword argument specification for these tcl procs: `step_dr`, `check_drc`
[should i use sta namespace or drt?]
> [Docs] drt documentation

- src/ppl/include/ppl/IOPlacer.h
- src/ppl/src/IOPlacer.cpp
- src/ppl/src/IOPlacer.i
- src/ppl/src/IOPlacer.tcl
- src/ppl/test/ppl_aux.py
- src/ppl/test/write_pin_placement1.defok
- src/ppl/test/write_pin_placement1.tcl
- src/ppl/test/write_pin_placement1.tclok
- src/ppl/test/write_pin_placement2.defok
- src/ppl/test/write_pin_placement2.tcl
- src/ppl/test/write_pin_placement2.tclok
- src/ppl/test/write_pin_placement3.defok
- src/ppl/test/write_pin_placement3.tcl
- src/ppl/test/write_pin_placement3.tclok
The option to place an individual pin as PLACED does not work as expected. If place_pin is called before placing all pins, the individual pins will be modified. This PR sets the pins placed individually always as FIXED, avoiding changing them later in the PPL flow.
> ppl: update place_pin command

- src/dpl/src/Grid.cpp
In some cases you can have a double height row
with only a single layer row below it instead of two. In that case if you were painting a double height
cell then you would go out of bounds.
This commit adds a check to ensure, that does not happen.
> dpl: Fixes out of bounds in grid paint

- src/gui/src/gui.cpp
- src/gui/src/mainWindow.cpp
Fixes the `gui::hide` which broke in be4378f3473e4603687f1ad2261b02541284f7d1
> gui: restore gui hide behavior

- etc/deltaDebug.py
Find the right level of detail to look for cuts and complete cuts at this level.
This speeds up deltaDebug as it is not necessary to start at the top every time an error is found and I believe it to be general and significant improvement over the current heuristic for searching for cuts.
I do believe that even better heuristics exist for deltaDebug, but this step is significant enough and simple enough that I think it makes sense to accept this PR as a new baseline.
I had a case of a deltaDebug that I stopped after 2 days, with this change it takes "only" 12 hours or so.
> deltaDebug: tweak heuristic to speed up bisection

- etc/deltaDebug.py
The granularity is increased when no error found and reduced when errors are found.
Previously the granularity would go all the way to two sections as soon as an error was found, this resulted in a lot of extra iterations when the approperiate granularity to find errors is high.
This results in fewer iterations.
After:
- 217 steps to complete insts, in my test case each negative test was on the order of 10 minutes
- 596 steps to complete nets, here a negative test was no more than a minute or so
Before:
- 270 steps to complete insts
- 526 steps to complete nets
> deltaDebug: decrease granularity by steps instead of going straight back to start

- README.md
- docs/toc.yml
- docs/user/Build.md
- docs/user/ORFS.md
Addresses the following comments @vvbandeira @dralabeing 
1. The OpenROAD installation does not currently link to pre-built binaries. This is only shown for ORFS. This should be added here as well: https://openroad.readthedocs.io/en/latest/user/Build.html
This is also missing the OS information as in ORFS. 
2. The link from OpenROAD to ORFS lands on this page : https://openroad.readthedocs.io/en/latest/user/ORFS.html.  I think this can be removed since it is redirected to another page  : https://openroad-flow-scripts.readthedocs.io/en/latest/.
3. There is a redundant/recursive link reference the readme from the readme landing here: 81c8ee17-ef2e-45bf-a0cd-351f8787aca2.png
Remove the line "Documentation is also...."
> [Docs] Fix prebuilt instructions and comments

- src/grt/src/GlobalRouter.cpp
- src/grt/test/inst_pin_out_of_die.ok
It seems like the code meant to do this, but got warn/error switched around. Otherwise, `GRT-0028` is actually unreachable.
> grt: print all pins out of die area before erroring

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
- src/rsz/test/regression_tests.tcl
- src/rsz/test/report_floating_nets2.ok
- src/rsz/test/report_floating_nets2.tcl
- src/rsz/test/report_floating_nets2.v
- src/rsz/test/report_floating_nets3.ok
- src/rsz/test/report_floating_nets3.tcl
- src/rsz/test/report_floating_nets3.v
Adds:
- check for input pins with no nets indicating that they are not driven
- unit tests to check
- metrics for floating nets and pins
> rsz: add metrics and pins check to report_floating_nets

- src/dbSta/src/heatMap.cpp
- src/dbSta/src/heatMap.h
- src/gui/include/gui/gui.h
- src/gui/include/gui/heatMap.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/heatMap.cpp
- src/psm/include/psm/pdnsim.h
- src/psm/src/pdnsim.cpp
Adds:
- tcl commands to access heatmap settings
- avoids using corner in dbSta for power density as this can segfault
- ensure nodes are saved after failed IRDrop analysis for better debugging.
> gui: fixes to segfaults and allow for better debugging

- src/dpl/src/Grid.cpp
As mentioned in the comment.
If there's an uneven number of single row height cells, say 21. The above layer mapping coordinates on double height rows will round up, because they don't know if there's 11 or 10 rows of double height cells. This just caps it to the right amount.
> dpl: Handles odd numbers of single height rows in double height context

- src/gui/src/layoutViewer.cpp
Resolves #3998 
Two things are being done here:
1. I am reverting what I have previously changed in #3585. With this change we got back to the problem reported in #3573, which is now fixed (now properly) by this PR.
2. When computing the necessary shift for centralizing the design in the layout viewer, we were not considering the distance that can exist between bound's xMin / yMin and the dbu origin. This was causing the design to the drawn, but not properly displayed in the layout viewer as the center was not being placed correctly. This is distance is now being considered.
> gui: fix fit bad behavior when DIEAREA is outside the first quadrant

- src/grt/src/fastroute/src/FastRoute.cpp
Fixes crash during RCX unit test `names`
> grt: fix crash when global routing grid has only one cell

- src/mpl2/src/hier_rtlmp.cpp
- Fixed the issue of skipping mpl2 directly after initializing the cell position
- For example, in OpenROAD-flow-scripts, mixed sized placement is executed first, and then mpl2 is executed, so mpl2 will be skipped directly in present.
> Fixed the issue of skipping mpl2 directly after initializing the cell position

- src/pdn/src/via.cpp
- src/rsz/src/Rebuffer.cc
Having non-compliant comparators can lead to crashes, infinite loops, or undefined behavior.
This commit makes the comparators follow strict weak ordering.
See:
https://github.com/bashrc-real/Codearchive/blob/master/cpp/Strict_weak_ordering_and_stl.md
> [rsz, pdn]: Fixes Strict Weak Ordering Violations

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/options.h
- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
#Resolves #4050
Also renaming "Misc->Instances->Pin labels" to "Misc->Instances->Pin Name".
> gui: use one control for drawing bterms' marker, geometry and text in the layout

- src/mpl/src/MacroPlacer.cpp
- src/mpl2/README.md
- src/mpl2/include/mpl2/rtl_mp.h
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
- src/mpl2/src/mpl.i
- src/mpl2/src/mpl.tcl
- src/mpl2/src/rtl_mp.cpp
- src/mpl2/test/mp_test1.tcl
- src/odb/include/odb/dbTypes.h
- src/odb/src/db/dbTypes.cpp
Resolves #4068 
In this PR I'm also implementing the command `place_macro` to place macros individually.
The output file of write_macro_placement will be written in the format of `place_macro` commands
as we currently do in PPL.
> mpl2: add command for writing macro placement

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/mpl.i
- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
- src/mpl2/src/rtl_mp.cpp
I'm making three corrections here:
1. I used wrongly the function to snap the macro. The name I chose for the function was misleading its use, so I changed it. I'm using the function correctly now.
2. I realized then that this same function would not work if a macro have pins in only one direction (e. g. `src/mpl2/test/mp_test1.tcl`), so now we calculate the coordinate of the snap origin only when we actually have pins in that direction.
3. Finally, now we also don't try to snap the macro placed by `place_macro` if it has a rotation which is not allowed in HierRTLMP.
Also:
We're now using not only iterms, but bterms in the wirelength computation for adjusting orientation.
> mpl2: corrections in place_macro

- src/mpl2/doc/debugMessages.md
- src/mpl2/src/SACoreHardMacro.cpp
- src/mpl2/src/SACoreSoftMacro.cpp
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/object.cpp
The way the debug messages' groups were structured was making it difficult to debug due to the amount of information related to different steps of HierRTLMP flow.
I divided `macro_placement`and `clustering` into groups with two levels according to the stages of HierRTLMP. They're described in `src/mpl2/doc/debugMessages.md`.
> mpl2: improve debug messages

- src/grt/src/fastroute/src/maze.cpp
Creating vectors with the size necessary to save the routing of an edge.
Fixing git issue #4148
> grt: creating vectors with the size necessary to save the routing of an edge

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
I also changed the names of the methods related to bundledIO clusters to improve readability.
> mpl2: display cluster type when printing physical tree

- src/cts/.gitignore
- src/cts/test/check_buffers_blockages.ok
- src/cts/test/check_buffers_blockages.tcl
- src/dpl/include/dpl/Opendp.h
- src/dpl/test/report_failures.tcl
- src/gui/.gitignore
Minor fixes to avoid creating unwanted report files. Currently, a bunch of files is created when running the regression tests, leaving the branch "dirt" with git status.
> fix gitignore and report file generation

- etc/shell.nix
- src/ant/src/AntennaChecker.cc
- src/cts/src/TritonCTS.cpp
- src/dbSta/src/dbSta.i
- src/dpo/src/Optdp.cpp
- src/dpo/src/detailed_manager.h
- src/drt/src/db/drObj/drNet.h
- src/drt/src/global.h
- src/drt/src/gr/FlexGR.cpp
- src/drt/src/pa/FlexPA.cpp
- src/drt/src/pa/FlexPA.h
- src/drt/src/serialization.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/Net.cpp
- src/grt/src/heatMap.cpp
- src/ifp/src/InitFloorplan.cc
- src/odb/src/lefin/lefTechLayerCutSpacingParser.cpp
- src/odb/src/lefin/lefTechLayerCutSpacingTableParser.cpp
- src/pdn/src/sroute.h
- src/pdn/src/techlayer.cpp
- src/pdn/src/via.h
- src/rmp/src/blif.cpp
* Change uses of `uint` to `odb::uint` where available (by explicit namespace access or `using` as appropriate) or by expansion to `unsigned int` in files where `odb` is not imported
* Change the few uses of `ushort` to `uint16_t`, importing `cstdint` as appropriate
* `src/dbSta/src/dbSta.i`: Change import of `Exception.i` to match that of other `.i` files (Current import only works when `USE_SYSTEM_OPENSTA` is `OFF`)
* Added a recommended compile environment to `./etc/shell.nix` for posterity
---
Granted, this only helps on some freak setups such GCC-based compile environments on aarch64 macOS. I can confirm it doesn't hurt at least (and I hope the CI backs me up on that. 🙂)
> Avoid non-standard use of `uint`/`ushort`

- src/grt/src/fastroute/include/DataType.h
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4201
Initializing variable `last_routelen` in Route structure to be used in the `FastRouteCore::newRipupCheck` function
> grt: initializing variable in Route structure

- src/mpl2/src/hier_rtlmp.cpp
It is not clear from the printed information what 'total area' means.
Why should total area not include halos of macros?
The individual area information is now printed and the user can add those together to get the numbers they need.
> rtlmp: change 'total area' with Core area in debug output

- src/gpl/src/routeBase.cpp
- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/fastroute/include/FastRoute.h
- src/grt/src/fastroute/src/FastRoute.cpp
This reverts commit 27065cbf5d72d0a4e8a2105cf79e661a3eb6b51d, reversing changes made to 2d83b7137cc071085468500522a70b9cc39317b4.
Reverting the congestion layer range update due to failures in the CI.
> Revert "Merge pull request #4262 from eder-matheus/grt_congestion"

- src/rsz/src/Resizer.tcl
* Fix types of `timing__drv__floating__nets` and `timing__drv__floating__pins`, which were mistakenly reported as strings.
> Fix `rsz` metric types

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
After merging #4272, for some designs, the bundled io clusters were still being displayed in a weird location in debug mode after we ran SA for specifically placing children clusters of the root.
I realized then that when incorporating the SASoftMacro results for the root cluster, we were cheating the `fixed_` flag that we set to true when setting a cluster as an IO Cluster. This was being done by changing the SoftMacro pointer address directly and, this way, bypassing the flag. With this, when trying to move these clusters to their real location in the die, they would be stuck in a wrong location, however they should not have been displaced in the first place.
I'm running Secure-CI on this.
Also doing some tiny refactoring/cleaning.
> mpl2: fix SASoftMacro result update

- src/gpl/src/mbff.cpp
> gpl: fix clustering bug

- src/pad/src/PdnGen.tcl
Several of the procs in PdnGen.tcl return an expression that's missing an `expr` wrapper. I believe this is a bug, since a `return` won't evaluate an expression (but rather, the last word will be returned directly):
```tcl
proc foo {} {
return 0 && 1
}
puts [foo]
```
prints 1 rather than 0, as expected.
I caught this with a tool I'm working on, [`tclint`](https://github.com/nmoroze/tclint): 
```
$ tclint . | grep return
```
> pdn: add missing expr to returns

- src/grt/src/fastroute/src/maze.cpp
Small fix for crashes in the secure-ci.
> grt: fix nullptr check to avoid invalid access

- .github/workflows/github-actions-lint-tcl.yml
- src/rsz/src/Resizer.tcl
- tclint.toml
Towards #4347, this PR adds `tclint` to the CI (with a hardcoded file-list) and cleans up the lint warnings in `Resizer.tcl`, which was the first file chosen as a test.
> Add `tclint` to CI and clean `Resizer.tcl`

- CMakeLists.txt
- src/gpl/CMakeLists.txt
- src/gpl/test/CMakeLists.txt
You can now run the GPL tests in parallel with the ctest command.
`ctest -j 40`
Integration tests can be excluded with.
`ctest -j 40 -LE IntegrationTest`
> meta: Moves GPL tests to new CTest Runner

- .github/workflows/github-actions-test-installer.yml
The problem is with the linker order and or-tools
> ci: disable macos installer due to issues upstream

- debian/rules
- test/regression_vars.tcl
The debian installer uses `./obj-x86_64-linux-gnu/src/openroad` instead of `build/src/openroad` as the binary location. This change allows us to set the env var `OPENROAD_EXE` to point to anywhere.
Reference: https://github.com/Precision-Innovations/OpenROAD/actions/runs/7265482983/job/19795253692
> Fix deb installer

- src/odb/include/odb/dbStream.h
This is based on the already existing case for std::map
> odb: adding support to serialize and de-serialize std::unordered_map

- src/dst/src/BalancerConnection.cc
- src/dst/src/LoadBalancer.cc
- src/utl/include/utl/Logger.h
Minor change.
[boost::asio::ip::address](https://www.boost.org/doc/libs/1_80_0/boost/asio/ip/address.hpp) is a class.
> format_as: pass by reference instead of value

- src/gui/src/staGuiInterface.cpp
1000 paths can take a LONG time to update, who needs more than 50 initially?
Alternatively, the GUI could return immediately and populate in the background
> Sta gui 50 paths is enough

- src/odb/include/odb/dbStream.h
- src/odb/src/codeGenerator/schema/scan/dbScanPin.json
- src/odb/src/db/dbScanPin.cpp
- src/odb/src/db/dbScanPin.h
- Makes the code in dbScanPin more simple
- std::variant now is available to be use for serialization by others
> odb: refactoring out serialization code for std::variant

- src/odb/test/cpp/CMakeLists.txt
- src/odb/test/cpp/CallBack.h
- src/odb/test/cpp/TestAccessPoint.cpp
- src/odb/test/cpp/TestCallBacks.cpp
- src/odb/test/cpp/TestGCellGrid.cpp
- src/odb/test/cpp/TestGeom.cpp
- src/odb/test/cpp/TestGroup.cpp
- src/odb/test/cpp/TestGuide.cpp
- src/odb/test/cpp/TestJournal.cpp
- src/odb/test/cpp/TestLef58Properties.cpp
- src/odb/test/cpp/TestMaster.cpp
- src/odb/test/cpp/TestModule.cpp
- src/odb/test/cpp/TestNetTrack.cpp
- src/odb/test/cpp/helper/CMakeLists.txt
- src/odb/test/cpp/helper/env.cpp
- src/odb/test/cpp/helper/env.h
- src/odb/test/cpp/helper/helper.cpp
- src/odb/test/cpp/helper/helper.h
- src/odb/test/cpp_tests.tcl
Some refactors to support subfolders for other projects inside cpp for odb (like scan) and also fixed clang-tidy warnings in the tests.
> odb: refactor cpp tests

- src/rsz/src/SteinerTree.cc
- src/rsz/src/SteinerTree.hh
There are some unnecessary pin location lookups during Steiner tree construction in global placement. This change fetches these locations once and reuses them.
| `gpl` run | Mean [s] | Min [s] | Max [s] |
|:---|---:|---:|---:|
| `ariane133` (before) | 486.971 ± 0.833 | 485.887 | 487.765 |
| `ariane133` (after) | 447.517 ± 1.311 | 446.120 | 449.581 |
| `black_parrot` (before) | 562.767 ± 2.765 | 553.641 | 565.986 |
| `black_parrot` (after) | 525.773 ± 1.841 | 522.481 | 530.099 |
Global placement speedup is about 7-8%.
> Reduce number of pin location lookups in Steiner tree construction

- src/stt/src/pdr/src/pd.cpp
It's a hot function in global placement. Probably the biggest win here is capturing `pts` by reference instead of by copy, but also there's fewer allocations.
| `gpl` run | Mean [s] | Min [s] | Max [s] |
|:---|---:|---:|---:|
| `ariane133` (before) | 486.971 ± 0.833 | 485.887 | 487.765 |
| `ariane133` (after) | 447.314 ± 6.410 | 441.101 | 454.566 |
| `black_parrot` (before) | 562.767 ± 2.765 | 553.641 | 565.986 |
| `black_parrot` (after) | 537.563 ± 5.191 | 524.795 | 543.223 |
Global placement speedup is about 5-8%.
> Optimize `pdr::get_nearest_neighbors`

- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
The optimization include getter inlining and removal of `refer_lx_` and `refer_ly_` which were effectively unused but took part in checks in `SoftMacro::setX` and `SoftMacro::setY`.
The effect of the optimization was tested with `OpenROAD-flow-scripts` on `ariane133` design with `nandgate45` PDK. The stage `2_4_floorplan_macro` before the optimization took roughly **104** seconds whereas after the optimization about **83** seconds (on an Intel i7-8700 @ 3.20GHz CPU).
> Optimize macro floorplanning

- src/grt/src/fastroute/src/route.cpp
It makes assignments directly to destination vectors and removes unnecessary allocations.
> grt: Don't use temporary vectors

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
Refactoring to prepare for macro array support.
Originally, we had one function to both search and split the mixed leaves in the multilevel autoclustering stage.
This PR is to split this function into two: one to fetch the mixed leaves and other to actually split them into std cells and macro clusters.
If the approach is ok, I'll run Secure-CI
> mpl2: refactor mixed leaves splitting

- etc/DependencyInstaller.sh
Use latest version to avoid "Argument list is too long" error.
> etc: update eqy version

- src/gui/CMakeLists.txt
- src/gui/src/chartsWidget.cpp
- src/gui/src/chartsWidget.h
- src/gui/src/mainWindow.cpp
- src/gui/src/mainWindow.h
Resolves #4433 
With these changes, Charts will always be built within the GUI, but if QtCharts is not installed, a message will be displayed "QtCharts is not installed".
> gui: add charts event when qtcharts is not installed

- etc/deltaDebug.py
Don't continue doomed run if the error string couldn't be found.
```
$ openroad -python ~/OpenROAD-flow-scripts/tools/OpenROAD/etc/deltaDebug.py --persistence 3 --use_stdout --error_string "signal 11" --base_db_path bazel-bin/results/asap7/ChipTop/flat/3_2_place_iop.odb --step "echo hello"
OpenROAD v2.0-11865-g6471c0995 
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING ORD-0039] .openroad ignored with -python
Backing up original base file.
Performing a step with the original input file to calculate timeout.
No error found in the original input file.
Traceback (most recent call last):
File "/home/oyvind/OpenROAD-flow-scripts/tools/OpenROAD/etc/deltaDe …
```
> deltaDebug.py: abort immediately if we can't find the error

- src/odb/include/odb/dbStream.h
Working on some unit tests for Scan Chains in odb I found two bugs:
1. variantHelper was recursing on the wrong function (operator>> instead of variantHelper)
2. std::get<N> do not work in this case because std::variant default initialization is the first value so we get an exception trying to get any std::get<N> for N>0
> odb: fix std::variant bug

- src/gpl/CMakeLists.txt
The addition of the test in gpl caused builds to build when `ENABLE_TEST=OFF` this corrects this behavior.
@maliberty it might be nice to add a test to the Jenkinsfile to check this behavior. It doesn't actually have to build openroad, just run cmake, since the failure is in the cmake configuration. https://github.com/siliconcompiler/siliconcompiler/actions/runs/7508809382/job/20444951866
> gpl: fix inclusion of test only when tests enabled

- etc/deltaDebug.py
When runs are hours, then starting at a given level can be important.
> deltaDebug: add --start parameter

- include/ord/OpenRoad.hh
- src/Main.cc
- src/OpenRoad.cc
- src/OpenRoad.i
- src/rcx/src/MakeOpenRCX.cpp
No functional changes.
Changes:
- Moves OpenROAD version functionality to the OpenROAD object and removing the dependency on Version.hh everywhere except for the openroad object.
> ord: provide access functions to version information to avoid recompiling modules on commit changes

- etc/deltaDebug.py
- etc/test_delta_debug.sh
This is useful when there is an .odb file that needs very fine level cuts. These are lessons learned when trying to whittle down #4548.
Also added a basic test script. Takes a few minutes to run, worth hooking up to CI . Only needs to run if deltaDebug.py is changed.
To run smoke-test:
```
cd flow
../tools/OpenROAD/etc/test_delta_debug.sh
```
> deltaDebug: --multiplier increases number of cuts, --timeout can be specified explicitly

- src/gui/src/staGuiInterface.cpp
> gui: avoid displaying ideal clock odd values in report timing

- src/tap/include/tap/tapcell.h
- src/tap/src/tapcell.cpp
Similar to https://github.com/The-OpenROAD-Project/OpenROAD/pull/4551, but covering the cases where the tapcell overlaps with an endcap on the left side.
> tap: fix missing cells that overlaps with endcaps 

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/layoutViewer.cpp
- src/gui/src/options.h
- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
- src/gui/src/search.cpp
- src/gui/src/search.h
Adds:
- controls for via and segment shapes for routing and snet routing
Changes:
- bpins are drawn in layer order and are only visible with the net and layer controls
Replaces: https://github.com/The-OpenROAD-Project/OpenROAD/pull/4565
> gui: controls for shape types

- src/grt/src/AbstractRoutingCongestionDataSource.h
- src/grt/src/heatMap.cpp
- src/grt/src/heatMap.h
- src/gui/include/gui/heatMap.h
- src/gui/src/gui.cpp
- src/gui/src/heatMap.cpp
- src/gui/src/heatMapRUDY.cpp
- src/gui/src/heatMapRUDY.h
- src/gui/src/renderThread.cpp
- src/gui/src/stub_heatMap.cpp
- src/odb/include/odb/util.h
- src/odb/src/zutil/util.cpp
Changes:
- allow for heatmaps to have non-uniform grids
- add reset to RUDY calculation, otherwise each call just sums on the previous
- add db callbacks to RUDY heatmap to update when instances move
- add mutex to heatmap `ensureMap` to prevent RenderThread from calling it more than once at a time
Closes: #4618
> gui: allow for non-uniform grids in heatmaps and apply gcells to heatmaps

- src/grt/src/GlobalRouter.cpp
Avoiding generating congestion reports in Fastroute overflow iterations when incremental GRT is being executed.
> grt: avoiding generating congestion reports in the incremental GRT stage

- src/gui/src/layoutViewer.cpp
- src/gui/src/layoutViewer.h
- src/gui/src/renderThread.cpp
- src/gui/src/renderThread.h
Fix #4450 
Also making a small change to prevent interactions between the cursor and the layoutViewer while the design loading message is drawn.
> gui: draw ellipsis animation while rendering

- src/odb/src/codeGenerator/gen.py
Use case:
adding "flags" to the relations in schema.json so we can pass
"no-get" to prevent the generation of default get methods
> odb code gen: Allows us to control method creation for schema relations

- src/gpl/include/gpl/Replace.h
- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovBase.h
- src/gpl/src/replace.cpp
- src/gpl/src/replace.i
- src/gpl/test/gpl_aux.py
Uses OpenMP to parallelize Nesterov's method in global placement.
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| ibex / master / 1 thread | 32.251 ± 0.138 | 31.985 | 32.428 | 1.33 ± 0.01 |
| ibex / omp-nesterov / 1 thread | 32.621 ± 0.144 | 32.303 | 32.872 | 1.35 ± 0.01 |
| black_parrot / master / 1 thread | 505.898 ± 2.452 | 503.023 | 510.608 | 1.27 ± 0.01 |
| black_parrot / omp-nesterov / 1 thread | 500.197 ± 7.726 | 487.191 | 507.588 | 1.26 ± 0.02 |
| ariane133 / master / 1 thread | 434.566 ± 1.666 | 432.692 | 436.897 | 1.28 ± 0.01 |
| ariane133 / omp-nesterov / 1 thread | 431.179 ± 6.552 | 418.658 | 436.884 | 1.27 ± 0.02 |
| ibex / master / 8 threads | 25.579 ± 0.069 | 25.454 | 25.692 | 1.06 ± 0.00 |
| ibex / omp-nesterov / 8 threads | 24.172 ± …
> Parallel Nesterov's method

- .github/workflows/github-actions-lint-tcl.yml
- tclint.toml
This moves the paths to not be tclint-ed to the config file so its much easier to execute this test locally
> tcl: use tclint config to control paths to make it easier to run locally

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
This PR is to ensure we don't generate huge io blockages and end up deteriorating QoR when using the changes in #4206.
The quadratic power is to make the factor more aggressive as the problems below were not solved using the factor without it.
Secure-CI for #4206 showed, among some other metrics failures, problems for the following designs:
gf121/ariane: [ERROR GPL-0307] RePlAce divergence detected. Re-run with a smaller max_phi_cof value.
tsmc65lp/bp_be: [ERROR DPL-0036] Detailed placement failed.
Both of these designs had huge io blockages for pin access. Running the changes here combined with #4206 lead both designs to finish without metric failures.
I'm starting a Secure-CI only for this.
> mpl2: consider macro dominance when computing io blockages' depth

- src/dpl/include/dpl/Opendp.h
We have been seeing this error in some build environments:
```
src/dpl/include/dpl/Opendp.h:230:17: error: 'accumulate' is not a member of 'std'
```
This is fixed by this patch.
> Opendp: Fix missing include

- src/dpo/src/detailed_mis.cxx
It adds a few simple changes to `DetailedMis::gatherNeighbours` function, which results in ~4.7% speedup in `place_dp` stage (measured on `black_parrot`).
It changes `std::deque` to `std::queue` (because the deque was used as a queue), simplifies the conditions, evaluates `std::lround` only if it is needed and moves that condition to the end and skips the rest of conditions after the first that don't pass.
Results (from 8 runs):
|                | min time [min]   | avg time [min]   | med time [min]   | max time [min]   | sum time [min]   |
|:--------------------------|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|
| master         | 2:40             | 2:44             | 2:45             | 2:46             | 21:52            |
| my branch …
> dpo: optimize DetailedMis::gatherNeighbours

- src/CMakeLists.txt
The add_subdirectory statements for mpl2 and par are now conditional to the OS to avoid build and link errors on macOS.
> cmake: move add_subdirectory mpl2 and par

- src/CMakeLists.txt
As per https://github.com/The-OpenROAD-Project/OpenROAD/issues/4401#issuecomment-1980207992, "swig3 is ancient and we don't support it. Please use swig 4".
This updates the build files to reflect that statement.
> Update minimum SWIG version in `src/CMakeLists.txt`

- src/OpenRoad.tcl
- src/gui/src/gui.tcl
- src/ppl/src/IOPlacer.tcl
- src/stt/src/SteinerTreeBuilder.tcl
- src/stt/test/parse_clocks.tcl
Add helper function: `ord::parse_list_args` to help parse arguments with multiple allowed uses.
This will be useful for UPF support since it supports the same set of arguments provided and this function ensures a common methodology for handling these arguments.
Changes:
- changes the couple of examples in ORD (except for UPF) that is currently using this scheme, that I was able to find.
> ord: provide helper function to parse list arguments

- src/gui/src/layoutViewer.cpp
> gui: resize viewer based on its actual size rather than the padded rect dimensions

- src/dbSta/src/dbNetwork.cc
Since there are far more Iterms in a design, this avoids calling `.size()` when handling iterms speeding up `::id()`.
> dbsta: swap pin ordering to make iterms handling faster

- src/pdn/src/PdnGen.cc
- src/pdn/src/grid.cpp
- src/pdn/src/grid.h
- src/pdn/src/renderer.cpp
- src/pdn/src/shape.cpp
- src/pdn/src/shape.h
- src/pdn/src/sroute.cpp
Changes:
- initial loading of shape and obstruction rtrees to bulk loading
I'm sure there are more places that can benefit from this in PDN.
For ZeroSOC this takes off ~50% of the build time for the power grid.
> pdn: switch initial building of rtrees to vectors and use bulk loading

- src/gpl/test/CMakeLists.txt
- src/gpl/test/regression_tests.tcl
- src/gpl/test/simple02-rd.def
- src/gpl/test/simple02-rd.defok
- src/gpl/test/simple02-rd.ok
- src/gpl/test/simple02-rd.tcl
small modification on simple01-rd to include the target RC parameter. And included simple02-rd to test considering a lower target RC, which activates routability.
> gpl: add simple tests for routability mode in GPL

- src/drt/src/frRegionQuery.cpp
- src/drt/src/io/io_parser_helper.cpp
- src/drt/src/io/io_pin.cpp
- src/drt/src/pa/FlexPA_prep.cpp
computers are faster than they used to be, some of these updates spammed the log several times a second.
10x rarer still gives progress updates several times per minute plenty fast for detailed route.
This is helpful for larger designs, such as the one in this github issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/4821
> detailed route: reduce frequency of progress update

- src/gui/include/gui/heatMap.h
- src/gui/src/heatMap.cpp
- src/psm/src/heatMap.cpp
Issue:
* when converting to a `%`, the previous code was applying the scaling factor to the the percent value, which was be incorrect.
Changes:
* avoid applying scaling factor to percent and delay setting min and max with the scaling factor until after processing map
* provide access to logger (no functional change, but helpful when attempting to debug)
* use `lowest` vs. `min` for finding max values.
> correct realvalued heatmap handling

- src/odb/test/unitTestsPython/TestDestroy.py
- src/odb/test/unitTestsPython/helper.py
- src/odb/test/unitTestsPython/odbUnitTest.py
PEP8 red lines fixed while wandering through the code
> python: fewer red lines in editor by adhering to pep8 formatting

- src/drt/src/pa/FlexPA_prep.cpp
The middle of the pin needs to be used even though it intersects two routing tracks, as either track is too close to the blockages around the pin.
As a result, increase the threshold for checking the middle of the pin as an option from two to three routing tracks.
Let me know if you prefer a more specific solution.
> Fix pin acccess for 130BCD IO library

- docs/getMessages.py
@vvbandeira Fixes bug in OR messages glossary, where newlines parsed from files will mess up the markdown table.
https://openroad.readthedocs.io/en/latest/user/MessagesFinal.html
Before
After
> [Docs] Fix OR messages glossary

- src/mpl2/src/hier_rtlmp.cpp
A bug was introduced in #4839. I realized now when refactoring.
The bug was avoiding the generation of an io blockage for the left boundary.
> mpl2: fix bug introduced in io blockages computation fix

- src/odb/src/db/dbInst.cpp
- src/odb/test/cpp/TestCallBacks.cpp
Fix #4032
The callback cpp test was considering that, for a created inst whose block has not a valid bbox, calling setOrigin would only be effective in the first call. However, with the fix here, as long as the block has not a valid bbox, every setOrigin call should trigger callback events.
> odb: avoid skipping bbox computation for inst when block is not valid

- src/gpl/src/placerBase.cpp
as soon as the user sees this error message, they have to hunt down the value in the log, simply provide it in the error message instead.
```
Running global_place_skip_io.tcl
[INFO GPL-0002] DBU: 1000
[INFO GPL-0003] SiteSize: 54 270
[INFO GPL-0004] CoreAreaLxLy: 14418 14580
[INFO GPL-0005] CoreAreaUxUy: 129600 129600
[INFO GPL-0006] NumInstances: 104598
[INFO GPL-0007] NumPlaceInstances: 102890
[INFO GPL-0008] NumFixedInstances: 1708
[INFO GPL-0009] NumDummyInstances: 0
[INFO GPL-0010] NumNets: 118071
[INFO GPL-0011] NumPins: 378191
[INFO GPL-0012] DieAreaLxLy: 0 0
[INFO GPL-0013] DieAreaUxUy: 144000 144000
[INFO GPL-0014] CoreAreaLxLy: 14418 14580
[INFO GPL-0015] CoreAreaUxUy: 129600 129600
[INFO GPL-0016] CoreArea: 13248233640
[INFO GPL-0017] NonPlaceInstsArea: 49805280
[INFO GPL-0018] …
```
> placement: improve error message, no need to hunt down value in log

- src/gui/src/dbDescriptors.cpp
- src/gui/src/displayControls.cpp
With the addition of implant layers, this makes it a little easier to identify them in the GUI.
Plus, "Type" is a reserved property, so renaming the layer type to "Layer type" to avoid the overlapping names
> gui: add layer type to tool tip + fix overlapping property names

- src/gui/src/layoutViewer.cpp
- src/gui/src/renderThread.cpp
- src/gui/src/search.cpp
- src/gui/src/search.h
Changes:
- converts shapes.h and shapes.cpp to use the boost geom interface.
Notes:
- dbBox* could be further simplified to Rect, but it appears that accessing the dbBox requires several calculations to find the pointer, so I left that in (still reduces the total memory needed).
> gui: use boost geom for shapes

- src/gui/src/renderThread.cpp
This avoids spending time searching the special net rtrees on IMPLANT layers.
> gui: only draw routing shapes on routing layers

- src/mpl/src/MacroPlacer.cpp
Change warning to error to avoid mysterious downstream errors in pdn.tcl:
```
v2.0-13145-gfd769f92a
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ORD-0030] Using 1 thread(s).
[INFO MPL-0101] Found 4 macros.
[INFO MPL-0102] West pins 446.
[INFO MPL-0102] East pins 444.
[INFO MPL-0102] North pins 738.
[INFO MPL-0102] South pins 739.
[INFO MPL-0069] Initial weighted wire length 7.22153e+06.
Begin one level partition.
[INFO MPL-0076] Partition 4 macros.
[INFO MPL-0077] Using 4 cut lines.
[INFO MPL-0079] Cut line 129.60.
[INFO MPL-0079] Cut line 381.19.
[INFO MPL-0079] Cut line 665.01.
[INFO MPL-0079] Cut line 891.27.
End one level partition.
Begin …
```
> mpl2: fail with error instead of producing invalid .odb file

- docs/contrib/ReadmeFormat.md
- docs/src/scripts/md_roff_compat.py
- src/psm/README.md
@maliberty 
The problems in PSM readme
- Non-command headers in README should not be given a `###` - that is reserved for command parsing
- Missing description in function
- Wrong option/flag name, must match Tcl definition
> [Docs] fix failing CI due to psm

- etc/DependencyInstaller.sh
-fPIC is required so the static lib*.a we are building can also be used inside a DSO on Linux.
See also https://github.com/gabime/spdlog/issues/1405
> Build libspdlog.a with -fPIC by default

- src/grt/src/GlobalRouter.cpp
This update avoids resetting the db congestion when calling RUDY.
> grt: remove updateDbCongestion from applyAdjustments

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/heatMapRudy.cpp
- src/grt/src/heatMapRudy.h
To have the RUDY heatmap and GPL using the same Rudy object, make rudy inside GRT a class member so it's available for both the heatmap and GPL.
> grt: make rudy a class member

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/odb/include/odb/db.h
- src/odb/src/codeGenerator/schema/tech/dbTechLayer.json
- src/odb/src/db/dbDatabase.h
- src/odb/src/db/dbTechLayer.cpp
- src/odb/src/db/dbTechLayer.h
RUDY requires some way to load the user derating without overwriting the GRT information, now that it is shared. For that we opted to put the user layer adjustment in ODB, in dbTechLayer. The code generator was used to do so.
> odb: relocate user derating value from GRT to dbTechLayer

- src/cts/src/TritonCTS.cpp
After we write the clock nets to Db some subnets and sinks can be removed if they are not properly connected. However we don't remove the deleted sinks from the subnets, this can lead to crashes in the dummy load insertion and on writing clock NDR to Db.
This PR makes sure we remove the deleted sinks from the subnets.
> remove deleted sinks from subnets before dummy load insertion

- src/cts/test/array.ok
- src/cts/test/array_ins_delay.ok
- src/cts/test/array_no_blockages.ok
- src/rsz/src/RepairDesign.cc
- src/rsz/test/repair_wire2.ok
- src/rsz/test/resize_slack1.ok
- src/rsz/test/resize_slack3.ok
From the commit message:
> The `repairNetWire` function works on one wire segment at a time. To detect an overly long wire, we compare `wire_length > max_length_`, where `wire_length` is inclusive of previous segments.
> 
> When we request splitting, `split_length` is in terms of the current segment only, so add a missing offset that accounts for the length contributed from previous segments.
As far as I can tell there's an actual bug, but I wonder how come this hasn't been caught by some kind of DRC before.
> rsz: Fix split length calculation for long wires

- src/gui/src/staGui.cpp
- src/gui/src/staGui.h
there's no great way in C++ to get the maximum value/count for an enum, but at least it's no longer hardcoded if new columns are added.
The "End" column was hidden since there was a gaffe when adding End and not updating the hardcoded count of the enum everywhere:
> staGui: End column is now visible

- src/drt/src/io/io.cpp
Fixes [#5005](https://github.com/The-OpenROAD-Project/OpenROAD/issues/5005)
This PR avoids creating access points for db pins that aren't connected to any net. This is to prevent errors from happening to pins that are not connected to any net.
> DRT skip adding access points for db pins with no net

- src/CMakeLists.txt
- src/Main.cc
No function changes expected to the "Release" builds.
Adds:
- indicator to splash to indicate if the build is something other than Release.
Reasoning:
- in the past I've been trying to determine runtime issues and it's frequently because the build type is Debug and I forgot to switch it back to Release.
> ord: add build type to splash if other than release

- src/ant/src/AntennaChecker.tcl
- src/dbSta/src/dbSta.tcl
- src/dft/src/dft.tcl
- src/dpl/src/Opendp.tcl
- src/dpo/src/Optdp.tcl
- src/gpl/src/replace.tcl
- src/grt/src/GlobalRouter.tcl
- src/par/src/partitionmgr.tcl
- src/pdn/src/pdn.tcl
- src/tap/src/tapcell.tcl
- test/commands_without_load.tcl
Fixes [#4993 ](https://github.com/The-OpenROAD-Project/OpenROAD/issues/4993)
This PR adds a check on commands to prevent them from crashing if no design was loaded.
> fix crash for commands when no design were loaded

- src/gui/src/gui.cpp
Example use case: compare dimensions of two macros.
> Inspector: add width, height for convenience alongside BBox

- CMakeLists.txt
- src/dbSta/include/db_sta/dbSta.hh
- src/dbSta/src/CMakeLists.txt
- src/dbSta/src/MakeDbSta.cc
- src/dbSta/src/dbSta.cc
- src/rmp/src/CMakeLists.txt
- src/rmp/src/abc_library_factory.cpp
- src/rmp/src/abc_library_factory.h
- src/rmp/test/CMakeLists.txt
- src/rmp/test/cpp/CMakeLists.txt
- src/rmp/test/cpp/TestAbc.cc
- src/utl/include/utl/deleter.h
Creates a factory class to map an sta library into an abc one. This library can be used to unmap a netlist in ABC into an AIG for optimization, and then back into a mapped netlist
> rmp: Adds support to create an abc standard cell library from opensta

- src/grt/src/RepairAntennas.cpp
> grt: ignore nets connected by abutment in repair_antennas

- src/drt/include/triton_route/TritonRoute.h
- src/drt/src/TritonRoute.cpp
- src/odb/include/odb/db.h
- src/odb/src/db/dbSBox.cpp
- src/odb/test/regression_tests.tcl
- src/odb/test/smash_vias.defok
- src/odb/test/smash_vias.ok
- src/odb/test/smash_vias.tcl
Changes:
- repair via will now "smash" a block via array into individual vias and then remove all violating vias. This avoids the issue where a single via in a block via array causes drt to remove the entire via array disconnecting the power grid.
> drt: handle PDN repair for block vias

- CMakeLists.txt
I had to fork OpenROAD as there is an issue during linking of `stdc++fs`. It seems to be an old practice to put this line and is an issue when building with Flatpak. 
I made a similar request for Surelog that has been accepted (maybe it can be done for OpenROAD as well):
https://github.com/chipsalliance/Surelog/pull/3966
> Fix issue with linking dependency of -lstdc++fs when using flatpak

- src/grt/src/GlobalRouter.cpp
Previously, the user-defined max routing layer was overwritten by this process, causing issues during post-drt repair_antennas by using out-of-range layers.
> grt: split max layer and routing layers check

- src/odb/src/swig/python/dbtypes.i
As instructed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/4733#issuecomment-1982006670, this allows the following functions to be called (and the results thereof inspected) from Python:
* `dbMTerm::getDiffArea`
* `dbTechAntennaPinModel::getGateArea`
* `dbTechAntennaPinModel::getMaxAreaCAR`
* `dbTechAntennaPinModel::getMaxSideAreaCAR`
* `dbTechAntennaPinModel::getMaxCutCAR`
---
Supersedes #4733
> Added Python SWIG typemaps for returning vectors of float/layer pairs by reference

- src/odb/include/odb/db.h
- src/odb/src/db/dbBlock.cpp
Fixes overflow:
```
original HPWL         -964503.2 u
legalized HPWL       -2147483.6 u
```
->
```
original HPWL         3330464.1 u
legalized HPWL        3341133.7 u
```
> odb: provide dbuToMicrons for various datatypes to avoid casting errors

- src/mpl2/src/SimulatedAnnealingCore.cpp
- src/mpl2/src/SimulatedAnnealingCore.h
- src/mpl2/src/hier_rtlmp.cpp
Resolves the centralization problem showed in [#2020](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2020)
> gui: skip "macro alignment" of the current outline when SA centralized floorplan

- src/rmp/src/CMakeLists.txt
> Fix building `rmp_abc_library` when `USE_SYSTEM_ABC` is set

- Jenkinsfile
Adds test to ensure ENABLE_TESTS is implemented correctly in CMAKE.
> ord: add stage to confirm cmake can be run without building tests

- src/rsz/src/RecoverPower.cc
- src/rsz/src/RecoverPower.hh
In power recovery, vertices that have already been tried and rejected can be tried again if they happen to be on another path we look at. Usually, the result is the same – we reject the vertex. Not only is this work unnecessary, it also prevents us from trying another (possibly better) vertex later in the path. Some stats on vertices that are tried in #4982:
| Vertex | Total tries | Better | Worse |
| - | - | - | - |
| `max_length492/Y` | 1325 | 1 | 1324 |
| `load_slew487/Y` | 130 | 1 | 129 |
| `load_slew465/Y` | 309 | 1 | 308 |
| `load_slew447/Y` | 231 | 1 | 230 |
| `load_slew409/Y` | 49 | 0 | 49 |
| `load_slew400/Y` | 294 | 2 | 292 |
| `load_slew375/Y` | 262 | 1 | 261 |
| `load_slew57/Y` | 240 | 0 | 240 |
| `load_slew407/Y` | 124 | 0 | 124 |
| …
> Skip known bad vertices in power recovery

- src/grt/src/GlobalRouter.cpp
- src/grt/test/ndr_1w_3s.ok
- src/grt/test/ndr_2w_3s.ok
Currently GRT is computing the wrong  consumption for ndr nets. This PR fixes this error.
> Grt fix ndr track consumption

- etc/deltaDebug.py
- src/odb/include/odb/db.h
- src/odb/src/db/dbDatabase.cpp
This PR closes #2910. C++ and Python new functions have been added:
- `int dbDatabase::removeUnusedMasters()` - removes unused masters
- `def remove_unused_masters(self)` - to prepare database and call above C++ function
> Added a new function to remove unused dbMasters.

- src/gui/src/layoutViewer.cpp
@oharboe this should do what you wanted. Not a major change, just moved where that control is being used.
Replaces: https://github.com/The-OpenROAD-Project/OpenROAD/pull/5188
> gui: make module view control instance size limit

- src/gui/src/chartsWidget.cpp
- src/gui/src/chartsWidget.h
While working on improving performance I realized that there was a bug making us show the wrong slack data when using the filter feature. These changes are to ensure we actually show the correct data and reset the axis and limits to improve the presentation.
Changes:
- Use the API from the TimingPath rather than the sta API which gives always the worst slack
- Ensure that for tiny intervals of min/max slack, we use a reasonable slack interval for the x axis
- Clicking on empty bins won't trigger timing report (based on [Oyvind's Comment](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5139#issuecomment-2125400329))
> gui: slack histogram filter fix

- src/cts/test/array.ok
- src/cts/test/array_ins_delay.ok
- src/cts/test/array_no_blockages.ok
- src/rsz/src/RepairDesign.cc
- src/rsz/test/repair_wire2.ok
This reverts commit 4fe54e666f3bf7120b9c22edd2087e537fe19a29, reversing changes made to b16bda7e82721d10566ff7e2b68f1ff0be9f9e38.
Fixes failing secure-ci design.
> Revert "Merge pull request #5154 from arthurjolo/rsz_fix_longwire_split_lenght

- src/dbSta/include/db_sta/dbNetwork.hh
- src/dbSta/src/dbNetwork.cc
This pull request reworks the id mechanism used in dbNetwork.cc in hierarchy mode to avoid using the concrete network infra structure (which uses the sta object id) and instead use the database id. 
(Matt this step seems sufficiently complex and atomic to merit a pull request in its own right. I factored the code so that the database object id is used to determine the uniquified object id. The database id is shifted left by 4 and then a tag inserted into the lower 4 bits to determine the type of the object.)
> Reworked sta is to use uniquified ids in hierarchy mode. 

- src/cts/src/HTreeBuilder.cpp
- src/cts/test/insertion_delay.ok
During the HTree building step of cts we can create more Clock subNets then needed, these extra Clock subNets were deleted at the end of CTS, but this can cause crashes (like it was mentioned in https://github.com/The-OpenROAD-Project/OpenROAD/pull/4938).
To prevent having to delete these nets at the end of CTS, this PR avoids creating subnets that aren't connected to anything.
> cts avoid removing sinks

- src/gui/src/scriptWidget.cpp
To rethrow, use `throw;` idiom.
> scriptWidget: fix rethrowing exception

- src/mpl2/src/hier_rtlmp.cpp
Resolve [#1850](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1850)
This solves the crash, but mpl2 stage only completes with the changes in #5255.
My suspicions are that these checks were there, because mpl2 used to get the instances area in micron from their LibertyCell. This was fixed in #5036.
> mpl2: avoid checking nullptr LibertyCell

- src/mpl2/src/object.cpp
This is an idea to make it possible for mpl2 to find a valid tiling for the root in cases such as sky130hd/chameleon. For this design, multilevel autoclustering engine generates a cluster with three very big macros that have no connection signature at all. This cluster will be further fine shaped to what we see in the image below .
The existence of this cluster ends up preventing SA from fitting all clusters in the outline later on.
> mpl2: avoid groupping macros with empty conn signature

- src/grt/src/GlobalRouter.cpp
I was reading the source code and noticed that the condition `if (tech_layer->getRoutingLevel() != 0)` on line 3650 was always evaluating to true, because the `tech_layer` is already a routing layer.
Hence, the variable `valid_layers` is the same as the variable `layer`, that is being iterated in the for loop.
In this PR, the variable `valid_layers` is removed and replaced by `layer` and the if statement `if (tech_layer->getRoutingLevel() != 0)` is removed.
> GRT: Updated GlobalRouter::computeMaxRoutingLayer

- src/ppl/include/ppl/IOPlacer.h
- src/ppl/src/IOPlacer-py.i
- src/ppl/src/IOPlacer.i
We are observing non-determinism in the output of the `place_pins` step across multiple runs of OpenROAD with fixed initial conditions. The root cause seems to be iteration over a set of `odb::dbBTerm*`.
With this change, we observe deterministic pin placement. Using `dbBTerm.getId()` for the comparison was considered but we suggest using `getObjNames()` to avoid being affected by upstream allocation order.
> Enforce iteration order determinism for ppl::PinSet.

- src/dft/README.md
- src/dft/include/dft/Dft.hh
- src/dft/src/Dft.cpp
- src/dft/src/architect/CMakeLists.txt
- src/dft/src/architect/Opt.cpp
- src/dft/src/architect/Opt.hh
- src/dft/src/architect/ScanArchitect.cpp
- src/dft/src/architect/ScanArchitect.hh
- src/dft/src/architect/ScanArchitectHeuristic.cpp
- src/dft/src/architect/ScanArchitectHeuristic.hh
- src/dft/src/cells/OneBitScanCell.cpp
- src/dft/src/cells/ScanCell.hh
- src/dft/src/dft.i
- src/dft/src/dft.tcl
- src/dft/test/CMakeLists.txt
- src/dft/test/cpp/ScanCellMock.cpp
- src/dft/test/cpp/ScanCellMock.hh
- src/dft/test/cpp/TestScanArchitectHeuristic.cpp
- src/dft/test/one_cell_nangate45.tcl
- src/dft/test/one_cell_sky130.ok
- src/dft/test/one_cell_sky130.tcl
- src/dft/test/place_sort_sky130.ok
- src/dft/test/place_sort_sky130.tcl
- src/dft/test/place_sort_sky130.v
- src/dft/test/place_sort_sky130.vok
- src/dft/test/scan_architect_clock_mix_sky130.tcl
- src/dft/test/scan_architect_clock_mix_sky130.vok
- src/dft/test/scan_architect_no_mix_sky130.tcl
- src/dft/test/scan_architect_no_mix_sky130.vok
- src/dft/test/sub_modules_sky130.tcl
This isn't quite complete as I haven't updated tests yet, but I'd appreciate feedback on the direction here before I do that.
This PR makes two changes to the DFT code:
- `insert_dft` is now only performing scan cell replacement, a new command `connect_dft` is used to perform scan architect and stitch. This is because replacement needs to be done before placement (as it affects cell areas) but stitching needs to be done after placement (where it can use placement information to minimise scan wirelength)
- A basic wirelength minimising sort is used on the scan chain before stitching. This is a simple greedy nearest neighbour approach using Boost rtrees - I also briefly explored using the or-tools TSP solver a bit but all the modes I tried were considerably too slow (and the only way to …
> Initial placement-aware scan stitching

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
Resolve #4539
Include macros in PAR partitioning when breaking flat clusters. The original code was only splitting the std cells between the generated partitions leading to something like the image below for flat megaBoom.
With the changes here:
> mpl2: include macros in large flat cluster partitioning

- src/dbSta/src/dbReadVerilog.cc
- src/dbSta/test/CMakeLists.txt
- src/dbSta/test/dont_touch_attr.ok
- src/dbSta/test/dont_touch_attr.tcl
- src/dbSta/test/dont_touch_attr.v
This enables a cell to be marked as "don't touch" (for example, a buffer you want kept), directly inside the HDL using the attribute (as per the included test) without needing any custom Tcl scripting.
> dbSta: Honor dont_touch attribute in Verilog

- src/odb/include/odb/db.h
I found these comments confusing at first, and then realized there was a minor typo/lack of newline.
> [docs] odb: minor layout/typo fix for db.h code comments

- src/gui/src/gui.cpp
Fixes exit code issue caused by: https://github.com/The-OpenROAD-Project/OpenROAD/pull/5258
> gui: dont eval error code if Qt says an exit was requested

- src/dft/test/place_sort_sky130.tcl
- src/dft/test/regression_tests.tcl
I didn't sport that `dft/test/helpers.tcl` was a symlink, so forgot to add my change to it adding the `place_inst` function for the test, so the test fails on master. As this probably isn't a very useful placement function outside of this specific test, I have decided to add it to the test this time round rather than modifying the global `helpers.tcl`.
Does something else also need to be fixed so that issues in Tcl tests get caught in CI?
> dft: Fix the place_sort_sky130 test

- src/dft/README.md
- src/dft/src/architect/ScanArchitect.cpp
- src/dft/src/architect/ScanArchitect.hh
- src/dft/src/config/ScanArchitectConfig.cpp
- src/dft/src/config/ScanArchitectConfig.hh
- src/dft/src/dft.i
- src/dft/src/dft.tcl
- src/dft/test/CMakeLists.txt
- src/dft/test/cpp/TestScanArchitect.cpp
- src/dft/test/max_chain_count_sky130.ok
- src/dft/test/max_chain_count_sky130.tcl
- src/dft/test/max_chain_count_sky130.v
- src/dft/test/max_chain_count_sky130.vok
- src/dft/test/regression_tests.tcl
This will be useful in applications where we are building to connect to a scan controller or external scan pins, with a fixed expected maximum number of chains (quite possibly one).
> dft: Add support for specifying a max number of chains

- src/gpl/README.md
- src/gpl/src/nesterovPlace.cpp
- src/gpl/src/timingBase.cpp
- src/gpl/test/convergence01.ok
- src/gpl/test/simple01-td-tune.ok
- src/gpl/test/simple01-td.ok
Include more clear messages during timing driven mode so the user can better understand what is happening. 
Include possible actions for user to improve runtime due to slow timing driven mode.
Include new tcl command in README for using grt(previous) routing congestion estimator during routability.
Fix default inflation parameters in README.
> gpl: modify log and readme for timing driven mode clarity

- .github/workflows/github-actions-lint-tcl.yml
- src/OpenRoad.tcl
- src/gpl/src/replace.tcl
- src/mpl2/src/mpl.tcl
- src/pdn/src/pdn.tcl
- src/rsz/src/Resizer.tcl
- src/tap/src/tapcell.tcl
- tclint.toml
This PR updates `tclint` to v0.3.2. Since CI was a bit behind the latest version, there are a few new categories of violations that require fixes. I've gone ahead and fixed all the newline escape spacing violations in this PR (there weren't that many), but I ignored [`spaces-in-braces`](https://github.com/nmoroze/tclint/blob/main/docs/violations.md#spaces-in-braces) and [`unbraced-expr`](https://github.com/nmoroze/tclint/blob/main/docs/violations.md#unbraced-expr), since there were too many instances of these violations to hit in one go. 
This latest version also includes a bug fix for the issue in `mpl.tcl`. With that fix + updating the indentation pattern to fix the other violations, the comment annotations to disable checks can be removed. 
It might be worth looking into setting up …
> ci: update tclint to v0.3.2

- src/Main.cc
getenv(HOME) can actually return null. Other places in OpenROAD, such as OpenSTA, this is checked.
Typical use-cases are highly controlled build environments, like bazel hermetic builds.
> init: HOME can be unset

- src/grt/src/heatMapRudy.cpp
Fixes: if grt throws an exception `populateXYGrid` this leaves `rudy_` a nullptr, but because the exception is caught execution continues.
> grt: check if rudy is nullptr to avoid segfault if an error occurs in grt setup

- src/pdn/src/straps.cpp
- src/pdn/src/straps.h
- src/pdn/src/techlayer.cpp
Fixes:
- when core area is the same as die area straps would appear on the edges going outside the die area, this avoids generating straps if they will exceed the die area.
> pdn: dont place straps outside of die area

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
Fix #5285 
I'm also adding a check to allow "exceptions" - nets with std cells without liberty will be skipped when creating data flow. I.e., we'll consider data flow as empty only when there's absolutely no Liberty data for std cells.
> mpl2: continue without dataflow when no liberty data is found for std cells

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/layoutViewer.cpp
Changes:
- moves implant layers into a sub category of layers (in case of a lot of implant layers this allows the routing and cut layers to be a little easier to find.)
- adds masterslice and other groups to enable non-implant layers too, there are very few shapes in this so should not add much to the render time.
- masterslice and other are not enabled by default
Before):
New default view:
Expanded:
> gui: add enablement for painting all layers

- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
- src/gui/src/mainWindow.cpp
Adds:
- list of layers an iterm can be found on. For most it will only be one, but on memory macros and IO pads it can be be several
> gui: add layers to ITerm descriptor

- src/gui/src/dbDescriptors.cpp
@maliberty only the IO type was exposed in the descriptor, so that's the only one removed.
> gui: remove io type from iterm descriptor as it is now in mterm

- src/grt/src/GlobalRouter.cpp
Adding error message when no routing layer has a track structure.
Fixes #5364
> grt: adding error message when no routing layer has a track structure

- src/drt/src/pa/FlexPA_graphics.cpp
- src/drt/src/pa/FlexPA_graphics.h
For more readability. Odb layer num and tech one are not the same.
> drt: Display layer name instead of num in DRT-0119 message.

- src/mpl2/src/clusterEngine.cpp
While running mock-array with the latest ORFS / OR and using mpl2 I realized that both halos were being set as the horizontal halo (width).
> mpl2: fix hardmacro halos

- etc/shell.nix
Tested to create a functional openroad executable, though on nixOS it doesn't work with `-gui` as-is. I assume it didn't before either, though
> nix: fix and update shell.nix to 24.05

- src/dft/test/scandef_core_sky130.tcl
No functional changes, just changing a DFT test to use `make_result_file` to avoid generating an untracked file in the test directory
> dft: correct test to avoid generating stray file

- src/gui/src/staGui.cpp
If there was a f1/help button for all menus, then
some of this tooltip would be moved in there.
Meanwhile, best that can be done is a slightly verbose tooltip.
Doesn't look too bad. Tolerable...
> timing report: add a more elaborate tooltip

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
Change memory management from manual to automated for the following objects:
- Metrics (Owned by a map within the tree)
- HardMacros (Owned by a map within the tree - this can be further improved so that the clustering engine doesn't deal with objects from the other mpl2 stages).
- SoftMacros (Owned by their cluster)
SoftMacros were neither being correctly allocated nor destroyed.
Also removing some useless variables.
> mpl2: fix SoftMacro leaks and beginning of automated memory management 

- src/gui/src/scriptWidget.cpp
- src/gui/src/scriptWidget.h
> gui: use a buffer to store report text to avoid slowing down OR when logging in Scripting

- src/gui/src/scriptWidget.cpp
- src/odb/include/odb/db.h
- src/odb/src/codeGenerator/gen.py
- src/odb/src/codeGenerator/helper.py
- src/odb/src/codeGenerator/schema/chip/dbPolygon.json
- src/odb/src/codeGenerator/schema/tech/dbTechLayerMaxSpacingRule.json
- src/odb/src/codeGenerator/templates/db.h
- src/odb/src/codeGenerator/templates/impl.cpp
- src/odb/src/db/dbLevelShifter.cpp
- src/odb/src/db/dbMetalWidthViaMap.cpp
- src/odb/src/db/dbPolygon.cpp
- src/odb/src/db/dbTechLayerEolKeepOutRule.cpp
- src/odb/src/db/dbTechLayerKeepOutZoneRule.cpp
- src/odb/src/db/dbTechLayerMaxSpacingRule.cpp
Added:
- `const std::string& arg` to code generator in ODB since that seemed to be a common warning from the SWIG generated code.
- defaults to the two classes identified.
> odb/gui: coverity fixes

- src/odb/include/odb/geom.h
- src/pad/src/RDLRouter.cpp
- src/psm/src/ir_network.cpp
- src/psm/src/ir_solver.cpp
- src/psm/src/node.cpp
- src/psm/src/shape.cpp
I found myself typing this several times in the last couple of days so I thought a helper function would be useful.
Adds:
- helper function to get the `.center()` point of a `Rect`
Changes:
- where possible in psm/pad use `.center()`
Notes:
- more would be possible, but in many places we pass around the `x,y` coordinates and not a `Point` so there would be more places possible in the future if that changes.
> odb: add .center() function to Rect

- src/gui/src/scriptWidget.cpp
I noticed that the order of the printouts in the gui were wrong. This corrects it by ensuring that the buffer is flushed before processing more text. There should not be any performance slowdown from this.
vs .
> gui: ensure flush is called on the buffer before logging output to preserve printing order

- src/gui/src/scriptWidget.cpp
Why:
- I noticed the GUI would periodically lock up on me when the GUI was active and reports were printing.
- When checking in GDB it was this lock that kept coming up as waiting to lock, but not able to.
Change:
- changes this to a `try_to_lock` (non blocking), if it fails to aquire the lock it will just restart a timer to call this later and return without flushing the buffer. This might cause the GUI to print things out of order compared to the cmdline, but avoids the lock up because the flush was unable to get the mutex.
I'm open to suggestions on how to better resolve this issue, but this "lazy"-lock approach was the simplest I could think of.
> gui: use try_lock for flushing buffer

- src/pad/src/RDLRouter.cpp
@maliberty this got missed in the previous pr.
Changes:
- ensure the obstruction box for 45 degree edges covers the correct edges.
> pad: adjust points to accounts to "width" different

- src/pad/src/RDLRouter.cpp
Fixes:
- segfault when the GUI is in use with the router and the router is called again.
> pad: fix debug segfault when GUI is in use

- src/cts/src/HTreeBuilder.cpp
Fixes [#5537](https://github.com/The-OpenROAD-Project/OpenROAD/issues/5537)
This is a improvement to the PR [#5222 ](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5222). The previous PR was not taking into account that CTS may also create a extra non leaf buffer that would not be driving anything. So in this PR we extend the previous one to prevent creating dangling non leaf buffer.
> CTS improve prevention to deleting buffers.

- etc/DependencyInstaller.sh
This PR updates `DependencyInstaller.sh` to support installation on Ubuntu 24.04
> Add support for Ubuntu 24.04

- src/gui/src/layoutViewer.cpp
- src/gui/src/layoutViewer.h
- src/gui/src/renderThread.cpp
- src/gui/src/search.cpp
- src/gui/src/search.h
Changes:
- use polygons for intersection searching to better control `selectAt` to avoid selecting the entire bounding box but actually select the Octagon or polygon correctly.
- use CellBoxes to search MTerms since we have already done this for rendering.
> gui: use odb::Polygon instead of boost polygon and implement select by polygons

- src/dbSta/include/db_sta/dbNetwork.hh
- src/dbSta/src/dbNetwork.cc
- src/dbSta/test/hier2_out.vok
- src/dbSta/test/hierclock_out.vok
- src/rsz/test/regression_tests.tcl
- src/rsz/test/resize1_hier.ok
- src/rsz/test/resize1_hier.tcl
- src/rsz/test/resize1_hier.v
- src/rsz/test/resize1_hier.vok
Clean up of verilog writer to use non-concrete network net iterator. Added hierarchical tests for resizer. Instance creation in Network Edit.
> Minor fixes to verilog writer/instance creation (network Edit Function)

- src/gui/src/gui.cpp
The type names are mangled.
```
$ echo "PN3gui12DRCViolationE" | c++filt -t
gui::DRCViolation*
$ echo "Dn" | c++filt -t
decltype(nullptr)
```
The type name "decltype(nullptr)" is more straightforwards than "Dn".
> gui: Demangle type name when printing an warning.

- src/gui/src/drcWidget.cpp
The var should no be inited otherwise has_value() will always be true. That way the condition of the if will decide if the var has been set or not.
Fixes warning:
[WARNING GUI-0033] No descriptor is registered for Dn.
and now
[WARNING GUI-0033] No descriptor is registered for type
decltype(nullptr).
Caused by frFakeVSS and frFakeGND:
[WARNING GUI-0044] Unable to find net (line: 104375): frFakeVSS
[WARNING GUI-0044] Unable to find net (line: 104378): frFakeVDD
> gui: Do not init std::any item var if we intend to use has_value() on it.

- src/odb/src/lef/lef/lefrData.cpp
When compiled with ubsan, the previous formulation resulted in `runtime error: index -1 out of bounds for type 'char[16384]'`. Changed to avoid without changing behavior.
> Avoid ubsan runtime failure

- default.nix
- flake.nix
This PR's purpose was changed after discussion with maintainers. Original text follows:
---
Per @gadfort's suggestion
> nix: add missing 'gtest' dependency

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/RepairAntennas.cpp
- src/grt/src/fastroute/include/FastRoute.h
- src/grt/src/fastroute/src/FastRoute.cpp
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5565.
> drt/grt: fix drt crash caused by temporary wires from repair_antennas

- docs/index.md
The * is a vestige from when macOS didn't support `par` and `mpl2`
> Remove * from macOS support in index.md

- test/flow.tcl
I noticed a few random crashes in some PRs that are unrelated to their changes. The stack trace is similar to what we saw on ORFS, caused by using MT in sta. This PR disables sta mt to avoid these random crashes.
> test: disable sta mt

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
- src/mpl2/src/object.cpp
- src/mpl2/src/object.h
This PR addresses one of the problems showed in #5655, that is: the clustering engine leaves the physical hierarchy with empty clusters created from empty modules:
Subsequent work is needed in order to address other things.
_I also made some renaming, because it was a bit confusing._
> mpl2: avoid creating clusters for empty modules

- src/grt/src/GlobalRouter.cpp
Partial fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/5668.
When running repair_antennas post-DRT, it is necessary to reset FastRouteCore values to ensure the correct resource values are at the edges of the routing grid. By resetting it, the resources used by the routed nets are freed, and it will consider only the resource reductions from the routing wires of the nets.
This helps to largely reduce the runtime of repair_antennas post-DRT and keep the final routing DRC clean.
> grt: reset FastRouteCore when repairing antennas from detailed routing

- src/cts/src/TritonCTS.cpp
As I was studying the code to see how to avoid using clock buffers during post-placement optimization I realized that the Lib iterators are not being freed after used in CTS.
> cts: delete leaked iterators

- src/odb/src/defin/definReader.cpp
I'm marking this PR as draft as generally in the build, duplicate message numbers generate an error.
In this case, there are 2 errors with number 250 and  I don't get any an error. Something is wrong with the build.
Can someone take a look at it?
if (_mode != defin::DEFAULT) {
if (chip == nullptr) {
_logger->error(utl::ODB, **250**, "Chip does not exist");
}
} else if (chip != nullptr) {
_logger->error(utl::ODB, **250**, "Chip already exists");
} else {
chip = dbChip::create(_db);
}
> odb: Convert old error message to logger.

- src/cts/include/cts/TritonCTS.h
- src/cts/src/TritonCTS.cpp
Make the cells with clkbuf/CLKBUF in their name to be correctly found when inferring buffers without needing to do manual string filtering after the search.
This fix is necessary for #5577 so that RSZ can choose correctly which buffers not to use for resizing.
_I tested this with aes for all public and private PDKs and the pattern match doesn't fail._
Example with some printing for debug in sky130hs/aes:
Without the fix
```
Infer Buffer List
Looking for buffers with is_clock_cell attr:
No buffers found.
Looking for buffers with name CLKBUF or clkbuf:
No buffers found.
Looking for buffers with name BUF or buf:
No buffers found.
Looking for all buffers:
sky130_fd_sc_hs__buf_1
sky130_fd_sc_hs__buf_16
sky130_fd_sc_hs__buf_2
sky130_fd_sc_hs__buf_4
sky130_fd_sc_hs__buf_8 …
```
> cts: fix pattern match regexp and remove manual string filtering

- src/odb/test/cpp/CMakeLists.txt
Updated gtest registration in odbtest cmakefile, so that linker can find gtest, gmock and gtest_main libraries.
> Updated gtest registration to fix odbtest linking issue

- etc/DependencyInstaller.sh
The user can uninstall to have it reinstalled. The thinking is that reinstalling on a docker can cause more problems than it solves, so better to do nothing until the user explicitly uninstalls.
Also, this allows the user to choose podman-docker, if that is his preference.
> DependencyInstaller: if docker is present, do not reinstall

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/SteinerTree.cc
RSZ skips nets with more pins than 200000. This PR removes this limit.
> RSZ: remove max_steiner_pin_count_ limit on pins per net handled by rsz

- src/odb/CMakeLists.txt
- src/odb/src/db/CMakeLists.txt
The messages checking was set at db level as odb is an interface and doesn't not have a post-build trigger.
Unfortunately there were no dependencies on other libs besides db such as defin.
So since add_dependencies can only add targets but not files, create a custom target which depends on a generated files which
triggers the call to find_messages.py.
> odb: Move messages checking to odb to fix deps.

- .dockerignore
- .gitignore
- docker/Dockerfile.builder
- etc/Build.sh
- etc/DependencyInstaller.sh
- etc/DockerHelper.sh
- src/gpl/CMakeLists.txt
This PR adds `-save-deps-prefixes=FILE` argument to `DependencyInstaller.sh`, which dumps additional CMake parameters in form of `-D <PackageName>_ROOT=<path>`.
Those parameters can be used for OpenROAD built, to make sure the correct dependencies' versions are used.
Moreover, `GTest::` was added to Google Test target link, fixing build errors (on Ubuntu 24.04):
```
/usr/bin/ld: cannot find -lgtest: No such file or directory
/usr/bin/ld: cannot find -lgmock: No such file or directory
/usr/bin/ld: cannot find -lgtest_main: No such file or directory
```
> Add option to generate CMake parameters pointing to installed dependencies

- etc/DependencyInstaller.sh
This PR adds `-constant-build-dir` flag that sets `baseDir` for dependency building to a fixed directory instead of `mktemp`-based directory.
Dependencies like Yosys and abc use `__FILE__` macro, which is different on every build.
Such changes can lead to cache invalidation in e.g. https://github.com/The-OpenROAD-Project/bazel-orfs/
> DependencyInstaller: Add option for constant build path

- src/pdn/src/via.cpp
Spotted this while debugging some other arrayspacing related via issues, seems like it only affects the debug prints but avoids confusion with incorrect units in the prints.
> pdn/via: Fix debug print units

- src/pdn/test/sky130_power_switch/power_switch.lef
This ensures the lef matches the row pattern and power grid pattern.
> pdn: fix lef for powerswitch to align with site

- src/drt/src/pa/FlexPA.cpp
- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_graphics.cpp
- src/drt/src/pa/FlexPA_graphics.h
- src/drt/src/pa/FlexPA_init.cpp
- src/drt/src/pa/FlexPA_prep.cpp
- src/drt/src/pa/FlexPA_unique.cpp
- src/drt/src/pa/FlexPA_unique.h
This PR contains only name changes to the PA module. There is no change to functionality or logic at all, this PR can be considered aesthetic. (Large diffs with no variable highlights are just git getting lost due to too many changes in a block)
There are too many variable changes to list. Here are the most common changes:
- Variables now adhere to snake_case
- In some variables `ap` is now fully written as `access_point`
- Some variables had `V` to mean vertical, now the abbreviation used is `vert`
- In tome maps and such the formatting `key2Value` is now `key_to_value`
Here are all other variable names changes that do not fit the above patterns:
- `bp` → `begin_point`
- `ep` → `end_point`
- `sol` → `no_drv` (this variable clearly checks if there are no Design Rule Violations)
- …
> drt: PA name changes

- src/dft/src/cells/ScanCellFactory.cpp
- src/dft/src/replace/ScanReplace.cpp
Fixes two null pointer dereferencing crashes:
* One where no valid lib files have not been read prior to DFT function invocation
* One where a cell might be missing entirely from the lib files in a PDK (such as `sky130_fd_sc_hd__tapvpwrvgnd_1` in sky130)
Warnings are printed in both situations.
---
@maliberty i just incremented the numbers for the new messages- not sure if that's okay or not
> dft: fix lib-related crashes

- src/drt/src/pa/FlexPA_prep.cpp
This PR has some minor changes to `prepPoint_pin_checkPoint_planar` and `prepPoint_pin_checkPoint_viaDir_helper`.
There are essentially three changes:
Throughout both functions an at least on if statement has to check whether the given dir is in the preferred direction of the layer. This check is verbose and makes it difficult to follow the part of the code where those checks exists. `wrong_dir` was created to facilitate legibility.
Multiple getters for this variables though the code make it more bloated. Accessing them once and using them further make the code smaller.
Both `no_drv` changes are very simple. In both cases the variable is checked, if `true` something happens using `true` as an argument (either setting the variable itself or `ap->setAccess()`), if `false` the same happens …
> drt: explicit_wrong_dir, no_drv and pin_term/pin_net

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_init.cpp
- src/drt/src/pa/FlexPA_prep.cpp
- src/drt/src/pa/FlexPA_unique.cpp
- src/drt/src/pa/FlexPA_unique.h
This PR contain minor changes to some functions in PA. Functions changed take a reference to a container and fill said container. This PR changes it so instead it returns it.
This makes the functions role easier to understand, as its more obvious that its role is to return that structure and that it is an output, not an input.
This should not affect performance as due to **move semantics** instead of copying the returned structure its ownership is transferred to the caller.
Some functions have name changes:
- `prepPoint_pin_mergePinShapes` → `mergePinShapes` (Conform to PR [#5770](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5770))
- `initMaster2PinLayerRange` → `initMasterToPinLayerRange`
Also `LayerRange` was changed to a pair instead of a tuple, as its always a tuple of 2 …
> drt: functions changed to have more explicit output

- src/drt/src/pa/FlexPA_prep.cpp
This PR simply adds the use of `frDirEnumPlanar` when appropriate.
It also simplifies
```
if (allow_via) {
ap->setAccess(frDirEnum::U, true);
} else {
ap->setAccess(frDirEnum::U, false);
}
```
to
```
ap->setAccess(frDirEnum::U, allow_via);
```
> drt: cardinal directions and allow via simplification

- src/pad/src/pad.tcl
Avoid passing list of lists to `sta::parse_port_net_args`.
Without this it seems to be triggering a bug in the opensta tcl at https://github.com/The-OpenROAD-Project/OpenSTA/blob/20925bb00965c1199c45aca0318c2baeb4042c5a/tcl/CmdArgs.tcl#L81
I'm not able to reliably replicate it to make a testcase: `9 can't read "libcells": no such variable`
> pad: avoid passing list of lists to sta::parse_port_net_args

- src/grt/src/GlobalRouter.cpp
- src/grt/src/Net.cpp
- src/grt/src/Net.h
Fix crash in remove_buffers2 unit test, related to the merging of nets that were connected by a removed buffer.
> grt: destroy pins from disconnected terms

- src/drt/src/pa/FlexPA_prep.cpp
This PR patches a Coverity scan defect. `inst_term->getInst()` could be called even if `inst_term` was a `nullprt`. Now it can't.
> drt: check for inst_term nullptr

- src/ppl/src/IOPlacer.cpp
- src/ppl/test/large_groups3.ok
Improve error message for non-obvious problem.
I have a macro that is routed by abutment and temporarily during development I need to have a LOT of pins which can't fit on a single metal layer. I therefore increase the number of metal layers via IO_LAYER_H, but it still failed because I had a `set_io_pin_constraint -group -order` constraint which forced all pins to be put on a single metal layer.
It was not obvious to me that a group can't span metal layers... I'm hoping that mentioning "metal layer" here will key the user onto the problem.
Knowing this, I was able to work around some global routing congestion errors by removing a constraint:
```
foreach {direction direction2 names} $assignments {
set mirrored [zip {*}$names]
set_io_pin_constraint -region $direction2:* -pin_names [lindex …
```
> ppl: a group is on a single metal layer

- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
- src/mpl2/src/mpl.tcl
Resolve #5655 
Increase outline weight and reduce boundary to ease SA job for cases with very few bundled nets during **_cluster placement_**. Without this, the lack of connections + boundary pushing may end up preventing macros to fit in a tight outline.
_Note: The initial idea here was to tune the outline weight to a higher value. Running CI for this resulted in GPL not converging in a private design and a failure in sky130hd/uw due to high congestion caused by a bad macro placement._
> mpl2: add mechanism to ease outline/boundary weights based on the amount of nets

- src/gui/src/scriptWidget.cpp
Changes:
- add single shot to pauser timer in GUI, this prevents it from continuing run and trigger when pausing is not needed
- avoids formatting the idle/pause label when timer is not running, but update is still called.
> gui: fix pauser to stop repeated triggering

- src/drt/src/db/obj/frAccess.h
- src/drt/src/frBaseTypes.h
- src/drt/src/pa/FlexPA_prep.cpp
Adds arrays for `frDirEnumVia`, `frDirEnumHorz` and `frDirEnumVert` in the same format as `frDirEnumPlanar` and `frDirEnumAll`.
Adds support for setting multiple accesses with a single call: `setMultipleAccesses`.
Implements the new function in `gen_createAccessPoint`
Also refactored:
```
if (allow_planar) {
...
for (const frDirEnum dir : frDirEnumPlanar) {
ap->setAccess(dir, true);
}
...
} else {
for (const frDirEnum dir : frDirEnumPlanar) {
ap->setAccess(dir, false);
}
}
```
to:
```
ap->setMultipleAccesses(frDirEnumPlanar, allow_planar);
```
> drt: suport por setting multiple accesses in a single call

- src/drt/src/pa/FlexPA_prep.cpp
Like #5803, Eliminates code duplication in `genAPEnclosedBoundary`.
Creates the auxilary variables `coord_top` and `coord_top`.
The old function essentially added  `gtl::yh(rect) - box.yMax()` and `gtl::yl(rect) - box.yMin()` to coords if the layer was horizontal, if not it added  `gtl::xh(rect) - box.xMax()` and `gtl::xl(rect) - box.xMin()`. It used 4 if statements, now it uses one with an auxiliary loop.
> drt: genApEnclosedBoundary code duplication elimination

- src/drt/src/pa/FlexPA_prep.cpp
genAPsFromRect has a lot of code duplication. 
When generating access points for a given rectangle shape there are two relevant layer, a layer 1 and layer 2. Currently, the code verifies if layer 1 was horizontal. If true it made a bunch of calls to generate access points. In some cases Y/vertical coordinates were used and other X/horizontal coordinates were used. If false it made the exact functions calls with the same patterns, except Y/vertical and X/horizontal were switched. This happened twice.
Auxiliary variables `layer1_rect_min`, `layer1_rect_max`, `layer2_rect_min`, `layer2_rect_max`, `layer1_coords` and `layer2_coords` were created. The logic to check if layer 1 is horizontal is done in them through ternary operations and they are used in posterior calls, so code does not have …
> drt: genAPsFromRect code duplication elimination

- src/grt/src/fastroute/include/FastRoute.h
- src/grt/src/fastroute/src/FastRoute.cpp
- src/grt/src/fastroute/src/RipUp.cpp
- src/grt/src/fastroute/src/maze.cpp
- src/grt/src/fastroute/src/utility.cpp
Removes the following unused functions:
- applyVerticalAdjustments
- applyHorizontalAdjustments
- fixEmbeddedTrees
- bendEdge
- ripupSegZ
Adds a better description to unused but useful during development functions:
- checkRoute2DTree
- verify2DEdgesUsage
- verify3DEdgesUsage (renamed from verifyEdgeUsage for clarity)
> grt: FastRoute unused functions

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_prep.cpp
[Context] I'm starting to take a look at the Access Pattern generation in the PA module, as until now I only looked at the Access Point generation. I just started, but this code duplication case stood out like a sore thumb. I don't like naming functions "helper" but I intend to change the names of Access Patterns generation functions later so I created a temporary name.
Eliminates code duplication in `genPatterns`. Creates an auxiliary function `genPatterns_helper` to execute the duplicated code so the helper is called twice instead of repeating the code.
Git diff is making it hard to see that the code was in fact duplicated. If its hard to see I recommend looking at `genPatterns` in master to see that there is a clear repetition just changing `pins` to `reversed_pins`.
Also adds spaces …
> drt: genPattern code duplication elimination

- src/gui/include/gui/gui.h
- src/gui/src/dbDescriptors.cpp
- src/gui/src/inspector.cpp
- src/gui/src/mainWindow.cpp
- src/gui/src/staDescriptors.cpp
- src/gui/src/staDescriptors.h
Adds:
- sta::Corner descriptor
- sta::Instance descriptor
- adds fields to the properties in allow access to more information
- add highlighting where possible
- sta::Instance can be slow to load the first time since it needs to get power information, but I think it's worth having access to that, especially when debugging things like clock gating power @QuantamHD (the added loading time is also why I think it makes sense to keep it separate the DB descriptor).
Discussion:
- I don't like the names I've chosen for `STA Instance` and `DB ???`, so I'm open to suggestions for what to rename those to make it better
> gui: add to sta descriptors

- src/gpl/src/mbff.cpp
IsClockPin() returned true for various pins in the synthetic ASAP7 MBFFs due to sta::Pin* -- removed for now.
> gpl: mbff clock pin issue fix

- etc/DependencyInstaller.sh
It is a left over from 4fef3cb9796cc33188e466d758b4667402b8d946 which moved definition few lines above.
> etc: Remove redundant definition.

- src/Main.cc
The "-threads" is option always specified in ORFS, which results in log spam.
Only print out number of threads when the splash screen is enabled
Manual test/demo...
Before:
```
$ make do-2_4_floorplan_macro
Running macro_place.tcl, stage 2_4_floorplan_macro
[INFO ORD-0030] Using 48 thread(s).
No macros found: Skipping macro_placement
Elapsed time: 0:00.30[h:]min:sec. CPU time: user 0.24 sys 0.06 (100%). Peak memory: 119424KB.
$ openroad -threads 12345 -no_splash
[INFO ORD-0030] Using 48 thread(s).
openroad> 
$ openroad -threads 12345
OpenROAD v2.0-16246-gc20457a6c 
Features included (+) or not (-): +Charts +GPU +GUI +Python
Components of this program may be licensed under more restrictive licenses which …
```
> output: reduce log spam

- src/drt/src/pa/FlexPA_prep.cpp
As I was reading the Access Pattern of the PA module I noticed some variables still needed name changes. Here they are:
- `numNode` → `num_node`
- `numEdge` → `num_edge`
- `vioEdge` → `vio_edge`
- `apIdx` → `ap_idx`
- `via_2` → `via2`
- `via_1` → `via1`
- `leftAP` → `left_access_point` (In Access Pattern it is important to differentiate Access Point from Access Patterns as both abbreviate to AP)
- `rightAP` → `right_access_point`
- `leftPt` → `left_pt`
- `rightPt` → `right_pt`
- `tmpPt` → `tmp_pt`
> drt: PA access pattern variable name changes

- src/drt/src/frBaseTypes.h
- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_prep.cpp
This secure CI associated with this PR passed with no changes.
In Multiple parts of the code the Master of an instance was deferenced to get its type and determine the type of the instance. In multiple parts of the code the same check was done either to verify if the instance was a Standard Cell or a Macro Cell. Two respective functions were created to make this check given an instance.
`isStdCell()` checks for as the `isCore()` instead of directly looking for various typing. This caused no changes in the secure CI Run
> drt: pin type check

- src/dft/src/dft.tcl
there was an error generated when running report_dft_config
[ERROR GUI-0070] can't read "args": no such variable
> dft: fix reporting config problem

- src/mpl2/src/SimulatedAnnealingCore.cpp
- src/mpl2/src/SimulatedAnnealingCore.h
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
Resolves #5884
This PR is the proper fix for #5655, that's the reason why it also reverts #5799.
Changes:
1. Keep the lowest cost valid result as SA goes so that, if the lowest cost result is not valid we use the former.
2. Minor cleanup
> mpl2: improve convergence

- src/ppl/src/IOPlacer.cpp
- src/ppl/src/SimulatedAnnealing.cpp
- src/ppl/src/SimulatedAnnealing.h
- src/ppl/src/Slots.h
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5847
> ppl: fix infinite loop in annealing

- src/pdn/src/straps.cpp
https://github.com/The-OpenROAD-Project/OpenROAD/pull/5927 broke repair channels on gf180
This ensures that the connecting strap directions are used if they can be found.
See https://github.com/siliconcompiler/siliconcompiler/actions/runs/11308313835/job/31451523568?pr=2885 for failing grid
> pdn: fix gf180 power grid and correct incorrect use of direction

- src/gui/src/staGuiInterface.cpp
Resolve #5882
It seems like the manual check we were doing was wrong. There's an option to include the PathGroup(s) name(s) on the search so we can get only the paths that belong to that group.
> gui: include pathgroup name information when searching for pathends

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_prep.cpp
A secure CI associated with this branch passed.
The latter part of `genAPsFromRect` is a bit verbose for what it is doing. In essence, it goes through 4 access point costs (`OnGrid`, `Center`, `EncOpt` and `NearbyGrid`), checks if the layer cost limit allows for these costs and creates them with their respective functions. This takes a lot of lines and is verbose for a simple ideia. 
To encapsulate this simple ideia the function `genAPCosted` was created. It takes a cost and the necessary arguments to create any kind of access point and creates the according access point. I very much like the fact that the association between cost and function is made very clear, although it makes the use of some arguments (like `offset`) a little harder to understand.
More importantly, the use of the …
> drt: genApCosted

- src/rmp/src/logic_cut.cpp
- src/rmp/src/logic_cut.h
- src/rmp/src/logic_extractor.cpp
- src/rmp/src/logic_extractor.h
- src/rmp/test/cpp/TestAbc.cc
- src/rmp/test/side_outputs_extract_logic_depth.v
Before this change logic cuts were sta::Pin* terminated this lead to weird effects where ABC would see two pins with the same driving net, and do weird things to its internal datastructure.
It also has the nice property that a logic cut based on nets can be reused multiple times if a user wants to run two versions of a script on a Abc_Ntk*.
> rmp: Moves Logic Cut to net based primary IO

- src/Main.cc
- src/gui/include/gui/gui.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/mainWindow.cpp
- src/gui/src/mainWindow.h
- src/gui/src/stub.cpp
This provides a way to pass in the `no_init` information to the GUI on load to start the GUI in a clean state.
If we dont want to bring in the commandline flag, I suggest we still have this capability since it would be useful when debugging GUI issues and dealing with sometimes corrupted settings files.
> gui: if no_init is specified on commandline previous settings will not be loaded

- src/ppl/test/group_pins7.py
- src/ppl/test/place_pin2.py
- src/ppl/test/ppl_aux.py
- src/ppl/test/random4.py
Python 3.12 generates a SynthesisWarning for strings containing unescaped `\[` or `\]`. This causes the test suite to fail, and indirectly blocks building .deb packages for Ubuntu 24.04 (which comes with Python 3.12 as the default).
> ppl: escape backslashes in python tests

- src/cts/src/TritonCTS.cpp
Fixes [#5953](https://github.com/The-OpenROAD-Project/OpenROAD/issues/5953)
Dummy load currently doesn't considers the max fanout limit and insert buffer to nets where the driver is already on the limit, causing max fanout violations.
This PR prevent inserting dummy loads in such case and prevents the violations.
> Dummy load insertion respect max fanout

- etc/find_messages.py
Adds:
- file and line number information to the find_messages script to make it easier to track down errors.
Sample output on STDERR:
```
Error: ODB 0256 used 2 times, next free message id is 273
Appears in dbMarker.cpp on line 494 
Appears in dbMarker.cpp on line 509 
```
> add files and line numbers to find_messages to make it easier to track down there the duplicate is

- src/Main.cc
TL;DR This fixes the last niggling little deployment problem with non-Ubuntu systems and bazel-orfs GUI.
Not pretty, but good 'nuf to use around the house.
> tcl: add a fallback from hardcoded TCLRL_LIBRARY path

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_prep.cpp
Creates `initInstAccessPoints`, a separate function for initializing the access point of a single instance. 
Might be pertinent to #5867
> drt: init instance access points

- src/mpl2/src/hier_rtlmp.cpp
- src/odb/src/zutil/util.cpp
Fix #5983 
Also: use new block methods when writing mpl string.
> mpl2: don't move macro if all layers are already snapped

- src/gui/src/displayControls.cpp
Made some darker colors brighter and easier to see. A side-by-side review of all the colors needs to be done, I don't know exactly where to find them in the GUI though.
Before:
After:
> colors: tweak default colors to work better on black background

- src/ppl/include/ppl/IOPlacer.h
- src/ppl/src/IOPlacer.cpp
Fix overlaps between FIXED pins placed with the `place_pin` command and the remaining pins placed with `place_pins` command.
> ppl: check if slot location is used by a fixed bterm

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
- src/utl/include/utl/scope.h
Generic functionality that will be useful for the match footprint/user_function_class task in #5577.
> utl: add mechanism to make it easier to handle operation-specific settings

- src/pdn/README.md
- src/pdn/src/pdn.tcl
- src/pdn/test/core_grid_offset_strap.tcl
Currently it is ignored when -followpin is set. Better issue an error and point to the correct way.
> pdn: Issue an error when -starts_with is used with -followpin in add_pdn_strip.

- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
- src/gui/src/mainWindow.cpp
No functional changes expected.
The last time I was adding a ODB descriptor I noticed that I was just copying and pasting the makeSelected, lessThan, and forgot to add the ODB properties to the getProperties.
So this is an attempt to create a base class that can do these things and remove that duplicated code.
> gui: use base descriptor class to remove duplicated code for lessThan, makeSelected, and populateODBProps

- src/gui/src/gui.cpp
- src/gui/src/inspector.cpp
Fixes #5999
Changes:
- make qDebug messages go to `debugPrint` to allow for easier QT debugging.
> gui: fix selection in inspector when using navigation

- .github/workflows/github-actions-docs-test.yml
@maliberty this should help avoid merging code that doesn't pass the docs testing
> add docs testing to PRs so errors are caught before push to main

- src/drt/src/io/io.cpp
- src/drt/src/io/io.h
This update allow incremental DRT to route nets that are created by post-DRT repair_timing.
> drt: add net when it does not exist in drt yet

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/RecoverPower.cc
- src/rsz/src/RecoverPower.hh
- src/rsz/src/RepairHold.cc
- src/rsz/src/RepairHold.hh
- src/rsz/src/RepairSetup.cc
- src/rsz/src/RepairSetup.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
This PR checks if `repair_timing` did something in the design. This is specially useful in the post-DRT timing repair project to avoid calling DRT when repair_timing didn't executed or didn't changed anything in the design.
> rsz: return if repair_timing did something in the design

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/BufferedNet.cc
- src/rsz/src/EstimateWireParasitics.cc
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
This first step only adds `detailed_routing` as a new source of parasitics, and is used mainly to avoid calculating the parasitics from wire load models.
In the first iteration on each net, the droute parasitics are used, but once the net is changed, later iterations will use the global routing parasitics for estimation. At some point we should be able to detail route again specific nets inside the repair_timing flow.
Last, I'm checking if the design is routed to define the parasitics source as detailed_routing. It doesn't seem the ideal way, but I didn't find any functions in STA to detect there are parasitics present in its internal structures. Another option would be have a command that the user explicitly calls to define detailed_routing as the parasitics source.
I'm open to …
> rsz: add detailed_routing as parasitics source

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
Resolve one of the tasks in #5577.
I changed the function that checks the footprints to a bool, because it looked a bit overkill. It feels more concise as well.
> rsz: check electrical compatibility when available

- src/drt/src/pa/FlexPA_prep.cpp
Regression from 58b46bbc5ac5a206af201b991e0fcd5c8e7f0ade.
Info message was never shown as pin count was always odd when performing the modulo.
Also simplify code even more.
> drt: Fix pin double count and not appearing info.

- include/ord/OpenRoad.hh
- include/ord/Tech.h
- src/Main.cc
- src/Tech.cc
- src/gui/src/tclCmdInputWidget.cpp
Replaces #6071 
This should resolve all GUI entrypoints. I decided to wait on the documenting the tests since I don't have time right now but wanted this fix in.
> app startup for GUI

- src/drt/src/pa/FlexPA_prep.cpp
Code needs a increment of 1 to work properly so linearize batch size into a loop in ditributed code.
> drt: Simplify code and fix distributed group messages.

- src/mpl2/src/SACoreHardMacro.cpp
- src/mpl2/src/SACoreHardMacro.h
- src/mpl2/src/SACoreSoftMacro.cpp
- src/mpl2/src/SACoreSoftMacro.h
- src/mpl2/src/SimulatedAnnealingCore.cpp
- src/mpl2/src/SimulatedAnnealingCore.h
Resolves #5996,
Resolves #6031,
Resolves #6055.
When I implemented #5908 I missed one fundamental thing: the cluster placement result (and all the other SoftMacro annealing results) is not just the sequence pair itself but rather a combination of the sequence pair along with the specific shapes chosen during a perturbation iteration. _I.e., the same sequence pair can represent different floorplan arrangements depending on the clusters' shapes._
As this only applies for SoftMacro annealing, even though the logic for storing the best valid result happens inside the base class SimulatedAnnealingCore, we can only actually use that result in the derived SACoreSoftMacro, because we need SoftMacro APIs to set the shapes that we cached. Because of that, I thought it was time to also remove the …
> mpl2: ensure that sa converges if a valid result was generated at any point

- src/Metrics.tcl
No functional changes, just adding a few metrics that are calculated, but not reported.
> ord: add missing metrics to report_design_area

- src/dbSta/src/dbReadVerilog.cc
Fix for:
** CID 1564875:  Performance inefficiencies  (COPY_INSTEAD_OF_MOVE)
/src/dbSta/src/dbReadVerilog.cc: 448 in ord::Verilog2db::makeDbModule(sta::Instance *, odb::dbModule *, std::vector<std::pair<const sta::Instance *, odb::dbModInst *>, std::allocator<std::pair<const sta::Instance *, odb::dbModInst *>>> &)()
> Fix coverity std::move

- src/mpl2/src/SACoreSoftMacro.cpp
- src/mpl2/src/SACoreSoftMacro.h
- src/mpl2/src/SimulatedAnnealingCore.cpp
- src/mpl2/src/SimulatedAnnealingCore.h
Make the Result live inside the Core so that we can use the same struct for both types of Macro.
For each type there's a different type of result now:
Soft -> Sequence Pair + Shapes
Hard -> Sequence Pair (I'm not including the orientation, because the flip perturbations in SA are now deprecated and should be removed. See #6102 )
> mpl2: use best valid result for both Hard/Soft

- src/tap/README.md
Also align place_endcaps -prefix option default value description.
> tap/doc: tapcell_ripup options are optional.

- src/gui/src/renderThread.cpp
Closes #6114
Changes:
- color can brush type was changing the draw IO pins which masked the tracks. This ensures that pen and brush is setup correctly for tracks.
- similar bug for fills was also fixed.
> gui: ensure color and brush is set correctly on layer drawing

- src/odb/src/swig/common/odb.i
Before:
```
>>> _906ffb309d5d0000_p_odb__dbMaster getArea 
_00a1d12f9d5d0000_p_int64_t
```
After:
```
>>> _f0af0448c7590000_p_odb__dbMaster getArea
4256000
```
> odb: add int64_t to swig to ensure getArea works in TCL

- src/gui/src/displayControls.cpp
I noticed this when debugging https://github.com/The-OpenROAD-Project/OpenROAD/pull/6121.
Before the layers checkbox would be partially filled in (even though all visible boxes are checked):
After the layers checkbox is behaving correctly:
> gui: dont check hidden children states when toggling parent checkbox

- src/README.md
- src/dbSta/include/db_sta/dbSta.hh
- src/dbSta/src/dbSta.cc
- src/dbSta/src/dbSta.i
- src/dbSta/src/dbSta.tcl
- src/dbSta/test/regression_tests.tcl
- src/dbSta/test/report_cell_usage_modinsts.ok
- src/dbSta/test/report_cell_usage_modinsts.tcl
Changes:
- adds optional module inst argument to `report_cell_usage` to report the usage of cells in submodules. Default stays the top module.
> dbsta: add modinst optional argument to report_cell_usage

- src/utl/src/ScopedTemporaryFile.cpp
Remove "basic_ios::clear: iostream error" error and ":iostream error" suffix that does not say much so the message is more user friendly.
> utl: Simplify error mesage in stream handler.

- src/CMakeLists.txt
Fixes the cmake warning printed at the start of cmake config
```
-- spdlog: 1.8.1
CMake Warning (dev) at src/sta/CMakeLists.txt:32 (option):
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
For compatibility with older versions of CMake, option is clearing the
normal variable 'USE_TCL_READLINE'.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- STA version: 2.6.0
```
Now:
```
-- spdlog: 1.8.1
-- STA version: 2.6.0
```
> sta: set cmake policy 77 to NEW to forward the tcl readline setting

- src/ifp/src/InitFloorplan.cc
Closes #6113.
Changes:
- Improved error messages. Units converted to micrometer (μm).
- Duplicate error IDs removed.
> Improved IFP error messages

- README.md
Removes `\n` from README, seems to be a new mermaid compiler
> [Docs] Fix mermaid diagram README

- src/rmp/src/logic_cut.cpp
- src/rmp/src/logic_cut.h
- src/rmp/src/unique_name.h
- src/rmp/test/cpp/TestAbc.cc
This PR adds a new function called LogicCut::InsertMappedAbcNetwork, this function takes an Abc_Ntk_t* and reinserts it into the STA netlist.
This function also removes the old logic cut and replaces it with new instances derived from the Abc network.
Only thing left to do is optimize the abc network in some positive way.
😎
> rmp: Adds backedge from ABC to OR

- src/rmp/src/abc_library_factory.cpp
- src/rmp/src/abc_library_factory.h
- src/rmp/src/logic_cut.cpp
- src/rmp/src/logic_cut.h
- src/rmp/test/cpp/TestAbc.cc
- src/rsz/test/cpp/TestBufferRemoval.cc
- src/utl/include/utl/deleter.h
`deleted_unique_ptr` implies that the contents are already deleted or something which is both confusing and incorrect. `UniquePtrWithDeleter` more accurately captures the intent of a unique_ptr with a custom Deleter.
> Rename deleted_unique_ptr to UniquePtrWithDeleter

- flake.nix
The current `flake.nix` `openroad` attribute can't be imported into other flakes for consumption nor used to install `openroad`. This is due to a limitation in `nix` that doesn't fetch submodules (with the exception of self with '.?submodules=1'). Due to this limitation, peoples using `nix` wanting to install `openroad` have to
1. clone the OpenROAD repository with git
2. use `nix` to build or install `openroad` from the git clone using a special undocumented flag.
Step 2. copies the git source code in the nix store ending up with two copies of a large repo on disk.
To remedy this we propose to add a second attribute `openroad-release` using `fetchFromGitHub` which is capable to retrieve submodules and pointing to a git commit (tag) known to work. (I tried to compile HEAD with the `nix` …
> flake.nix: add openroad-release attrubute

- Jenkinsfile
This timeout can be triggered when the Jenkins queue is large, which is not intended.
> ci: remove global timeout

- CMakeLists.txt
- src/CMakeLists.txt
- src/utl/src/Utl.tcl
Changes:
- installs the pages for `man` in the `OPENROAD_SHARE` share directory to avoid interfering with other installs
> utl/man: ensure man pages get installed in openroad share directory to avoid clobbering other installs

- src/utl/src/Utl.tcl
Changes:
- when gui is enabled the pager does not work since it is requesting inputs from an unused stdin. The gui already have scrollbars on the log so this feature doesnt add much.
- on the last page where is no reason to ask for a user input to continue.
> utl: fix pager behavior

- src/odb/include/odb/db.h
- src/odb/src/db/dbITerm.cpp
- src/odb/src/swig/python/dbtypes.i
- src/odb/src/swig/tcl/dbtypes.i
Currently only the rect is returned but that's not very useful. So instead we return pairs of layer + rect.
The appropriate SWIG mapping is also added so the result is usable both in Python and in TCL.
Note that someone should definitely have a close look at the SWIG mapping because I have very little experience with those.
I did test that it seems to work as expected in both TCL and Python though.
> odb: In dbITerm::getGeometries, return layer + rect

- src/odb/src/cdl/cdl.cpp
- src/odb/test/data/gcd/gcd.def
ATM the code seem to assume that for each top level pin, the net name is equal to the pin name.
That's not always the case and this produces an incorect netlist.
To solve that, during pin name enumeration when creating the subckt line, we create a mapping from "net name" -> "pin name" for each pin connected to a net of a different name. Then when outputting the connections between sub blocks, we use the pin name instead of the DB net name.
> odb/cdl: Handle top-level pins wired to nets of different name

- CMakeLists.txt
- include/ord/OpenRoad.hh
- src/OpenRoad.cc
- src/OpenRoad.i
- src/gui/CMakeLists.txt
- src/gui/README.md
- src/gui/include/gui/gui.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/helpWidget.cpp
- src/gui/src/helpWidget.h
- src/gui/src/mainWindow.cpp
- src/gui/src/mainWindow.h
- src/utl/src/Utl.tcl
Adds:
- `HelpBrowser` widget to allow for interactive / offline viewing of help if it's available.
Changes:
- Adds two functions to OpenROAD to allow for a centralized location to determine the location of the docs
- `man` switched to use new path access.
Notes:
- ~Due to the exclusion of `std::filesystem` I had to do path and directory handling manually, this can be simplified if `std::filesystem` is allowed.~
- `man` could be configured to open the gui help if we want.
- The HTML help is not particularly pretty and I don't find it helpful to know the compile date or header, but these issues can be handled separately.
- The script widget could be modified to allow for hyperlinks to this widget got commands and error messages (that would be best handled in a separate PR).
- there are lots …
> gui: help browser

- src/mpl2/include/mpl2/rtl_mp.h
- src/mpl2/src/Mpl2Observer.h
- src/mpl2/src/graphics.cpp
- src/mpl2/src/graphics.h
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
- src/mpl2/src/mpl.i
- src/mpl2/src/mpl.tcl
- src/mpl2/src/rtl_mp.cpp
So we can know where a specific cluster is being placed.
> mpl2: add option to show cluster id instead of sequence pair id

- CMakeLists.txt
- src/ant/test/CMakeLists.txt
- src/cts/test/CMakeLists.txt
- src/dbSta/test/CMakeLists.txt
- src/dft/test/CMakeLists.txt
- src/dpl/test/CMakeLists.txt
- src/dpo/test/CMakeLists.txt
- src/drt/test/CMakeLists.txt
- src/fin/test/CMakeLists.txt
- src/gpl/test/CMakeLists.txt
- src/grt/test/CMakeLists.txt
- src/gui/test/CMakeLists.txt
- src/ifp/test/CMakeLists.txt
- src/mpl/test/CMakeLists.txt
- src/mpl2/test/CMakeLists.txt
- src/odb/test/CMakeLists.txt
- src/pad/test/CMakeLists.txt
- src/par/test/CMakeLists.txt
- src/pdn/test/CMakeLists.txt
- src/ppl/test/CMakeLists.txt
- src/psm/test/CMakeLists.txt
- src/rcx/test/CMakeLists.txt
- src/rmp/test/CMakeLists.txt
- src/rsz/test/CMakeLists.txt
- src/stt/test/CMakeLists.txt
- src/tap/test/CMakeLists.txt
- src/upf/test/CMakeLists.txt
- src/utl/test/CMakeLists.txt
- test/CMakeLists.txt
Ensures all tests that appear in regression_tests.tcl are present in CMakeLists.txt for the tool test dir.
No functional changes.
Notes:
- Adds the base openroad tests as well, which were missing. I had to disable timing_api_4 as it was generating a failure on my machine.
- Only includes tests from record_tests list
Additionally: any new tests getting added after this PR must appear in both files until a followon PR removes the dependency on `./regression` in the tool directories
> ctest test merged with regression_tests.tcl

- src/odb/include/odb/db.h
- src/odb/src/db/dbBlock.cpp
- src/odb/src/db/dbBlock.h
- src/odb/src/db/dbModule.cpp
Removes the static variable name_id_map from the dbModule::makeUniqueDbModule method (issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/5981)
Variable name_id_map moved to dbBlock, as suggested by @maliberty in https://github.com/The-OpenROAD-Project/OpenROAD/pull/6245#issuecomment-2501902499, and is now accessed via the dbBlock::getModuleNameIdMap() method.
> odb: moving dbModule::makeUniqueDbModule()::name_id_map to dbBlock 

- src/stt/include/stt/SteinerTreeBuilder.h
- src/stt/include/stt/flute.h
- src/stt/src/SteinerTreeBuilder.cpp
- src/stt/src/flt/flute.cpp
The errors below were fixed by removing the write_svg function and initializing numsoln as nullptr.
** CID 1566420:    (INTEGER_OVERFLOW)
/src/stt/src/flt/flute.cpp: 2021 in stt::flt::Flute::write_svg(stt::Tree, const char *)()
** CID 1566417:  Uninitialized members  (UNINIT_CTOR)
/src/stt/include/stt/flute.h: 198 in stt::flt::Flute::Flute()()
> stt: fixing errors detected with Coverity Scan

- src/grt/src/GlobalRouter.cpp
- src/grt/test/repair_antennas_error1.ok
grt::have_routes should be silent in .tcl, AntennaChecker.cc has another warning of its own and EstimateireParasitics.cc uses placement if global routing is not available and it doesn't look like it should output a warning
fixes #6293
> grt: make haveRoutes() a silent check

- src/odb/include/odb/db.h
- src/odb/src/db/dbGlobalConnect.cpp
- src/odb/src/db/dbNet.cpp
I noticed that the global connects hold on to the old information after a net is destroyed (usually causing a segfault).
This fixes that by ensuring that the global connects are checked during dbNet destroy.
> ord: ensure global connects are updated when nets are destroyed

- src/rsz/README.md
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
- src/rsz/test/CMakeLists.txt
- src/rsz/test/regression_tests.tcl
- src/rsz/test/report_dont_touch.ok
- src/rsz/test/report_dont_touch.tcl
- src/rsz/test/report_dont_use.ok
- src/rsz/test/report_dont_use.tcl
Adds:
- `report_dont_use` and `report_dont_touch` to provide feedback about the instance, cells, and nets that have been marked by resizer.
> rsz: add report_dont_* commands

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/graphics.cpp
- src/mpl2/src/hier_rtlmp.cpp
Run cluster placement for children of std cell clusters to allow correct generation of temporary std cell placement (and consequently allow orientation improvement) for cases in which the cluster tree has maximum level > 1.
The idea here is based on megaBoom and the big module that I'm referring to is lsu.
In the original implementation, when doing multilevel autoclustering, at the point in which we haven't yet split the macros from std cells in the leaves of the tree (meaning all the leaves are mixed) and iterating the children of a certain parent to do so, if we found a cluster without macros, we would simply classify it at as std cell cluster and move on to the next child, not caring about a possible further stdcell cluster only level i.e., a std cell parent whose children are all std …
> mpl2: do cluster placement for stdcell-only levels

- src/gpl/src/graphics.cpp
- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovBase.h
These modifications does not change any functionality.
- Add debug prints for overflow calculation values.
- Show microns instead of dbu for bins in debug mode on gui.
> gpl: debug options for overflow

- src/drt/src/db/drObj/drVia.cpp
- src/drt/src/db/drObj/drVia.h
- src/drt/src/db/obj/frVia.h
- src/drt/src/db/taObj/taVia.h
- src/drt/src/dr/FlexDR_maze.cpp
- src/drt/src/dr/FlexDR_rq.cpp
- src/drt/src/frRegionQuery.cpp
- src/drt/src/gc/FlexGC_init.cpp
- src/drt/src/gr/FlexGR_rq.cpp
- src/drt/src/io/io.cpp
- src/drt/src/io/io_parser_helper.cpp
- src/drt/src/ta/FlexTA_assign.cpp
- src/drt/test/fixture.cpp
This PR is auxiliary to #6326, regarding issue #5712.
The aforementioned PR is failing a regression test, I'm hunting the reason for this failing. This is probability due to setting some Transform "by hand" instead of taking it from another object, as is a problem on the whole drt codebase that is being fixed. I organized some of the Transform on drt to help find this bug and figured this was getting big enough to be a separate PR since it is just minor refactoring. Mainly, This PR avoids the direct creation of `dbTransform` on drt and opts to get from already set objects when available.
> drt: Transform slight refactoring

- jenkins/Jenkinsfile.coverage
Increased timeout to 3h to see if the Dynamic Code Coverage stage completes successfully.
> bumped up coverage timeout to 3h

- CMakeLists.txt
- include/ord/OpenRoad.hh
- src/Main.cc
- src/OpenRoad.cc
- src/OpenRoad.i
Now that charts is not optional for compile it doesn't need to be in the options list
> ord: remove charts from options as this is not optional anymore

- src/gui/src/heatMap.cpp
Fixes:
- on my ubuntu24 with wayland QT driver is generating warnings about the heatmap cursor:
```
[WARNING GUI-0076] QObject::killTimer: Timers cannot be stopped from another thread
[WARNING GUI-0076] QObject::startTimer: Timers cannot be started from another thread
[WARNING GUI-0076] QObject::killTimer: Timers cannot be stopped from another thread
[WARNING GUI-0076] QObject::startTimer: Timers cannot be started from another thread
[WARNING GUI-0076] QObject::killTimer: Timers cannot be stopped from another thread
[WARNING GUI-0076] QObject::startTimer: Timers cannot be started from another thread
[WARNING GUI-0076] QObject::killTimer: Timers cannot be stopped from another thread
[WARNING GUI-0076] QObject::startTimer: Timers cannot be started from another thread
[WARNING GUI-0076] …
```
> gui: check for QThreads before updating cursors

- src/dft/src/architect/CMakeLists.txt
- src/dft/src/architect/ScanArchitect.cpp
- src/dft/src/clock_domain/CMakeLists.txt
- src/dft/src/clock_domain/ClockDomain.hh
- src/dft/src/clock_domain/ClockDomainHash.cpp
- src/dft/src/clock_domain/ClockDomainHash.hh
Now we don't force dependencies on scan architect when using ClockDomain.
This will help us on the implementation of scan opt as we don't need to know about clock domains when performing scan optimizations based on scandefs.
> dft: refactor clock domain

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
To avoid the infinite recursion in #6083. This doesn't solve the problem there. I'll open a subsequent PR with the proper fix.
> mpl2: throw error when PAR gives MPL2 a completely unbalanced solution

- src/gui/src/tclCmdInputWidget.h
The Tcl_Size define is used in tclSwig.h, but at least with swig version 4.2.1 and tcl 8.6.15, this results in this symbol being undefined and subsequently in a compile error. Work around by including the header providing it (which is happening _before_ tclSwig.h is included).
> With swig 4.2.1, Tcl_Size is needed; provide necessary define.

- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_maze.cpp
This PR is ISPD and Secure CI safe. Tackles #5610.
While debugging #6326 I had to take a look at `routeNet_postAstarPatchMinAreaVio` where I noticed a weirdly verbose chunk of boolean logic that was also duplicated. I made a helper function with the condensed logic to eliminate duplication.
> drt: slight routeNet_postAstarPatchMinAreaVio refactor

- src/mpl/src/ParquetFP/src/parsers.h
The std::ifstream is used, but necessary header was missing. Also `<cstring>` was missing for the strcmp().
While at it, remove superfluous headers.
Also: simplify a boolean return (there was a else after return issue, and the whole expression could be written more concise and readable anyway).
If there is a single statement in a block in a new line, add the necessary curly braces.
> Cleanup: Fix missing header in parsers.h and some clang-tidy issues.

- docs/contrib/DeveloperGuide.md
- etc/run-clang-tidy-cached.cc
Running clang-tidy is very slow and time consuming. We're already running it as part of pull requests to incrementally point out issues, but sometimes it would be good to see an overall summary or simply a way to figure out which clang-tidy checks make sense to keep.
This adds a new script to etc/ to allow running clang-tidy in parallel, while also caching the results. So subsequent runs only need to process files that have changed.
For simplicity, this script is written in C++, but it can be invoked as a script as it is self-compiling. So it is as simple as running
```
/bin/sh etc/run-clang-tidy-cached.cc
```
(or, with the executable bit set, you can invoke it
even simpler as `etc/run-clang-tidy-cached.cc`)
Note: The first time, before there is a cache built, this will take a while.
This …
> Add a script to run clang-tidy over all files in parallel, cache the results

- .clang-tidy
This will help finding missing and superfluous includes. Right now, over the project, there are a lot of findings, so let's see if this will be good or annoying until most of it is fixed.
> Enable misc-include-cleaner in .clang-tidy

- .clang-tidy
It warns on every enum if it is smaller than fitting into a uint32_t to use a smaller type. While it might be an interesting exercise at some point to look at these, right now, this is a somewhat noisy check.
> Switch off performance-enum-size clang-tidy check for now.

- src/pdn/src/shape.h
- src/pdn/src/via.h
No functional changes.
Just an attempt to run the parallel clang-tidy thing.
> pdn: clang-tidy unused namespace

- src/grt/src/fastroute/src/utility.cpp
- src/grt/test/congestion7-20.rptok
- src/grt/test/congestion7-40.rptok
- src/grt/test/congestion7.rptok
- src/utl/include/utl/algorithms.h
> utl:: check if container is empty on utl::shuffle

- src/dbSta/test/CMakeLists.txt
This does not do anything, since the code above handles the integration tests
> dbsta: remove stray or_integration_test from ctest

- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_init.cpp
- src/drt/src/dr/FlexGridGraph.cpp
- src/drt/src/dr/FlexGridGraph.h
Also use Boost's `flat_map` instead of `std::map`.
| Branch | Min [s] | Max [s] | Mean [s] | Median [s] | Relative |
|--------|---------|---------|----------|------------|----------|
| baseline | 400.68 | 400.80 | 400.74 ± 0.04 | 400.73 | 1.05 |
| `drt-graph-init-flip-keys` | 379.85 | 380.59 | 380.27 ± 0.26 | 380.37 | 1.00 |
| Branch | Min [s] | Max [s] | Mean [s] | Median [s] | Relative |
|--------|---------|---------|----------|------------|----------|
| baseline | 570.60 | 570.74 | 570.67 ± 0.05 | 570.66 | 1.06 |
| `drt-graph-init-flip-keys` | 538.44 | 538.73 | 538.57 ± 0.11 | 538.54 | 1.00 |
---
| Branch | Min [s] | Max [s] | Mean [s] | Median [s] | Relative |
|--------|---------|---------|----------|------------|----------|
| baseline | 168.32 | 168.69 | 168.53 ± 0.16 | 168.59 | 1.02 …
> drt: Flip map keys in graph init

- src/rmp/src/CMakeLists.txt
- src/rmp/src/abc_library_factory.cpp
- src/rmp/src/delay_optimization_strategy.cpp
- src/rmp/src/delay_optimization_strategy.h
- src/rmp/src/logic_extractor.h
- src/rmp/src/logic_optimization_strategy.h
- src/rmp/test/aes_nangate45.sdc
- src/rmp/test/aes_nangate45.tcl
- src/rmp/test/cpp/TestAbc.cc
Adds new pass based infrastructure to add new Abc optimization passes. The first delay based optimization is added here.
General intention is to build lots of interfaces that can be extended by both the public and private clients.
> rmp: Adds DelayOptimization pass to remapper

- src/gui/src/displayControls.cpp
The default min size is 60 while 3 last colums are between 26 and 28.
Before:
After:
> gui: Reduce display controls sections min size so 3 last columns can be resize to their content.

- src/grt/src/GlobalRouter.cpp
Fix CI failures.
With this update, only long pins (i.e., pins that crosses more than 2 gcells) will have their positions snapped closer to the instance edge.
> grt: only snap pins that crosses multiple gcells

- src/grt/src/GlobalRouter.cpp
Changes:
- removes the nested loops and replaces it with a "&" operation on two Boost Polygon90set.
On zerosoc sky130:
Previous implementation: `layerIsBlocked` takes 187.15s
New implementation: `layerIsBlocked` takes 0.28s
Speedup of 99.8%
> grt: use boost polygon90set in layerIsBlocked to speedup init

- src/drt/include/triton_route/TritonRoute.h
- src/drt/src/TritonRoute.cpp
- src/drt/src/dr/FlexDR.cpp
Before this patch the constructor of boost::asio::thread_pool{1} created a thread, regardless of if distributed_ was true.
Now it is wrapped in an optional so that it is only created if or when distributed_ becomes true.
This means that OpenROAD can be initialized without spawning any new threads (a niche usecase for sure, but useful in certain environments).
> [drt] Only spawn new threads when distributed_ is true

- src/psm/README.md
- src/psm/include/psm/pdnsim.h
- src/psm/src/pdnsim.cpp
- src/psm/src/pdnsim.i
- src/psm/src/pdnsim.tcl
- src/psm/test/CMakeLists.txt
- src/psm/test/gcd_no_vsrc_reuse.ok
- src/psm/test/gcd_no_vsrc_reuse.tcl
- src/psm/test/pdnsim_aux.py
Changes:
- if a previous solution is available, this allows the user to specify they want to use that instead of recomputing.
> psm: allow reuse of previous solution

- .github/workflows/github-actions-format-on-push.yml
clang-format behaves slightly differently between versions. Print out the version number used in the CI, so that it is possible for contributors to verify that they run exactly the version locally to avoid formatting issues in PRs.
> Print clang-format version in use in CI format check.

- src/odb/src/db/dbInst.cpp
When running pin_access before global routing in ORFS, access points are created for the existing instances. When it reaches the incremental repair stage, new instances that were inserted by resizer can be deleted. However, these instances don't have access points, and when destroying them, OR was crashing when calling `iterm->getAccessPoints()`.
This update changes the default value for `pin_access_idx_` to -1, and use it to check if the instance have access points before removing the link between their iterms and the access points.
> odb: remove link with aps only for instances that have aps

- src/gui/src/clockWidget.cpp
- src/gui/src/clockWidget.h
Closes #6400.
Changes:
- Optimizes instance search in CTS Viewer by disabling rendering when setting nodes to selected
- Previously, the CTS Viewer was rendering everything after each node was set to selected
- Changes items name hash table to unordered_map
> gui: optimizing find in clock tree viewer

- src/mpl2/src/hier_rtlmp.cpp
This PR changes the search attempts from a fixed number to using the lowest common multiple from all the layers that can be snapped as basis in order the explore more possibilities.
> mpl2: increase snapping search range based on the layers pitch

- docs/toc.yml
DFT seems to be missing from the docs build.
> docs: add dft to docs

- src/gpl/src/mbff.cpp
- src/gpl/test/CMakeLists.txt
- src/gpl/test/clust03.ok
- src/gpl/test/clust03.tcl
Changes:
- `cluster_flops` changes error to warning when clusterable flops are not found (this is consistent with the `scan_replace` which doesnt error out but warns when flops are not found).
> gpl: switch mbff to warning when flops are not found

- src/gpl/src/mbff.cpp
Moves the cleanup code to before exiting function to avoid leaving behind a bunch of instances.
> gpl: ensure cleanup occurs before exiting run

- src/drt/src/frRegionQuery.cpp
Secure and ISPD CI safe.
In `frRegionQuery::addBlockObj()` the condition `shape->typeId() == frcPathSeg`is always false when that part of code is reached. This is a very small piece of dead code (But one that threw me off for a while).
> drt: pathseg deadcode elimination

- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_maze.cpp
- src/drt/src/dr/FlexGridGraph.h
No functional change intended. This speeds up DRT by 3-8%, at least for `asap7` (varies depending on the design). Baseline is a recent commit from Oct 6.
| Branch | Min [s] | Median [s] | Relative |
|--------|---------|------------|----------|
| Baseline | 221.96 | 222.23 | 1.03 |
| This PR | 215.48 | 215.91 | 1.00 |
| Branch | Min [s] | Median [s] | Relative |
|--------|---------|------------|----------|
| Baseline | 337.61 | 338.30 | 1.08 |
| This PR | 312.99 | 313.16 | 1.00 |
> drt: Push node index computation up

- src/dpl/include/dpl/Opendp.h
- src/dpl/src/Opendp.cpp
This PR adds a public API for DPL that returns a cluster of instances, where every instances is adjacent to at least one instance inside the cluster.
This was requested by @bnmfw for his incremental pin access update.
This cluster should only contain instances that the pin access will do something, so tapcells and endcaps are ignored. Also, since macros are handled separately, they're also ignored.
> dpl: add API to get adjacent cells cluster

- src/cts/src/TechChar.cpp
The cts tech char creates a scratch pad dbBlock and Sta and creates low level liberty gates in a partial network.
Rather than register these as concrete, we turn off the hierarchical api (if hierarchical mode enabled) so that the default "Concrete" api calls are made.
This pattern seems likely to occur any time flat scratch pad sta/dbBlocks are created to evaluate different liberty gates.
> Cts techchar: Turn off hierarchical api during characterization

- src/odb/test/cpp/CMakeLists.txt
- src/odb/test/cpp/scan/CMakeLists.txt
Excluding the ODB c++ tests from CMake registration prevents a couple of issues:
1. Tests were being called twice: once from cpp_tests.tcl and once outside of it
2. Any test that writes/reads from the disk either fails or writes the output to the current working directory and not the results directory as intended
Addresses https://github.com/The-OpenROAD-Project/OpenROAD/issues/6388
> Updated ODB c++ tests to only be handled via cpp_tests.tcl

- src/odb/include/odb/db.h
- src/odb/src/db/dbBlock.cpp
Removed the dbBlock::duplicate method, which causes memory corruptions when used in the context of a Python unit test that destroys the DB as part of the tearDown method. The duplicate method doesn't appear to be used in any other OR code after checking *.c*, *.h*, *.i, *.tcl, and *.py files.
> removed dbBlock::duplicate which causes memory corruption issues

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
- src/mpl2/src/hier_rtlmp.cpp
- src/mpl2/src/hier_rtlmp.h
- src/mpl2/src/object.h
- src/mpl2/test/guides1.ok
- src/mpl2/test/guides2.ok
- src/mpl2/test/macro_only.ok
Based on the discussion in #6543 so that we can ignore fixed instances.
Also changing the feasibility of the macro placement to be based on the area computed using the global fence instead of directly the core.
> mpl2: do not allow fixed instances inside floorplan area

- src/mpl2/src/clusterEngine.cpp
- src/mpl2/src/clusterEngine.h
- src/mpl2/src/hier_rtlmp.cpp
Needs #6547
Resolve #6092 
Needed to switch from manual macro placement to automated macro placement in gf12/bp_single.
Note that I also needed to include the ignore check in the Orientation Improvement step.
> mpl2: ignore fixed instances

- src/odb/src/db/dbModInst.cpp
- src/odb/src/db/dbModuleModBTermItr.cpp
Two fixes: (a) ModBTerm doubly linked reversal, make sure prev field is set. (b) Avoid deleting unused ports/pins contained in busses from modules on after hierarchical connect.
> Modbterm iter reversal and Fix for Not removing unused pins/ports in busses after hierarchical connect

- docs/contrib/DeveloperGuide.md
Small typo, missing right bracket when referencing OpenSTA.
In HTML:
> Update(Doc): Missing bracket in Tool Flow Namespace Section

- src/cts/include/cts/TritonCTS.h
- src/cts/src/HTreeBuilder.cpp
This PR removes the insertion delay added to the clustering buffers.
For designs with macros clustered together the delay inserted caused the clustering buffers to be placed outside of the die area causing problems during the legalization.
> Cts don't insert delay for clustering buffers

- src/rsz/src/CMakeLists.txt
- src/rsz/src/MakeResizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
To get all the SWIG type conversion rules around basic STA types, it's best if we can source `StaTclTypes.i`. Here we make the change in the resizer binding, and use it to clean up some of the binding code. See the commits.
> rsz: Source `StaTclTypes.i` and clean up the binding

- test/Nangate45/Nangate45.vars
- test/sky130hd/sky130hd.vars
- test/sky130hs/sky130hs.vars
`macro_place_channel` is not used in flow.tcl anymore.
> remove old mpl macro_place_channel

- src/rmp/include/rmp/Restructure.h
- src/rmp/include/rmp/blif.h
- src/rmp/src/Restructure.cpp
- src/rmp/src/blif.cpp
- src/rmp/src/rmp.i
- src/rmp/test/rmp_aux.py
Removes the static variable rmp::Blif::call_id_ by moving it to Restructure.h as discussed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/5989
> rmp: removing static variable Blif::call_id_

- src/odb/src/db/dbBlock.cpp
- src/odb/src/db/dbGlobalConnect.cpp
- src/pdn/test/CMakeLists.txt
- src/pdn/test/add_double_global_connection.ok
- src/pdn/test/add_double_global_connection.tcl
Changes:
- I noticed that repeated calls to `add_global_connection` with identical parameters results in multiple identical rules.
- This adds a check for existing rules and removes the duplicate (this should also allow calls to global_connect to process faster since the duplicate rules would just double the runtime).
> odb/pdn: avoid double registration of identical connect rules

- src/ifp/include/ifp/InitFloorplan.hh
- src/ifp/src/InitFloorplan.cc
- src/ifp/test/CMakeLists.txt
- src/ifp/test/Nangate45_data/macros.v
- src/ifp/test/init_floorplan10.ok
- src/ifp/test/init_floorplan10.tcl
Adds:
- check for instances sizes against core area to avoid continuing when core will not support macros.
> ifp: add check for instance sizes in init flooorplan to fail quickly

- src/rcx/include/rcx/extRCap.h
- src/rcx/include/rcx/wire.h
- src/rcx/src/extCC.cpp
- src/rcx/src/extFlow_v2.cpp
- src/rcx/src/extRCmodel.cpp
- src/rcx/src/extRCmodel_solver.cpp
- src/rcx/src/extmain.cpp
- src/rcx/src/grids.cpp
Global and static variables removed (issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/5981)
Variables changed:
- rcx::SdbPlaceWireNoTouchCheckForOverlap [Removed]
- rcx::coupleOptionsNull [Removed]
- static variables from rcx::Ath__grid::buildDgContext(int gridn, int base):
- allCtxwire [Changed to a local vector]
- awcnt [Removed. It was used to help manage allCtxwire memory]
- awsize [Removed. It was used to help manage allCtxwire memory]
- rcx::OUREVERSEORDER [Moved to extRCTable and extMetRCTable] 
- rcx::ttttsrcnet [Removed]
- rcx::tttttgtnet [Removed]
- rcx::ttttm [Removed]
- rcx::ttttGetDgOverlap [Moved to Ath__gridTable]
Unused methods removed:
- uint Ath__grid::couplingCaps
- uint Ath__gridTable::couplingCaps
> RCX: removing static variables

- src/dbSta/src/dbSta.tcl
@maliberty this seems to be enough to resolve the issue I was having.
The issue was the list -> string conversion with escape characters.
> dbSta: fix modinst lookup

- src/mpl/src/SimulatedAnnealingCore.cpp
- src/mpl/src/clusterEngine.cpp
- src/mpl/src/clusterEngine.h
- src/mpl/src/graphics.cpp
- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
- src/mpl/src/object.cpp
- src/mpl/src/object.h
Resolve #6585 
Changes:
- Divide the IO Clusters into two types:
1) Group of Unplaced IO Pins
2) IO Pad
- When creating the hypergraph that will be used to build the dataflow maps and iterating over the terminals of an IO PAD net, consider the start of the path to be the bterm mapped to that PAD instead of the PAD itself so that MPL can see the connection properly inside SA.
- Do data flow before creating IO Clusters so that the IO Clusters creation can be based on the dataflow. With this, we'll only create IO Pad Clusters for the PADs that have useful connections macro placement wise.
Obs: Large nets are excluded from the hypergraph and not used by SA, so we don't want to look at those.
- Use the distance to boundary technique inside SA only for the first type of IO Clusters.
> mpl: add support for IO Pads

- src/odb/include/odb/db.h
- src/odb/src/db/dbNet.cpp
- src/rsz/src/Resizer.cc
Fixes remove_buffers failing with dont_touch set
Changes:
- mergeNet checks if iterm insts are marked dontTouch and return before making modifications to the design if any are set.
- removeBuffers will not remove a buffer is the net fails to be merged
> rsz/odb: check for mergeNet success before removing buffer

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/RepairDesign.cc
- src/rsz/src/RepairHold.cc
- src/rsz/src/Resizer.cc
@maliberty these are the fixes I needed to make dontTouch work for resizer (not universal, but point fixes for each place I found it violating the dontTouch flag).
> rsz: account for dont use during repairDesign and hold

- src/rsz/src/EstimateWireParasitics.cc
As mentioned in [#6651]( https://github.com/The-OpenROAD-Project/OpenROAD/discussions/6651#discussioncomment-12083425), the resistance for clk wires when there is no layer or orientation provided always uses horizontal resistance. It should consider also the vertical resistance, like it is done for clk wire capacitance.
> rsz: if no layers or orientation are specifeid consider bot H & V resistance for clk wires

- src/dst/CMakeLists.txt
- src/dst/include/dst/Distributed.h
- src/dst/src/Distributed.cc
- src/dst/src/MakeDistributed.cc
Tackles #6532.
GRT depends on DRT, which in turn depends on DST. Thus, it is necessary for a DST_LIB linkable with core code to exists that does not depend on the ORD singleton. This PR creates this separation.
This should be the final PR on the issue, as the three together actually solve the issue.
> dst: dst_lib linkable

- .github/workflows/github-actions-repo-stats.yml
> ci: Repo stats workflow

- src/gpl/src/nesterovBase.cpp
There are probably meant to be debugPrints, but removing them and they can always be added back correctly.
> gpl: remove callback prints

- src/CMakeLists.txt
When ortools is not installed in /opt/or-tools/ the previous setting is useless, this ensures cmake handles the rpath setting.
> cmake: use CMAKE_INSTALL_RPATH_USE_LINK_PATH instead of hardcoded paths

- flake.nix
URL Literals are legacy syntax which has been long disallowed in NixOS/nixpkgs, since Lix release 2.92 they have been deprecated in Lix. See <https://lix.systems/blog/2025-01-18-lix-2.92-release/>. Using the normal string syntax makes this flake compatible with both Nix implementations without any special flags.
> flake.nix: replace deprecated url literal with a string literal

- src/rsz/README.md
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/Resizer.cc
- src/rsz/src/Resizer.i
- src/rsz/src/Resizer.tcl
- src/rsz/test/CMakeLists.txt
- src/rsz/test/report_overdriven_nets1.ok
- src/rsz/test/report_overdriven_nets1.tcl
- src/rsz/test/report_overdriven_nets1.v
- src/rsz/test/report_overdriven_nets2.ok
- src/rsz/test/report_overdriven_nets2.tcl
- src/rsz/test/report_overdriven_nets2.v
- src/rsz/test/report_overdriven_nets3.ok
- src/rsz/test/report_overdriven_nets3.tcl
- src/rsz/test/report_overdriven_nets3.v
- src/rsz/test/report_overdriven_nets4.ok
- src/rsz/test/report_overdriven_nets4.tcl
- src/rsz/test/report_overdriven_nets4.v
- src/rsz/test/report_overdriven_nets5.ok
- src/rsz/test/report_overdriven_nets5.tcl
- src/rsz/test/report_overdriven_nets5.v
- src/rsz/test/report_overdriven_nets6.ok
- src/rsz/test/report_overdriven_nets6.tcl
- src/rsz/test/report_overdriven_nets6.v
When debugging the dont_touch issues, I noticed several instances were resizer ended up with multiple drivers on a net (fixed by https://github.com/The-OpenROAD-Project/OpenROAD/pull/6708) but it didn't appear that we had any way of reporting these types of issues.
This adds:
- `report_overdriven_nets` (a mirror to `report_floating_nets`) which report nets with multiple drivers accounting for nets with tristate drivers.
> rsz: add command to report nets driven by multiple drivers

- .gitignore
- src/gui/include/gui/gui.h
- src/gui/src/gui.cpp
There is currently an issue where clicking on any sta::Instance on macOS causes a crash. This is owing to an oddball RTTI issue that I've spent some time debugging but was ultimately unable to resolve.
My hypothesis as to why this issue does not surface on GNU/Linux is because of the specific type_info implementation in the GNU C++ standard library, libstdc++. This email chain from the libc message list may be insightful: https://lists.llvm.org/pipermail/llvm-dev/2014-June/073465.html
As a workaround, I've elected to use a compiler macro and only use type_index hashes if `__GLIBCXX__` is [EDIT: defined], otherwise, the mangled ABI names are used as the key for descriptors instead. With this fix, clicking on instances works on macOS. This, unfortunately, will incur a performance penalty, …
> gui: fall back to type name hashing when not using libstdc++

- src/README.md
- src/dbSta/include/db_sta/dbSta.hh
- src/dbSta/src/dbSta.cc
- src/dbSta/src/dbSta.i
- src/dbSta/src/dbSta.tcl
Add snapshot creation functionality to report_cell_usage. This will only be active if -file flag is specified (and optionally a name can be given to the stage at which the snapshot is created)
> dbSta: Add snapshot creation to report_cell_usage

- src/mpl/doc/debugMessages.md
- src/mpl/src/MplObserver.h
- src/mpl/src/SACoreHardMacro.cpp
- src/mpl/src/SACoreHardMacro.h
- src/mpl/src/SACoreSoftMacro.cpp
- src/mpl/src/SACoreSoftMacro.h
- src/mpl/src/SimulatedAnnealingCore.cpp
- src/mpl/src/SimulatedAnnealingCore.h
- src/mpl/src/graphics.cpp
- src/mpl/src/graphics.h
- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
- src/mpl/src/util.h
This will help a lot to see the results for each outline of cluster placement, especially when we need to know what happened at the level of each individual cost inside the annealer.
1. Wrap utilities in mpl namespace;
2. Adapt debug docs.
3. Compute area penalty in base class to avoid duplicated code and allow the debug report approach used in this PR.
1. Remove unused debugPrint messages
2. Report summary for each cluster/macro placement in table format.
> mpl: clean up / improvements of debug messages & some fixes

- src/odb/include/odb/db.h
- src/odb/src/db/dbBTerm.cpp
- src/odb/src/db/dbBTerm.h
- src/odb/src/db/dbDatabase.h
First step to store mirrored pins in odb. The next PR will update PPL to write the data into odb.
> odb: add mirrored pin data into dbBTerm

- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/RepairDesign.cc
- src/rsz/src/Resizer.cc
For large (private) PDKs that have many equivalent cells (~50 per logic type), large designs spend significant time recomputing the equivalent cell list during rsz operations. In typical OR flows, the liberty library does not change after init so this list should not have to be recomputed.
Also move checking of `dontUse()` and `isLinkCell() `to `getSwappableCells()` so it does not have to be repeatedly checked. This also eliminates the need to remember to conduct this check where it is called. The cache is reset if an additional liberty file is read or when the dont_use set is updated.
Baseline private design `global_placement -timing-driven` : 52s
With caching private design `global_placement -timing-driven`: 29s (-44%)
On a large private design, time attributed to these calls was …
> rsz: Cache result of getSwappableCells()

- src/mpl/src/SACoreSoftMacro.cpp
- src/mpl/src/SimulatedAnnealingCore.cpp
- src/mpl/src/object.cpp
This is a hack fix for the compiler bug or real returning [a,b] inclusive. See https://github.com/The-OpenROAD-Project/OpenROAD/pull/6649 for the proper fix
> mpl: Fix random index generation with hack

- src/gui/src/timingWidget.cpp
- src/gui/src/timingWidget.h
This is to help when we want to check what happens to a path across different versions of OR.
Closest Match option now becomes a menu with two options:
- Exact (Same as the previous Closest Match)
- No Buffering (Exclude buffers and back-to-back inverters)
> gui: add option to exclude buffering nodes when generating report_checks

- src/utl/src/prometheus/metrics_server.cpp
ip::address::from_string is deprecated since 1.66.0 with an explanation to use make_address() instead.
https://beta.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/ip__address/from_string.html
Last version it is available is in boost 1.86.0
https://beta.boost.org/doc/libs/1_86_0/doc/html/boost_asio/reference/ip__address/from_string.html
The current 1.87.0 has it removed.
> ip::address::from_string is deprecated, use make_address instead.

- src/cts/src/CMakeLists.txt
- src/cts/src/CtsOptions.cpp
- src/cts/src/CtsOptions.h
- src/cts/src/TritonCTS.cpp
- src/cts/test/array.ok
- src/cts/test/array.tcl
- src/cts/test/cts_aux.py
- src/cts/test/simple_test.ok
- src/cts/test/simple_test.py
- src/cts/test/simple_test.tcl
- src/cts/test/simple_test_clustered.ok
- src/cts/test/simple_test_clustered.py
- src/cts/test/simple_test_clustered.tcl
Changes:
- no functional changes to CTS, but adds tracking of the masters used during CTS to be able to report that as part of report_cts
> cts: add recording of masters used to report_cts

- src/rcx/src/extRCmodel.cpp
Changes:
- checks the lower bound on array access for `extDistRCTable`, since this table can be empty, `getLastRC` would access `-1` which throws an error.
> rcx: check bounds in extDistRCTable in case of empty table

- src/rsz/src/Resizer.cc
Macros are still later skipped by nature of being FIXED, but some PDKs do not specify the SITE in the LEF for macros, so a crash can occur if site is nullptr in balanceRowUsage().
> rsz: Fix a crash in row balancing for PDKs with macros w/out a SITE in the LEF.

- etc/DependencyInstaller.sh
Installing all dependencies is now explicit with -all.
Option -base also requires priviledged access.
> etc: Update script usage.

- default.nix
Use nix instead of CMake to download all necessary deps.
> Prevent CMake from downloading content with FetchContent

- src/mpl/src/clusterEngine.cpp
- src/mpl/src/clusterEngine.h
- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
... so that we know which type of overlap happened when the boundary pushed is reverted.
As I was creating the tests for boundary pushing I ran into a weird overlap push reverting which should not happen.
- Remove top module `Metrics` pointer (which is accessible through the `PhysicalHierarchy` and doesn't need caching) from `HierRTLMP` class and its wrong setter API from the `ClusteringEngine` class.
> mpl: avoid creating blockages with zero depth and improve debug messages

- src/gui/src/chartsWidget.cpp
Fixes:
- this function enters an infinite loop when there are no paths
> gui: escape populateBuckets when paths are empty

- src/cts/src/Clustering.cpp
- src/cts/src/Clustering.h
- src/cts/test/cts_unittest.cc
Adding a new mode to CKMeans that does not adjust
the branch length. The start of some infrastructure to do high fanout net synthesis.
> cts: Adds a CKMeans mode without branching

- etc/DependencyInstaller.sh
Official site download links are at https://www.boost.org/users/history/.
Sourceforge causes troubles with my company Zscaler gateway and makes wget to fail. Accessing Sourceforge from a browser shows the message below asking to confirm access to the site. Once done the gateway allows wget to do the download.
You tried to visit: https://sourceforge.net/
Request method cautioned for category Shareware Download This website is providing free to try software downloads. We remind you that, in accordance with your company policy, you must not download any software from the internet directly.
> etc: Get boost package from https://archives.boost.io as referenced by official site.

- src/drt/src/pa/FlexPA.cpp
- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_init.cpp
Supports #5867.
Me and Eder have started implementing incremental PA on the GRT flow, so now I'm seeing what I missed when preparing the structures to implement it, this is one of those. The initialization of skipInstTerm has to be able to be done for a single instance during incremental PA, so it cannot be a done only once for every instance and then never more accessible.
> drt: dynamic initSkipInstTerm

- src/gpl/README.md
- src/gpl/include/gpl/Replace.h
- src/gpl/src/nesterovBase.h
- src/gpl/src/nesterovPlace.cpp
- src/gpl/src/replace.cpp
- src/gpl/src/replace.i
- src/gpl/src/replace.tcl
This change allows for updating OpenROAD db during every iteration of gpl, allowing for up to date locations during gpl debug mode.
We currently have this situation, where the instances as seen by the tool are always delayed until a call to the function updateDb() happens. Notice how gpl drawings in green do not align with instances from the gui.
with the new option we have:
This option maybe costly in runtime, so is set as false for default.
> gpl: debug mode update db option

- src/drt/src/db/obj/frBlock.h
- src/drt/src/io/io.cpp
- src/drt/src/io/io.h
- src/drt/src/pa/FlexPA_acc_pattern.cpp
- src/drt/src/pa/FlexPA_unique.cpp
Supports #5867.
This PR contains some minor changes to support the translation of dbInst data to frInst data. During incremental PA the GRT will only request changed to dbInst objects, while the DRT works only with frInst data. This makes changes to make this communication smoother.
`findInst()` requires the name of the inst to retrieve the respective `frInst*`, another function of the same name, that expects a `dbInst*` instead of a string was created. This is very minor (1 single line of code + 1 import), but helps clean some other parts of the code up.
The main change is that now the function returns the raw pointer of the created `frInst*`. Incremental PA is being build to support the passing of an instance not already initialized in the DRT. If this is the case, this will be done by …
> drt: better dbInst to frInst translation

- src/odb/src/db/dbBTerm.cpp
Previously, for a pair `{p1, p2}` of mirrored pins, only _p1_ had the information about _p2_ being its mirrored pin.
Now, both pins of the pair knows about each other, and we keep the information of what is the "main" pin by checking if the pin is mirrored when defining if it has a mirrored bterm.
> odb: add mirrored bterm info for both pins of the pair

- src/drt/src/pa/FlexPA_unique.cpp
- src/drt/src/pa/FlexPA_unique.h
Supports #5867.
Creates the `computeUniqueClass()`. I simply want to call this during incremental PA to catch the corner case where a moved inst kept the same unique inst.
> drt: drt_compute_inst_to_unique_class

- src/gui/src/chartsWidget.cpp
Fixes:
- before the unconstrained top level ports would not get counted as unconstrained and endpoints with no fanout would get counted as unconstrained since they have INF slack, but also have no logic.
This change ensures top level ports are handled and we check for more than 1 connection on an endpoint to avoid considering those as unconstrained
> gui: correct counting of unconstrained paths in charts widget

- src/gpl/.gitignore
As suggested in https://github.com/The-OpenROAD-Project/OpenROAD/pull/6897
The folder was accidentally added on a [commit to update gpl tests](https://github.com/The-OpenROAD-Project/OpenROAD/commit/250e48e05383b78791663ae7105b572ae860acd8).
> gpl: include Testing folder to gitignore

- src/odb/src/defin/definReader.cpp
- src/odb/src/defin/definReader.h
- src/odb/test/create_sboxes.ok
- src/odb/test/def_parser.ok
Also changed error callback ID from 1003 to 3, to avoid duplicate.
As find message doesn't catch message without double quote.
> odb/defin: Redirect defWarning to the logger.

- src/mpl/test/boundary_push2.defok
- src/mpl/test/boundary_push2.ok
- src/mpl/test/boundary_push2.tcl
- src/mpl/test/boundary_push3.defok
- src/mpl/test/boundary_push3.ok
- src/mpl/test/boundary_push3.tcl
- src/mpl/test/guides1.defok
- src/mpl/test/guides1.ok
- src/mpl/test/guides1.tcl
- src/mpl/test/io_constraints1.defok
- src/mpl/test/io_constraints1.ok
- src/mpl/test/io_constraints1.tcl
- src/mpl/test/io_constraints2.defok
- src/mpl/test/io_constraints2.ok
- src/mpl/test/io_constraints2.tcl
- src/mpl/test/orientation_improve1.defok
- src/mpl/test/orientation_improve1.ok
- src/mpl/test/orientation_improve1.tcl
- src/mpl/test/orientation_improve2.defok
- src/mpl/test/orientation_improve2.ok
- src/mpl/test/orientation_improve2.tcl
Resolve #6886
We now use only the commands for setting the constraints instead of also calling `place_pins`, because running them  will already incorporate the constraints' data into ODB.
> mpl: avoid calling ppl in regression tests by using new constraints' commands

- .bazelrc
Warnings from external components such as or-tools are not actionable, so tell bazel not to emit them.
While at it, prettify .bazelrc a bit.
> .bazelrc: silence warnings from components outside the project.

- .bazelrc
With `bazel build --config=asan ...`, enable the
llvm https://clang.llvm.org/docs/AddressSanitizer.html for easy debugging of memory access issues.
> Add a configuration to use address sanitizer.

- BUILD.bazel
- src/odb/src/def/BUILD
- src/utl/BUILD
Move the BUILD for this target more closely to the sources.
While at it, run `buildifier` on all BUILD files
to get a canonical formatting (`buildifier` is
for BUILD files what `clang-format` is for c++ files).
> Move `//:opendb_def` -> `//src/odb/src/def:def`

- src/grt/src/GlobalRouter.cpp
Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/6926
> grt: clean containers with dbNets data when initializing grid and nets

- src/ifp/test/upf/mpd_top.upf
- src/upf/README.md
- src/upf/src/upf.cpp
- src/upf/src/upf.tcl
- src/upf/test/CMakeLists.txt
- src/upf/test/data/isolation/mpd_top.upf
- src/upf/test/data/isolation/mpd_top_select_iso.upf
- src/upf/test/isolation_select.ok
- src/upf/test/isolation_select.tcl
- src/upf/test/isolation_select.vok
- test/upf/mpd_aes.upf
- test/upf/mpd_top.upf
- test/upf_test.defok
- test/upf_test.ok
The smallest isolation cell was selected without considering whether inverters were needed, so in some cases, the smallest isolation plus the required inverters had a bigger area than the isolation cell that didn't require any inverters.
Changes:
- `find_smallest_isolation` now chooses the smallest area of isolation cell plus the required inverters.
- `isolation_select` test added.
- `use_interface_cell` tcl/upf command:
- `lib_cells` argument now supports lists;
- `interface_implementation_name` argument has been added to be UPF 2.1 compliant.
- Additional isolation cells options added to the tests:
- `test/upf_test`;
- `test/aes`.
> Upf: choose isolation

- .github/workflows/github-actions-bazel-build.yml
- bazel/build_helper.bzl
Since it is experimental, I wrapped it in a `|| /bin/true` so that even if it fails, the CI is fine.
> Add a simple CI to run the bazel build.

- src/mpl/src/SACoreSoftMacro.cpp
Missing line in the table.
Old:
```
Penalty Type  |  Weight  |  Value  |  Norm. Factor  |  Cost
---------------------------------------------------------------
Area |   0.1000 |  0.9751 |         1.0000 |  0.0975 
Outline | 100.0000 |  0.0000 |         4.4037 |  0.0000 
Wire Length | 100.0000 |  0.1420 |         0.6828 | 20.8028 
Guidance |  10.0000 |  0.0000 |         1.0000 |  0.0000 
Fence |  10.0000 |  0.0000 |         1.0000 |  0.0000 
Macro Blockage |  10.0000 |  0.0000 |         9.8476 |  0.0000 
Notch |  10.0000 |  0.0000 |         1.0000 |  0.0000 
---------------------------------------------------------------
Total Cost                                            35.3747 
```
New:
```
Penalty Type  |  Weight  |  Value  |  Norm. Factor  |  Cost …
```
> mpl: include boundary penalty in debug table

- .github/workflows/github-actions-clang-tidy.yml
We're seeing linting issues like in this [PR](https://github.com/The-OpenROAD-Project/OpenROAD/pull/6916)
`warning: 'omp.h' file not found [clang-diagnostic-error]`
The underlying problem was that the correct version of libomp was not installed as a dependency.
> included libomp-15-dev to clang-tidy action

- .github/workflows/github-actions-bazel-build.yml
We have now the first tests wired up, let's run them. Switch to `-c opt` mode to not have them time out
(unfortunately, that also means a longer initial build time, but things will be cached)
> bazel: run tests in the CI

- BUILD.bazel
- WORKSPACE
- src/odb/src/lef/BUILD
Once we've switched to MODULE.bazel, we can add to CI(now we get false positives):
buildifier -r -lint warn .
> bazel: ran buildifier -r .

- BUILD.bazel
- MODULE.bazel
- src/Main.cc
This PR sets TCL_LIBRARY dynamically based on the runfiles location of the binary. Fixing running bazel outside the context of bazel. So that running `./bazel-bin/openroad` works as expected.
> meta: Adds ability to locate bazel runfiles dynamically

- src/Main.cc
fixes #7002
```
$ bazel build -c opt :openroad
$ cp bazel-bin/openroad .
$ ./openroad 
ERROR: external/rules_cc~/cc/runfiles/runfiles.cc(123): cannot find runfiles (argv0="./openroad")
$ echo $?
1
```
> openroad: fix segfault

- test/BUILD
- test/regression.bzl
Remove the timeout that is not used in the regression test,
as the `"medium"` fallback prevented the test size (which is passed
as argument) to have an effect on the timeout.
> bazel: Remove `timeout` which is not used in regression test.

- src/utl/src/Logger.cpp
When using a system spdlog library with version < 1.6.1 (e.g. [ubuntu 20.04 focal](https://packages.ubuntu.com/focal/libspdlog-dev)), compiling OpenROAD fails.
This is due to a [location change of `spdlog/details/pattern_formatter.h` to `spdlog/pattern_formatter.h`](https://github.com/gabime/spdlog/commit/752d5685dce44307bf3b0db9673f385628a32af0#diff-bbb51ff727831e269d19b7faac49198b7194a9d859ae2434df2e58f40219bd2b). I added a preprocessor directive to `src/utl/src/Logger.cpp` to support both locations.
> Use pattern_formatter.h from details when using spdlog < 1.6.1

- .bazelrc
- .github/workflows/github-actions-bazel-build.yml
... so that it is not necessary to remember the flag everyt time one runs the flow tests.
> bazel: configure timeout times in .bazelrc

- src/ppl/src/IOPlacer.cpp
When using `overlaps`, pins cannot be placed at the border of the top layer region. Using `intersects` fix the problem.
> ppl: use intersects instead of overlaps when checking top layer region

- src/dpl/include/dpl/Coordinates.h
- src/dpl/include/dpl/Objects.h
- src/dpl/include/dpl/Opendp.h
- src/dpl/include/dpl/OptMirror.h
- src/dpl/include/dpl/Padding.h
- src/dpl/src/CheckPlacement.cpp
- src/dpl/src/DecapPlacement.cpp
- src/dpl/src/FillerPlacement.cpp
- src/dpl/src/Objects.cpp
- src/dpl/src/Opendp.cpp
- src/dpl/src/OptMirror.cpp
- src/dpl/src/dbToOpendp.cpp
- src/rsz/include/rsz/Resizer.hh
- src/rsz/src/BufferedNet.cc
- src/rsz/src/BufferedNet.hh
- src/rsz/src/RecoverPower.hh
- src/rsz/src/RepairDesign.cc
- src/rsz/src/RepairDesign.hh
- src/rsz/src/RepairSetup.hh
- src/rsz/src/SteinerTree.cc
- src/rsz/src/SteinerTree.hh
Shortcuts like `using std::vector` pollute the namespace for everyone including the header. Even if they are used within a namespace, now a `foo` namespace suddenly has a `foo::vector`.
This first fix works on fixing the `std::` using statements, but there are a bunch more that need to be addressed.
> Don't use `using std::something` in header files.

- .bazelrc
To create a executables that keep enough debug information to retain useful symbols for use in e.g. running Linux `perf`
```
bazel build -c opt --config=profile //:openroad
```
> bazel: Add config with debug flags useful for creating a profile.

- BUILD.bazel
- bazel/build_helper.bzl
It is harder to navigate and see what is going on when some of these variables are hidden away in the build_helper.bzl. This is a first step to get more visibility for the developer to see the dependencies.
> bazel: move some variables from build_helper.bzl to BUILD.bazel

- src/grt/test/congestion7.tcl
- test/helpers.tcl
fixes #7109
To examine a failing test, re-run it with:
bazel test --test_output=all --sandbox_debug //path/to:test
> bazel: use TEST_TEMPDIR for results folder

- src/gui/src/chartsWidget.cpp
- src/gui/src/chartsWidget.h
The casting to and from floats and int causes large numbers to overflow and the while loops just get stuck when presented with a huge difference in min and max values.
> gui: fix inf loop on huge numbers

- src/cts/src/TritonCTS.cpp
Fixes [#6352](https://github.com/The-OpenROAD-Project/OpenROAD/issues/6352)
CTS skips building the clock tree for clock nets that already have a clock tree. The way CTS checks if the clock tree is already generated is by looking at the clock nets and checking if there is a clock buffer in it and if the master of the buffer is the same as the masters used by CTS.
This check can cause a misunderstanding, if there is a buffer in the clock tree that is not from a clock tree but has the same master, and it will skip creating a clock tree when it shouldn't.
This PR fixes this by also checking the source type of the buffer, and only skips if the source of the buffer is `TIMING`.
> CTS fix wrong clock net skiping

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
Partial solution for https://github.com/The-OpenROAD-Project/OpenROAD/issues/7100.
> grt: do not init clock nets when checking if design is routed

- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovBase.h
- src/gpl/src/nesterovPlace.cpp
- src/gpl/src/nesterovPlace.h
Instead of using both an error counter per region and a boolean flag to check for divergences, use only the counter and check if it's greater than zero where needed.
Remove unnecessary variables. Since NesterovPlace reports the errors, there's no need for a separate error message in NesterovBase.
Ensure that the divergence snapshot is stored after checking for divergence.
> gpl: simplify divergence detection logic

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_acc_point.cpp
Supports #7153.
Isolates the piece of code that receives a Via, a Rectangle and a direction and inserts the PA coords onto the input map.
This is a very cheap and almost inconsequential refactor but I think it can be useful later down the line when trying to generate new access points for vias besides the first 2
> drt: genViaEnclosedCoord

- src/pdn/src/pdn.tcl
Change `$key`, which does not exist,  to `$keys`.
> pdn: Fix typo in code

- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
Closes #7197
Issue:
- before each Node intersecting an iterm geometry in the wire graph was considered a source, but this caused multiple nodes to appear as unrouted segments even if the a different node pair was found.
Fix:
- cluster nodes by iterm mpin so any node pair that is found between two iterm mpins is considered routed and no flywire is needed. If no pairs are found the same set of flywires are drawn.
> gui: cluster net wire nodes by pins to avoid drawing flywires on strongly connected pins with multiple geometries

- src/gui/README.md
- src/gui/include/gui/gui.h
- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
- src/gui/src/layoutTabs.cpp
- src/gui/src/layoutTabs.h
- src/gui/src/layoutViewer.cpp
- src/gui/src/layoutViewer.h
- src/gui/src/mainWindow.cpp
- src/gui/src/options.h
Closes #7191 
Adds:
- control of background color to the display controls (as Misc/Background)
- add color option to `gui::set_display_controls` to support common colors in openroad or as `#rrbbggaa`
> gui: background color support

- src/psm/include/psm/pdnsim.h
- src/psm/src/CMakeLists.txt
- src/psm/src/pdnsim.cpp
No functional changes, just removing pad as a dependency from psm and fix the inclusion of dpl (which really should be in dpl and not in psm)
> psm: remove dpl and pad as dependencies for psm

- include/ord/OpenRoad.hh
- src/OpenRoad.cc
- src/OpenRoad.i
- src/dbSta/include/db_sta/dbReadVerilog.hh
- src/dbSta/src/dbReadVerilog.cc
- src/dbSta/src/dbReadVerilog.tcl
- src/dbSta/test/CMakeLists.txt
- src/dbSta/test/read_verilog10_no_prop.ok
- src/dbSta/test/read_verilog10_no_prop.tcl
- src/dbSta/test/readdb_hier.ok
Added -omit_filename_prop argument to link_design, which is intended for internal use only.
When set, OR doesn't create the src_file_# on the dbBlock nor the src_file_id or src_file_line properties on the dbInst. Since the file location stored in src_file_# can vary when running in different workspaces, the resulting ODB files are not exact. 
This primarily used for debugging differences between workspaces.
Added read_verilog10_no_prop.tcl to test new flag and updated read_verilog10.tcl to verify that the src_file_# prop is created.
> Added for-internal-use command line arg to link_design

- src/odb/src/db/dbModule.cpp
@precisionmoon this attempts to preserve the dbModBTerm connection  with undo.
Marked as draft until you indicate it helps resolve the issue.
> Disconnect dbModBTerms during destroy to allow restore from journalling

- .gitignore
make bazel-* ignore pattern narrower to clean up local goop more regularly. bazel-* folders can accrue in local `make issue` folders.
gitignore should:
- include all files that should exist locally, like IDE files, but should not be committed
- not include local goop that should be cleaned up regularly
git status should list:
- changes to be committed new or exisiting files
- files that should be deleted locally to keep the source folder nice and short and make sure that use-cases like IDE and "grep -r" remain nice and fast.
> gitignore: ignore bazel & Scala stuff

- Jenkinsfile
Implement a build retention policy that retains builds and artifacts for 20 days for the default branch.
Any other branches are limited by 10 builds on rotation.
> Added build retention policy for multi-branch pipeline

- .bazelrc
This explains why I didn't see any artifacts or error messages w.r.t. user.bazelrc setup for artifact server.
> bazelrc: fix typo for try-import

- src/cts/README.md
- src/rsz/README.md
Added description for inst name prefixes used when rsz & cts insert buffers.
> Added description of inserted inst name prefixes

- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
- src/mpl/test/cpp/TestSnapper.cpp
Related to #6267, #6836 and #6991.
This PR adds a warning when a pin from a macro wasn't aligned by the Snapper, and throw an exception if the related pin's layer has the constraint RightWayOnly. 
The code was integrated with the function `totalAlignedPins` (renamed from `totalPinsAligned`) and wrapped by `reportUnalignedPins`.
This PR also incorporates a small optimization where previously I was creating a vector with a amount of zeros and then used `push_back` on it, when I actually meant to use `reserve`. This does not change the code behaviour.
With this being merged, I think most work on the Snapper is finished for the time being, closing the related issues.
> mpl: warn/exception when a pin is not aligned by Snapper

- bazel/tcl_wrap_cc.bzl
adding some linebreaks makes buildifier format the code in a more readable fashion
> bazel: fix buildifier readability

- src/dpl/src/Opendp.cpp
- src/dpl/src/objective/detailed_displacement.cxx
- src/dpl/src/objective/detailed_hpwl.cxx
- src/dpl/src/optimization/detailed.cxx
- src/dpl/src/optimization/detailed_reorder.cxx
- src/dpl/src/optimization/detailed_vertical.cxx
- src/dpl/test/dpl_test.cc
Tried these instructions https://github.com/The-OpenROAD-Project/OpenROAD/pull/7269#issuecomment-2849049020
There are many 1358 "warning: included header ... is not used directly" warnings, fixed a few at the compilation unit level.
Fixing those in include headers is trickier as it requires adding include files in some other file where they are used.
Google coding standard, which I guess we're following here, is to disallow forward declarations like "struct Foo;". Rather one should include onlyh what is used in a .h/.cpp file.
> includes: prune some unused includes

- src/odb/src/db/tmg_conn.cpp
- src/odb/src/db/tmg_conn.h
In the function `splitBySj`, the call to `addRc` in the `while` loop pushes an element to the vector `_rcV`. It may thus be reallocated, causing the pointer `sj` to become invalid and a use-after-free when this pointer is later dereferenced.
My fix consists in re-defining the `sj` pointer on each loop based on the index in the vector, to ensure that it is always valid.
I observed this bug by providing as input a design in which one net has 395 wire segments in a single wiring.
> Fix Use After Free in splitBySj

- src/odb/src/db/dbTable.h
Provides a 13% improvment on 2 million standard cell block `report_checks` call.
> odb: Marking table as final

- src/ant/test/BUILD
- src/cts/test/BUILD
- src/dbSta/test/BUILD
- src/dft/test/BUILD
- src/dpl/test/BUILD
- src/drt/test/BUILD
- src/fin/test/BUILD
- src/ifp/test/BUILD
- src/mpl/test/BUILD
- src/odb/test/BUILD
- src/pad/test/BUILD
- src/par/test/BUILD
- src/pdn/test/BUILD
- src/ppl/test/BUILD
- src/psm/test/BUILD
- src/rcx/test/BUILD
- src/rmp/test/BUILD
- src/tap/test/BUILD
- src/upf/test/BUILD
- src/utl/test/BUILD
- test/regression.bzl
I wrote this up while looking at target vs. exec configurations. This PR does not change anything, but it will be easier in the future to work on a test bazel rule than the macro that is getting a bit out of hand.
Nice way to view dependencies worth sharing with the group:
```
bazelisk cquery -c opt --output=graph 'allpaths(//..., //:openroad)' | xdot /dev/stdin
```
To view configs:
```
$ bazel config
$ bazel config
INFO: Invocation ID: 6cce44db-fcdc-4080-b800-3a532ee857cf
Available configurations:
0b24ccd92eac9aee30d9c3421cff5361ddbe5c98eb3ea136284156efe217cc05 k8-opt-exec-ST-d57f47055a04 (exec)
179bdd4dff24859741914c63e292d5d478f34934b4e420b74789777a63ddf529 k8-opt-exec-ST-d57f47055a04 (exec)
2646c780eef9dc8fac37e9c1b8ed1835783fe77977a89a4be239f50aeef4ce3b k8-opt …
```
> bazel: introduce test rule(), macros are getting hairy

- BUILD.bazel
This is used to find tcl files in a future PR in OpenSTA
> bazel: add runfiles deps to OpenSTA

- src/rcx/include/rcx/util.h
The delete operator use for AthHash is wrong. Use the correct one
> Correct delete operator for AthHash

- src/rcx/src/extRCmodel.cpp
Since 4c290dc, the extMeasure destructor is skipped, leading to memory leaks notably of the _rc array. Why was such behaviour introduced in the first place, and shouldn't it be reverted?
> Do not skip the destructor in extMeasure

- src/rcx/src/extRCmodel.cpp
This avoid having a segfault because _computeTable may be set to an unititialized memory location due to _computeTableR
> Correctly initialize and clear the arrays

- src/pdn/test/BUILD
@gadfort FYI c2a61f64d3c389d7fc243d61f0c758716ed5ae6a
> bazel: fix macros_channel_recursive_repair test

- src/drt/src/dr/FlexDR.h
- src/drt/src/dr/FlexDR_init.cpp
When trying to find a matching layer in the other routing direction, the search is limited to layers selected for routing rather than all tech layers.
In addition, the code now also checks the layer is in the actual routing direction that's expected.
Finally because that code logic was duplicated a few times, it gets isolated in a helper function to make it easier to follow and track what's going on.
> drt: Use Bottom/Top routing layer in FlexDRWorker::initTrackCoords

- src/odb/src/def/BUILD
the bison generated header should not be visible from cc_library(name="def",...)
> bazel: reduce scope of bison generated header

- src/odb/src/def/BUILD
This produces an openroad build now:
bazelisk build --cxxopt=-stdlib=libstdc++ --linkopt=-lstdc++ -c dbg :openroad
Whereas this [still fails](https://github.com/The-OpenROAD-Project/OpenROAD/issues/7349):
bazelisk build -c dbg :openroad
> bazel: stopgap way to create debug build

- bazel/tcl_encode_sta.bzl
Hmmm... why?
Shouldn't this fix go into tclsh upstream?
@hzeller @QuantamHD Thoughts?
This fixes the `application-specific initialization failed: unknown encoding "ascii"` error with `bazel build -c opt :StaTclInitVar`
```
$ bazel build -c opt :StaTclInitVar 
INFO: Analyzed target //:StaTclInitVar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:StaTclInitVar up-to-date:
bazel-bin/StaTclInitVar.cc
INFO: Elapsed time: 0.442s, Critical Path: 0.26s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
$ bazel build -c opt @tk_tcl//:tclsh
INFO: Analyzed target @@tk_tcl//:tclsh (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @@tk_tcl//:tclsh up-to-date:
bazel-bin/external/tk_tcl/tclsh …
```
> bazel: fix tclsh problems finding library

- etc/DependencyInstaller.sh
When @oharboe updated cmake the aarch64 checksum was not updated to match the new file
> update checksum for cmake for aarch64

- src/gui/src/stub_heatMap.cpp
When compiling OpenROAD without Qt5 installed, or without the GUI, the compilation fails due to some functions being defined in the headers and not in the .cpp
> Add missing stubs GUI definitions

- src/gui/src/clockWidget.cpp
- src/gui/src/clockWidget.h
- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
Adds:
- CTS widget renderer option in display controls to disable or enable the rendering
Fixes:
- segfault in display controls restore when custom controls have been removed from the widget before restore is called
- order the custom controls at the bottom of the display controls option in alphabetical order to avoid options showing up out of order depending on the order the renderers were enabled.
> gui: add CTS renderer controls and fix display options

- src/upf/test/data/mpd_top/mpd_top.upf
- src/upf/test/data/mpd_top/mpd_top_combined.upf
- src/upf/test/write.upfok
- test/upf/mpd_aes.upf
- test/upf_aes.ok
Closes #7363.
Add missing port in upf tests.
> upf: add missing port in upf tests

- src/gpl/src/placerBase.cpp
When using regions, the GPL was creating dummyInstances on top of fixed instances.
Solution:
SiteGrid is used to create dummyInstances only where the grid is set to Empty.
The code was populating the FixedInstances in the grid before processing the regions, so the FixedInst sites could be set to empty if the instance is inside a region.
Making the population of FixedInstances the last thing before creating dummyInstances solved the problem.
Secure CI didn't have any changes.
> gpl: fix dummies

- src/rsz/src/Rebuffer.cc
- src/rsz/src/SplitLoadMove.cc
fix in splitLoadHier to make sure hier/flat nets correctly associated.
Replaced individual connection to hier net with simultaneous flat-net/hier-net call (makes pins on modnet refer to flat net).
> Hier fix in split load

- src/mpl/src/clusterEngine.cpp
- src/mpl/src/clusterEngine.h
1. Create debug table for thresholds. Example:
```
Current cluster: root
Macros: 28
Std Cells: 91483
Level 1  |  Min  |  Max
-----------------------------
Std Cells  |   900 |   5500
Macros  |     1 |      5
```
2. Group clustering debug functions in a section;
3. Improve existent messages.
> mpl: improve debug messages

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
Adds:
- disable controls for pin names when pins are not visible
When pins are visible:
When pins are not visible:
> gui: allow display pairs to disable another row and use for pin names  with pins

- src/dpl/BUILD
Was a spot missed in c0fe03f9b4e?
```
$ bazelisk build -c opt src/dpl/...
ERROR: /home/oyvind/OpenROAD-flow-scripts/tools/OpenROAD/src/dpl/BUILD:111:12: Action src/dpl/swig.cc failed: (Exit 1): swig failed: error executing Action command (from target //src/dpl:swig) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/org_swig/swig -tcl8 -c++ -module dpl -namespace -prefix dpl -Isrc/dpl/src/dpl/src -o bazel-out/k8-opt/bin/src/dpl/swig.cc src/dpl/src/Opendp.i
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/dpl/src/Opendp.i:18: Error: Unable to find 'dbtypes.i'
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.544s, Critical Path: 0.09s
INFO: 10 processes: 10 internal.
ERROR: Build did …
```
> bazel: fix bazelisk build -c opt dpl/src/... error

- src/utl/src/histogram.cpp
Fixes:
- index out of bounds on huge numbers (inf) that cause calculation to be `-1`.
> utl: pin to 0..bins-1

- src/gui/include/gui/heatMap.h
- src/gui/src/heatMap.cpp
Fixes:
- if the block doesn't have an area, the `setupMap` wont do anything which eventually leads to a segfault. This avoids it by stopping the heatmap processing after the setup fails.
>  gui: avoid populating an empty map

- src/drt/src/pa/FlexPA_acc_point.cpp
- src/drt/test/ndr_vias1.ok
- src/drt/test/ndr_vias2.ok
- src/drt/test/ndr_vias3.ok
- src/grt/test/pin_access2.ok
Fixes #7305.
Warning 88 is now a debug print, what it should have been from the start.
> drt: warning 88 is now a debug print message

- .bazelrc
- test/regression.bzl
TL;DR Minimize surprises, build OpenROAD once instead of twice and run all tests:
```
bazelisk test -c opt ...
```
Configs, "exec" is a host configuration, so "k8-opt-exec..." is used to run `regression.bzl` tests and bazel-orfs tests. 
Use "exec" configuration to run tests to avoid building OpenROAD with two configurations "exec" and "target". More info https://github.com/The-OpenROAD-Project/OpenROAD/discussions/7295
```
$ bazelisk config
INFO: Invocation ID: ac5e40a2-0ad6-4926-be42-b559d5cde6e9
Available configurations:
227a4f0a56582136a9c238b40665fb23e8f08f5dae30fa8d28a146d384142d99 k8-opt-exec-ST-d57f47055a04 (exec)
729e8bf41f646cfcb07402580a35d32ec5d99e07d267cdc9c51abe36ab3139a8 k8-opt
7ec72a8f466254106038ebc53574a58b9d30d6afff8d93bf6ebcf819884f6438 k8-opt-exec-ST-d57f47055a04 …
```
> bazel: `bazelisk test -c opt ...` now builds OpenROAD once

- src/drt/src/pa/FlexPA.h
- src/drt/src/pa/FlexPA_acc_point.cpp
Supports #7153.
ISPD, Secure and Calibre CIs safe.
#7210 is failing some CIs, so I'm trying to isolate the problematic part of the code. This PR contains `validateAPForPlanarAccess` and its supporting changes. This change is very minimal and is essentially an effort to separate access points planar validation from via validation.
> drt: validate AP for planar

- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
Some preparation for the work to model blockages as macro clusters constrained by fences.
> mpl: remove redudant blockages' cache and minor refactor

- src/utl/include/utl/algorithms.h
The shuffle function doesn't handle correctly the case where the iterator passed has exactly one element (it tries to create a distribution between 1 and 0, which causes an assertion error in boost)
> Fix the shuffle function

- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovBase.h
This has no functional change, since we do not trigger callback removals yet.
> gpl: reduce counting of new cells after callback removal

- src/gpl/src/placerBase.cpp
Creates dummy instances on top of fixed instances from other regions.
PR #7405 removed the creation of dummy instances on top of fixed instances, but the placerBase can only see instances that belong to its region, so dummy instances still need to be created on top of fixed instances from other regions.
> gpl: dummies ignore fixed instances in other regions

- src/drt/src/db/obj/frVia.h
- src/drt/src/io/io.cpp
- src/drt/src/pa/FlexPA_acc_pattern.cpp
- src/drt/src/pa/FlexPA_acc_point.cpp
- src/drt/src/pa/FlexPA_row_pattern.cpp
- src/drt/test/fixture.cpp
Just quickly did this because it was bothering me a little. Pet peeve PR.
Full Safe
`frVia` can now take an origin point during construction. We keep using `setOrigin()` when it clearly wants to be in construction. The part of the code on `FlexPA_acc_pattern.cpp` touched by this is very verbose for essentially just creating 3 `frVias`. 
I actually think `frVia` should have a constructor that just takes and access point as input but that would require each access point to know the transform from its unique instance which is not the case currently.
> drt: frVia takes origin during construction

- src/odb/include/odb/dbStream.h
Closes #7549.
The Odb reader appends the points stored in ODB to the _dbBlock._die_area polygon.
Changes:
- In dbIStream, clean containers before adding values.
> odb: dbIStream clear containers

- src/rcx/src/extRCmodel.cpp
- src/rcx/src/parse.cpp
Removes calls to system in rcx, this is part one of #7583 (the easy stuff)
> rcx: remove calls to system in favor of using std::filesystem

- src/gpl/src/nesterovPlace.cpp
Use default unscaled overflow for checking if routability or timing-driven should run.
The scaled version should be left for solving overflow with macros (normal distribution scaling).
This solves a segmentation fault occurring with @joaomai in https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Private/detail/secure-mpl-boundary-penalty/4/pipeline/ where we would end up calling the timing-driven iteration during the routability iterations.
> gpl: use deafult unscaled overflow 

- src/dbSta/src/dbNetwork.cc
- src/odb/test/replace_hier_mod3.ok
- src/odb/test/replace_hier_mod4.ok
- src/rsz/src/Rebuffer.cc
- src/rsz/test/clone_hier.ok
- src/rsz/test/clone_hier_out.vok
- src/rsz/test/replace_arith_modules1.ok
- src/rsz/test/split_load_hier_out.vok
This one includes:
(1) the api for IsPower/IsGround and leaves turned on the axiom check that each modNet can have only 1 dbnet.
(2) More fixes in Rebuffer.cc. Filters cases when all loads in same module.
Please note that replace_hier_mod3/mod4 and a couple of other (hierarchical) regressions changed because the IsPower/IsGround(Net*) was previously not properly handling hierarchical nets which led to false inference of a hierarchical net being a ground/power, thereby corrupting the timing results for those cases.
> Turn on axiom check by default in resizer, fixes for IsPower/IsGround

- src/mpl/src/hier_rtlmp.cpp
Closes #7616.
The check that threw an error was on the wrong place. If no valid tilings are found now, it will throw an error instead of segfaulting.
> mpl: error if there are no valid tilings

- src/gpl/src/initialPlace.cpp
- src/gpl/src/placerBase.cpp
If the `-initial` parameter is used with the `global_placement_debug` command in GPL debug mode, create a GIF for the `initialPlacement` procedure executed in `InitialPlace::doBicgstabPlace()`.
> gpl: debug mode, create gif for initial place

- src/ant/src/WireBuilder.cc
- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/grt/src/Net.cpp
- src/grt/src/Net.h
- src/grt/src/fastroute/include/FastRoute.h
- src/grt/src/fastroute/src/FastRoute.cpp
**Problem**
When merging the routing of two nets after buffer removal, the FastRouteCore data regarding edges and nodes of the deleted net was just being deleted, but the congestion information of them wasn't updated. This caused multiple congestion issues during post-GRT incremental repair, since the congestion data of these edges was never updated.
**Solution**
Instead of just deleting the edges and nodes of the deleted nets, append them to the edges and nodes of the preserved net (i.e., the net that will "receive" the routing of the deleted net). This way, the congestion data can be properly updated in future iterations of the global routing tool.
> grt: append nodes and edges from removed nets when merging nets

- src/CMakeLists.txt
- src/rmp/src/CMakeLists.txt
- src/rmp/test/cpp/CMakeLists.txt
1. Fixing two CMakeLists.txt files in src/rmp which use `libabc` unqualified, instead of ${ABC_LIBRARY} (in spite of the fact one of them already links ${ABC_LIBRARY}). This breaks using an ABC_LIBRARY with an absolute path which is supported by the rest of the CMake build scripts.
2. Adding OpenSTA as a STATIC, IMPORTED library when USE_SYSTEM_OPENSTA is set. This in turn allows CUDD_LIB to be added to its INTERFACE_LINK_LIBRARIES property, meaning all of the test binaries linked against OpenSTA will automatically be linked against CUDD_LIB. This is not propagated automatically otherwise and CUDD_LIB would have to be added to every single one of them.
> cmake: improve handling of using system abc/opensta

- src/gui/src/displayControls.cpp
- src/gui/src/displayControls.h
Changes:
- when routing layer color changes, the cut layers do not change with them (this also makes it easier for users to specify the color of a layer they want without having to undo the cut layer change as well).
- change default cut colors
Initial cut colors were chosen by calling `color.lighter()` or `color.darker()` to generate a color that is "related" to the initial metal color, but with some contrast to the metal.
If someone wants to suggest a different color for the specific layer, feel free to do so. My goal here was to get a starting point that I thought was sufficient to begin the discussion.
Examples m1-m10:
> gui: separate routing and cut colors

- src/drt/README.md
- src/drt/include/triton_route/TritonRoute.h
- src/drt/src/TritonRoute.cpp
- src/drt/src/TritonRoute.i
- src/drt/src/TritonRoute.tcl
- src/drt/src/dr/FlexDR.cpp
- src/drt/src/frBaseTypes.h
- detailed_route_debug: add new option, -snapshot_dir, that allows the directory where snapshots are dumped to be changed. if unset the current working directory is used, maintaining the previous behavior.
---
Resolves #6752
> drt: allow changing snapshot directory

- MODULE.bazel
- MODULE.bazel.lock
We had to pin rules_cc to a particular commit to contain a needed fix; the version has been released in the meantime, so simplify that.
> rules_cc: update. Released upstream version contains fix.

- Jenkinsfile
- docker/Dockerfile.bazel
Approx. 10 min TAT for Bazel: ~2-3 minutes for setup and ~7-8 minutes to run tests w/cache enabled.
> ci: run Bazel earlier

- src/gui/src/chartsWidget.cpp
Resolve #7721
The charts-based timing report is accurate in the sense that the we're getting the correct data when asking STA for the slack of a certain group of pins. The real problem seems to be that the negative part of the histogram is flipped.
What we see:
What we should we:
Apparently, some code that takes care of sorting the data when generating the bins was added to the charts, so we don't need to front push when populating the negative buckets as we used to.
Also, if we look at the `report` version of the histogram, we see that the data is logged correctly:
> gui: fix flipped negative buckets

- src/ant/src/WireBuilder.cc
- src/grt/src/GlobalRouter.cpp
std::minmax returns references, so the arguments need to have a valid allocation
> Avoid a stack use after scope

- src/gpl/include/gpl/Replace.h
- src/gpl/src/replace.cpp
- src/gpl/test/density01.ok
This PR addresses issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/6619, where gui debug mode was not stopping for some designs. 
The cause of the issue was the usage of TCL command `place_density_with_lb_addon`, which calls `Replace::getUniformTargetDensity()` (side note: this function is interesting because it constructs gpl objects only to calculate the uniform density). I understand objects will be reconstructed for the "normal" gpl call afterwards, so there is no point printing all initialization log messages for the uniform density query.
The debug issue was avoided by not reseting the replace debug attributes at `Replace::reset()`.
> gpl:l debug avoid issue

- src/gui/include/gui/gui.h
- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
- src/odb/include/odb/geom.h
- src/odb/src/db/geom.cpp
Closes #7833
Adds:
- odb::Polygon merge functions to merge sets of shapes into a set of polygons
- gui::Painter add drawLine to take in a odb::Line.
Changes:
- when detailed routing information is available it will be used for highlighting, when guides are available it will be used, and finally flywires will be used if neither is available (in that order)
Notes:
- This code will draw the outline of the guide boxes and use the centerline of the box to represent the routing with a "flywire" connecting the center line to the iterm or bpins.
- The center line is drawn with two pixels (or 4 seemed like good numbers, 4 is a more clear, but I left it 2 for now), 1 pixel was nearly impossible to see what was going on.
- The "fatness" of the routing in the examples stem from the routing box …
> gui: use guides for net highlighting when available

- src/gui/include/gui/gui.h
- src/gui/src/clockWidget.cpp
- src/gui/src/clockWidget.h
- src/gui/src/gui.cpp
- src/gui/src/gui.i
Adds:
- clock tree depth to the swig interface, this proved useful when working on the guide routing drawing.
Notes:
- there is no tcl interface to this functionality at this time, if we want to add that we can do it in a separate PR.
> gui: expose clock depth to swig interface

- docs/user/Bazel.md
These instructions in [anticipation](https://github.com/The-OpenROAD-Project/OpenROAD/issues/7812#issuecomment-3075718616) of `:openroad` bazel targets to be OpenROAD built with GUI support and `:openroad-cli` to be OpenROAD built with CLI only support.
> bazel: test GUI on github request use-case

- src/gui/src/browserWidget.cpp
- src/gui/src/browserWidget.h
Changes:
- only resizeColumns on first load.
Should solve: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/3342
@jeffng-or please check if this resolves your issue. In my testing it seems to handle correctly.
> gui: call resize once

- src/rsz/src/Rebuffer.cc
- src/rsz/src/Rebuffer.hh
Calculating drive resistance takes about 2.8 hours of the currently 30 hour runtime of our block. It's very expensive to calculate so we should cache it.
> rsz: Caching drive resistance value.

- src/gpl/src/graphics.cpp
- src/gpl/src/initialPlace.cpp
- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovPlace.cpp
- src/gpl/src/placerBase.cpp
- src/gpl/src/placerBase.h
- src/gpl/src/timingBase.cpp
Include the `get` prefix for some member functions of classes in PlacerBase.h. Also rename some internal variables at constructor `PlacerBaseCommon::PlacerBaseCommon()`
> gpl: rename variables for PlacerBase

- src/gui/src/dbDescriptors.cpp
- src/gui/src/dbDescriptors.h
- src/gui/src/mainWindow.cpp
Resolve #7740.
Obs: It looks like the Test Mode is not set for the dbScanChain object so I'm not including it as a descriptor property. Once we set it correctly we can revisit this and add it properly.
> gui: add descriptor for dbScanChain

- src/gui/src/staGuiInterface.cpp
- src/gui/src/staGuiInterface.h
The Charts View was always displaying the setup slack histogram when filtering by path_group.
Changes:
- Sends the correct argument to findPathGroup
- sta::MinMax::max() when displaying setup slack
- sta::MinMax::min() when displaying hold slack
> gui: fix the charts view hold with path_group filter

- src/utl/src/decode.cpp
This is a weird one, but it seems like on ARM machines something about how TCL runs its arena allocator triggers false positive memory leak violations on internal presubmits. Not sure what the exact reason is, but the TCL docs say the old Tcl_Eval function is not preferred anyways.
It seems to only be triggered for large TCL scripts as none of the other Tcl_Eval functions trigger it. Would appreciate a merge here since it is identical functionality.
> utl: Fixes memory leak false positive with Google heap checker

- src/gui/src/chartsWidget.cpp
This button is useful when issuing interactive set_false_path commands or other commands that affect the timing reporting.
Normally when using dropdowns in Endpoint Slack Histogram, then there's no need to click this button. Unsure what the what 'Refresh filters' is referring to or what the use case is other than to refresh the histogram based on out of bound(not through GUI buttons) changes to the timing model.
> histogram: rename 'Refresh filters' to 'Update'

- etc/DependencyInstaller.sh
Hi there, thanks for this awesome project. Just managed to build from source. :)
This PR addresses two issues found when trying to build OpenROAD via the OpenROAD flow scripts repo on AlmaLinux 9. (binary-compatible with RHEL9 & RockyLinux 9). AlmaLinux 9 gets lots of use at universities here in Germany, and is used now by scientific institutions like CERN, so I guess it's worth adding this.
The first issues, was basically that a case for AlmaLinux when checking the `os-release` variable didn't exist in the `etc/DependencyInstaller.sh`. So I simply added a match:
```bash
elif [[ "${os}" == "AlmaLinux" ]]; then
rhelVersion=$(rpm -q --queryformat '%{VERSION}' almalinux-release | cut -d. -f1)
```
The second change I'm a bit more unsure of, but essentially the docs recommend the higher-level …
> Fix issue with `openroad_deps_prefixes.txt` permissions & add case for AlmaLinux 9

- src/rmp/src/CMakeLists.txt
- src/rmp/src/Restructure.cpp
- src/rmp/src/abc_library_factory.cpp
- src/rmp/src/abc_library_factory.h
- src/rmp/src/resynthesis_strategy.h
- src/rmp/src/zero_slack_strategy.cpp
- src/rmp/src/zero_slack_strategy.h
- src/rmp/test/BUILD
- src/rmp/test/CMakeLists.txt
- src/rmp/test/aes_donttouch_nangate45.ok
- src/rmp/test/aes_donttouch_nangate45.tcl
- src/rmp/test/aes_dontuse_nangate45.ok
- src/rmp/test/aes_dontuse_nangate45.tcl
- src/rmp/test/cpp/TestAbc.cc
- src/rmp/test/memory_nangate45.ok
- src/rmp/test/memory_nangate45.sdc
- src/rmp/test/memory_nangate45.tcl
- src/rmp/test/memory_nangate45.v
This fixes the following issues:
- Memories: IsCombinational didn't check for memories, but memories can not be used for resynthesis
- set_dont_use: Resynthesis did not check if cells are marked as dont-use
- set_dont_touch: Resynthesis did not check if instances/pins/nets are marked as dont-toch
Each feature has its own testcase.
> Resynthesis: Fix handling of memories and properly honor set_dont_touch and set_dont_use attributes

- src/mpl/src/SACoreSoftMacro.cpp
- src/mpl/src/SACoreSoftMacro.h
- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/hier_rtlmp.h
- src/mpl/src/util.h
No changes in functionality.
The idea is to make the code less bug prone for adding/removing penalties.
> mpl: group soft annealing weights in a struct

- src/mpl/src/SACoreSoftMacro.cpp
- src/mpl/src/SACoreSoftMacro.h
- src/mpl/src/shapes.h
This new function will be used in the implementation for supporting fixed macros in MPL.
> mpl: create and use function for computing overlap shape in sa

- src/mpl/src/hier_rtlmp.cpp
Needed for partial automated macro placement support.
The idea is that the fixed macros will also have to be considered at the root-level annealing we performing coarse shaping. (the root-level annealing prevents moving on to cluster placement with a set of macros that we can't fit in the core area).
> mpl: consider root cluster location in coarse shaping

- test/orfs/mock-array/BUILD
No warnings to be seen below.
```
$ bazelisk build test/orfs/mock-array:simulator
[deleted]
INFO: From [Verilator] Compiling @@//test/orfs/mock-array:array_verilator:
- V e r i l a t i o n   R e p o r t: Verilator v5.034 rev v5.034
- Verilator: Built from 13.172 MB sources in 163 modules, into 59.041 MB in 61 C++ files needing 0.000 MB
- Verilator: Walltime 23.065 s (elab=1.551, cvt=19.385, bld=0.000); cpu 21.316 s on 1 threads; alloced 464.305 MB
INFO: Found 1 target...
[deleted]
```
> power: -hier fixed warnings in .v with verilator

- src/grt/src/fastroute/include/Graph2D.h
- src/grt/src/fastroute/src/graph2d.cpp
This PR fixes a problem that can occurs when we have a NDR net with different edge cost for each metal layer.
During 2D phases, we need to check if there is 3D capacity available in a single layer considering the NDR net layer edge cost.
> grt: fix checking NDR net cost per layer

- src/grt/include/grt/GlobalRouter.h
- src/grt/src/GlobalRouter.cpp
- src/odb/include/odb/dbBlockCallBackObj.h
- src/odb/src/db/dbITerm.cpp
This new ODB callback will be necessary for incremental pin access.
Calling pin access in each iteration of incremental GRT might be prohibitive regarding runtime. This PR introduces a new callback that will track instance terms that had their access points modified by PA, and add their nets to the list of nets to reroute. This way, we can run incremental iterations and only update the access points at the end of it, leaving GRT to reroute only the nets with modified APs.
> grt/odb: add db callback for access point update

- src/mpl/src/hier_rtlmp.cpp
Small partial revert of #8216 .
Graphics require single thread to run properly. Not running single thread causes problems when attempting to `pause()` the GUI - it won't pause.
> mpl: use single thread when running with graphics

- src/gpl/README.md
To match changes in 24688077181.
> gpl: Update doc with current code for -timing_driven_net_reweight_overflow.

- src/odb/include/odb/dbId.h
Not only improves it readability, it also allow the compiler to see through that this is not an expensive object to copy.
> dbId: use default constructors and RAII

- src/cgt/include/cgt/ClockGating.h
- src/cgt/src/ClockGating.cpp
- src/cgt/test/aes_nangate45.ok
- src/cgt/test/countdown_asap7.ok
- src/cgt/test/ibex_sky130hd.ok
- src/cut/include/cut/logic_cut.h
- src/cut/src/blif.cpp
- src/cut/src/logic_extractor.cpp
- src/cut/test/cpp/TestAbc.cc
Fixes memory leak (and removes redundant calls to ABC) and resolves Coverity lints.
> cgt: cut: Cleanup/lint fixes

- src/mpl/src/clusterEngine.cpp
- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/object.cpp
- src/mpl/src/object.h
Found this bug when working on #8343.
The only reason nothing blows up nowadays is because, when we use the clusters' connection maps, we don't retrieve the `Cluster*`. Trying to do that with `std::map::at()` results in an invalid map access without the changes here.
Also some subtle renaming and code improvements.
> mpl: update connections after merging clusters

- src/gpl/src/nesterovBase.cpp
- src/gpl/src/nesterovBase.h
This PR includes a new check for gpl detecting if a divergence has occurred.
As reported by @joaomai at branch https://github.com/The-OpenROAD-Project-private/OpenROAD/tree/mpl-new-blockages with nangate45/black_parrot there was an undetected divergence happening in gpl. The newly included check detects such divergence, and reverts to a valid solution, also providing a valid legalized placement and routable design.
make gui_place:
make gui_final:
I triggered a secure-CI at https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Private/detail/secure-gpl-improve-divergence-detection/2/pipeline and should be an no-op on current master version.
I noticed the divergence happened after the last timing-driven iteration, where RSZ removed highly inflated instances.
> gpl: improve divergence detction

- src/dst/BUILD
Unless other implementations needed, just use it as default.
> Posix-threads are not specific to Linux.

- src/cts/BUILD
- src/odb/BUILD
There is only really one library that is providing an implementation and the associated headers.
> Don't export the same header by multiple libraries.

- src/mpl/src/clusterEngine.cpp
- src/mpl/src/clusterEngine.h
- src/mpl/src/object.cpp
- src/mpl/src/object.h
In order to merge #8375, we need to avoid adding redundant connections between clusters e.g., for a given cluster A having a connection with A itself. That might happen today due to how we create connections between clusters.
These refactoring changes are to make it easier to avoid those connections. I'll have a subsequent PR for that as I want to see if won't affect results.
> mpl: create and use method for connecting clusters

- src/dpl/src/util/symmetry.h
- src/dst/src/LoadBalancer.h
- src/odb/include/odb/db.h
- src/odb/include/odb/dbTypes.h
- src/odb/include/odb/gdsUtil.h
- src/odb/include/odb/isotropy.h
- src/odb/src/lef/clef/lefrReader.h
- src/odb/src/lef/lef/lefrReader.hpp
Adressing `clang-diagnostic-unused-const-variable` clang-tidy warning.
> Use `inline constexpr` uniformly for constants in headers.

- test/orfs/mock-array/BUILD
Should have no effect. Only thing is that yosys is sensitive to initial conditions, so even adding whitespace can result in slightly different synthesis results...
> mock-array: less noisy .v files generated

- src/mpl/src/hier_rtlmp.cpp
- src/mpl/src/object.h
> mpl: remove unused member variables in BundledNet object

- src/cut/src/CMakeLists.txt
- src/cut/test/cpp/CMakeLists.txt
- src/rmp/src/annealing_strategy.h
- explicitly cast rmp::AnnealingStrategy::random_'s seed to 32-bit
`rmp::AnnealingStrategy::random_` is `std::mt19937` which is 32-bit: https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine.html
This in turn causes the constructor for `AnnealingStrategy` to be ill-formed according to the C++17 standard:
> List-initialization of an object or reference of type T is defined as follows:
> ...
> (3.7) Otherwise, if T is a class type, constructors are considered. The applicable constructors are enumerated and the best one is chosen through overload resolution (16.3, 16.3.1.7). If a narrowing conversion (see below) is required to convert any of the arguments, the program is ill-formed.
As the seed is `uint64_t` and `mt19937` uses `uint32_t`, this is a narrowing conversion that …
> rmp/cut: various build fixes

- default.nix
Followup to #8295. This fixes the nix build as tested with `nix build '.?submodules=1#'`
> Add yaml-cpp to nix
