src/pdngen/src/PdnGen.tcl

Fix for Austin's issue running integrated pdngen.

fix missing odb:: on db destroy command. Test will come shortly.

---

src/dbSta/dbNetwork.cc
test/regression_vars.tcl
test/sdc_get1.ok
test/sdc_get1.tcl

Austin bug odb_testcase3
get_ports -of_objects net

get_ports -of_objects net

---

Dockerfile

This avoids invalid user permissions when cloning

Use a newer version of git

---

src/OpenRoad.i

*** Please do not merge before https://github.com/The-OpenROAD-Project/OpenROAD/pull/176 ***

[ioPlacer] Fix crash when design has no tracks

---

src/ICeWall/src/ICeWall.tcl
src/pdngen/src/PdnGen.tcl
src/pdngen/test/soc_bsg_black_parrot_nangate45.ok
src/pdngen/test/tinyRocket.ok

Fixed a problem in pdngen where it was modifying connections to VDDIO and VSSIO nets because there was some greedy pattern matching going on.
Fixed an issue highlighted by Austin wrt IO filler cells being missing on left/right hand sides of the die.
Report an error when expected P/G pins not found on a macro

Flow test updates

---

src/ICeWall/src/ICeWall.tcl

Use instance BBOX to determine box for filler cell addition

---

src/tapcell/src/tapcell.tcl

- Fix min spacing between tapcell and endcaps
- FIx orientation of cells around macros

Tapcell fixes

---

src/tapcell/src/tapcell.tcl

Simple change to correct endcap types for top and bottom edges. @eder-matheus please review.

[tapcell] Correct endcap cells on top and bottom of core area

---

src/resizer/include/resizer/SteinerTree.hh
src/resizer/src/Resizer.cc
src/resizer/src/SteinerTree.cc

I don't want to pull the code as is, but I want Cherry to review and make suggestions on how to integrate this (if at all).  I don't know the debug controls from OpenSTA so please suggest the right way to do the hook in Resizer.cc.

Steiner svg dump

---

src/tapcell/src/tapcell.tcl

The commits in this pull request fix all tapcell violations in bp_single when using auto macro placement

Fix tapcell violations

---

src/pdngen/src/PdnGen.tcl
src/pdngen/test/soc_bsg_black_parrot_nangate45.ok
src/pdngen/test/soc_bsg_black_parrot_nangate45.pad_offset.ok
src/pdngen/test/soc_bsg_black_parrot_nangate45/PDN.cfg
src/pdngen/test/soc_bsg_black_parrot_nangate45/PDN.pad_offset.cfg

Fix bug that left macros unconnected when other non-ram macros were being used

RAMs left disconnected, as no vias were being added over RAMs

---

src/TritonCTS/src/HTreeBuilder.cpp

distance_between_buffers and branching_point_buffers_distance were in DBU.

[TritonCTS] Change distance units for new options to micron

---

src/pdngen/src/PdnGen.tcl

Need to adjust halo in Y direction to ensure that vertical straps will overlap the full width of the stdcell rail

Adjust the halos around macros to ensure proper PDN connections

---

src/antennachecker/README.md
src/antennachecker/include/antennachecker/AntennaChecker.hh
src/antennachecker/src/AntennaChecker.cc
src/antennachecker/src/AntennaChecker.i
src/antennachecker/src/AntennaChecker.tcl
src/antennachecker/test/results/sw130_random.log
src/antennachecker/test/sw130_random.ok
src/antennachecker/test/sw130_random.tcl

@tspyrou can you please review.

Arc updates

---

src/TritonMacroPlace/README.md
src/TritonMacroPlace/include/tritonmp/MakeTritonMp.h
src/TritonMacroPlace/include/tritonmp/TritonMacroPlace.h
src/TritonMacroPlace/src/MakeTritonMp.cpp
src/TritonMacroPlace/src/TritonMacroPlace.cpp
src/TritonMacroPlace/src/circuit.cpp
src/TritonMacroPlace/src/circuit.h
src/TritonMacroPlace/src/graph.cpp
src/TritonMacroPlace/src/graph.h
src/TritonMacroPlace/src/hashUtil.cpp
src/TritonMacroPlace/src/hashUtil.h
src/TritonMacroPlace/src/logger.cpp
src/TritonMacroPlace/src/logger.h
src/TritonMacroPlace/src/macro.cpp
src/TritonMacroPlace/src/macro.h
src/TritonMacroPlace/src/macroPlace.cpp
src/TritonMacroPlace/src/partition.cpp
src/TritonMacroPlace/src/partition.h

I've inserted BSD-3-clause license headers in TritonMacroPlace.

[OR-460] Insert headers in TritonMacroPlace 

---

src/replace/README.md
src/replace/include/replace/MakeReplace.h
src/replace/include/replace/Replace.h
src/replace/src/MakeReplace.cpp
src/replace/src/fft.cpp
src/replace/src/fft.h
src/replace/src/fftsg.cpp
src/replace/src/fftsg2d.cpp
src/replace/src/initialPlace.cpp
src/replace/src/initialPlace.h
src/replace/src/logger.cpp
src/replace/src/logger.h
src/replace/src/nesterovBase.cpp
src/replace/src/nesterovBase.h
src/replace/src/nesterovPlace.cpp
src/replace/src/nesterovPlace.h
src/replace/src/placerBase.cpp
src/replace/src/placerBase.h
src/replace/src/plot.cpp
src/replace/src/plot.h
src/replace/src/point.cpp
src/replace/src/point.h
src/replace/src/replace.cpp
src/replace/src/routeBase.cpp
src/replace/src/routeBase.h

I've inserted BSD-3-clause license headers in RePlAce.

[OR-460] Insert headers in RePlAce

---

src/FastRoute/src/DBWrapper.cpp
src/FastRoute/src/FastRouteKernel.cpp
src/FastRoute/src/Pin.h
src/gui/include/gui/gui.h
src/gui/src/displayControls.cpp
src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h
src/gui/src/mainWindow.cpp
src/gui/src/mainWindow.h
src/gui/src/search.cpp
src/gui/src/search.h

Fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/454

handle bidir pins in FR

---

README.md

https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/opendp/src/CheckPlacement.cpp#L94

[Doc] Correct return value of check_placement

---

src/TritonRoute/src/dr/FlexGridGraph_maze.cpp

Recalculating the edge value represents 2% of the total runtime of
tritonroute.

Cache the values of EdgeLength.

---

src/TritonRoute/src/dr/FlexGridGraph.h

getIdx is one of the hottest functions in the detailed router.
This change improve the speed of the detailed router by 2%.

drt: Improves the speed of getIdx.

---

docs/user/UserGuide.rst

tapcell examples are at tap/etc/scripts

correct tapcell examples directory

---

src/tap/src/tapcell.tcl

This reverts commit d0138b59ff66341e82852af8d0770fc17d846b3d.
Fixes the secure-CI failure.

Revert "tap: update check_if_filled"

---

docs/contrib/DatabaseMath.rst

This is just a small inconsistency that I have noticed.

docs correction: 2 billion units = 2 million microns

---

src/ICeWall/src/ICeWall.tcl
src/OpenDB/src/db/OpenDB.tcl
src/TritonRoute/src/TritonRoute.tcl

closes [OR-999](https://openroad.atlassian.net/browse/OR-999)

Replace ord::error with utl::error

---

src/pdr/src/graph.cpp
src/pdr/src/node.cpp
src/pdr/src/node.h
src/pdr/test/pd2.tcl

pdr debug msg cleanup

---

src/rsz/messages.txt
src/rsz/src/EstimateWireParasitics.cc

estimate_parasitics do not seg fault if a net has no driver

rsz est rc seg fault if no driver

---

src/OpenDB/src/lefin/boostParser.h
src/OpenDB/src/lefin/lefLayerPropParser.h
src/OpenDB/src/lefin/lefTechLayerCornerSpacingParser.cpp
src/OpenDB/src/lefin/lefTechLayerCutClassParser.cpp
src/OpenDB/src/lefin/lefTechLayerCutEnclosureParser.cpp
src/OpenDB/src/lefin/lefTechLayerCutSpacingParser.cpp
src/OpenDB/src/lefin/lefTechLayerCutSpacingTableParser.cpp
src/OpenDB/src/lefin/lefTechLayerEolExtensionParser.cpp
src/OpenDB/src/lefin/lefTechLayerEolKeepOutRuleParser.cpp
src/OpenDB/src/lefin/lefTechLayerMinStepParser.cpp
src/OpenDB/src/lefin/lefTechLayerRectOnlyParser.cpp
src/OpenDB/src/lefin/lefTechLayerRightWayOnGridOnlyParser.cpp
src/OpenDB/src/lefin/lefTechLayerSpacingEolParser.cpp
src/OpenDB/src/lefin/lefTechLayerSpacingTablePrlParser.cpp
src/OpenDB/src/lefin/lefTechLayerTypeParser.cpp
src/TritonRoute/src/gc/FlexGC_main.cpp

Add copyrights to files:
* /OpenDB/src/lefin/lefTechLayerTypeParser.cpp
* /OpenDB/src/lefin/lefTechLayerCutSpacingParser.cpp
* /OpenDB/src/lefin/lefTechLayerSpacingEolParser.cpp
* /OpenDB/src/lefin/boostParser.h
* /OpenDB/src/lefin/lefTechLayerEolKeepOutRuleParser.cpp
* /OpenDB/src/lefin/lefTechLayerRightWayOnGridOnlyParser.cpp
* /OpenDB/src/lefin/lefLayerPropParser.h
* /OpenDB/src/lefin/lefTechLayerCutClassParser.cpp
* /OpenDB/src/lefin/lefTechLayerCornerSpacingParser.cpp
* /OpenDB/src/lefin/lefTechLayerRectOnlyParser.cpp
* /OpenDB/src/lefin/lefTechLayerCutSpacingTableParser.cpp
* /OpenDB/src/lefin/lefTechLayerSpacingTablePrlParser.cpp
* /OpenDB/src/lefin/lefTechLayerMinStepParser.cpp
* /OpenDB/src/lefin/lefTechLayerCutEnclosureParser.cpp
* …

Applying small required fixes

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/src/maze.cpp
src/grt/src/fastroute/src/utility.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/774

grt: fix crash

---

src/grt/src/fastroute/src/FastRoute.cpp

grt: fix uninitialized class member

---

src/grt/src/fastroute/src/FastRoute.cpp

Fix [OR-1043](https://openroad.atlassian.net/browse/OR-1043)

grt: fix uninitialized variable

---

src/grt/src/fastroute/src/RSMT.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/575

grt: fix undefined behavior in coeffADJ

---

src/rsz/src/Resizer.cc

rsz respect set_routing_alpha

---

src/ppl/src/IOPlacer.cpp

ppl: add check for manufacturing grid

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp

grt: fix constructor and destructor

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/src/fastroute/src/route.cpp

grt: fix coverity issues

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/Resizer.cc
src/rsz/test/repair_wire8.tcl

OR-1072 repair_design missing target slews missing with multiple corners 

rsz missing target slews with multiple corners OR-1072

---

src/stt/src/pdr/src/pdrev.cpp
src/stt/test/pd1.ok
src/stt/test/pd1.tcl

pdr 2 duplicate points

---

src/rsz/src/Resizer.cc
src/stt/src/pdr/src/pdrev.cpp
src/stt/test/pd1.ok
src/stt/test/pd1.tcl

Rsz no special

---

src/stt/include/stt/flute.h

stt: fix structs

---

docs/contrib/Logger.rst

Doc changes based on messages review.
@maliberty  Please edit as required.
reference to ord namespace is not clear- needs more description. Please let me know if the examples shown are sufficient or if we need to further clarify.

Logger documentation changes- added guidelines for messaging and overall cleanup

---

etc/DependencyInstaller.sh

docker: add readline as a dev dependency

---

src/TritonRoute/src/TritonRoute.tcl

[DRT] Cap droute_end_iter at 64

---

src/rsz/src/Resizer.cc

repair_clock_net ignore special nets

repair_clock_net ignore special nets

---

src/grt/src/GlobalRouter.tcl
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/src/fastroute/src/RSMT.cpp
src/grt/src/fastroute/src/maze.cpp
src/grt/src/fastroute/src/utility.cpp
src/grt/test/no_tracks.ok

Fixes all grt errors reported by valgrind.

grt: minor fixes

---

README.md
src/cts/test/max_cap.tcl
src/rsz/include/rsz/Resizer.hh
src/rsz/include/rsz/SteinerTree.hh
src/rsz/src/EstimateWireParasitics.cc
src/rsz/src/Rebuffer.cc
src/rsz/src/Resizer.cc
src/rsz/src/SteinerTree.cc
src/rsz/test/repair_clk_nets1.ok
src/stt/src/pdr/src/node.cpp
test/flow.tcl

estimate_parasitics ignore ideal clocks
OR-1080 Huge memory consumption (>200GB) on estimate_parasitics -placement, MegaBoomX1

Rsz no est ideal clks

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp

grt: plot actual route guides with highlight_net_route

---

src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.cpp
src/grt/src/Grid.h
src/grt/test/clock_route.ok
src/grt/test/congestion1.ok
src/grt/test/congestion2.ok
src/grt/test/congestion3.ok
src/grt/test/congestion4.ok
src/grt/test/congestion5.ok
src/grt/test/congestion6.ok
src/grt/test/est_rc1.ok
src/grt/test/est_rc2.ok
src/grt/test/ndr_1w_3s.ok
src/grt/test/ndr_2w_3s.ok
src/grt/test/pd1.ok
src/grt/test/pd2.ok
src/grt/test/pd4.ok
src/grt/test/repair_antennas1.ok
src/grt/test/repair_antennas2.ok
src/grt/test/repair_antennas3.ok
src/grt/test/repair_antennas_error2.ok
src/rsz/test/repair_hold10.ok

grt: check for min-max layers before adding obstructions to grid

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.cpp
src/grt/src/Grid.h
src/grt/src/RoutingLayer.h
src/odb/src/db/dbTechLayer.cpp
src/odb/test/lef_data_access.tcl

This reverts commit 6ebae943f400af27fe33c4fa75bbe1e3a856bdbb, reversing
changes made to d8dadacd23a0c162577eab9d075b4f3119e80e0d.

Revert "Merge pull request #968 from eder-matheus/grt_update"

---

src/drt/src/io/io.cpp

fixes #1036

---

docs/user/BuildLocally.md
docs/user/GettingStarted.md
etc/DependencyInstaller.sh

- Check if dependency is already installed.
- Add a note in the documentation about compiler not being in the path in Centos7 by default

Dependency Installer check and compiler in path note

---

src/odb/README.md

Update odb python interface docs

---

CMakeLists.txt
src/Main.cc

Avoid conflicting information about version:
Before:
-- OpenROAD version: 1
-- OpenROAD git describe: v2.0-915-g728fc70
After:
-- OpenROAD version: v2.0-915-g728fc70

Use git describe as the version

---

jenkins/Jenkinsfile.nightly

Nightly build run with detached git HEAD.

Fix email report.

---

docs/user/GettingStarted.md

Avoid [this case](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/150#issuecomment-918136855).

Move warning to the top of section

---

src/rmp/src/Restructure.cpp

Signed-off-by: Sanjiv Mathur <mathur.sanjiv@gmail.com>

Remove compiler warning for double brackets

---

src/dpl/src/OptMirror.cpp
src/dpl/test/mirror3.ok
src/dpl/test/mirror3.tcl
src/dpl/test/regression_tests.tcl

dpl optimize_mirroring w/o detailed placement

---

src/ppl/README.md

PPL add doc note on f2f usage

---

src/dbSta/src/dbReadVerilog.cc

sta bullet proof against missing liberty OR-1103

---

src/grt/src/AntennaRepair.cpp

grt: fix leak in AntennaRepair

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/test/congestion3.def
src/grt/test/invalid_pin_placement.ok

grt: get pin layers respecting layer range

---

test/aes_nangate45.metrics
test/aes_nangate45.metrics_limits

update aes_nangate45 metrics

---

src/rmp/src/Restructure.cpp

Don’t need to pass unconstrained endpoints for timing mode
Inverted check to skip constant removal in run function
Check for Macro in Restructure::getBlob
Signed-off-by: Sanjiv Mathur <mathur.sanjiv@gmail.com>

Fixes for minor issues from code review

---

src/rmp/src/blif.cpp
src/rmp/test/blif_reader.def.ok
src/rmp/test/blif_reader_const.def.ok
src/rmp/test/blif_reader_sequential.def.ok

Signed-off-by: Sanjiv Mathur <mathur.sanjiv@gmail.com>

Fix name construction.

---

src/drt/src/io/io.cpp

RIGHTWAYONGRIDONLY when masks > 1

---

test/aes_sky130hd.metrics_limits
test/aes_sky130hs.metrics_limits

flow rm metrics_limits merge turds

---

src/stt/include/stt/flute.h
src/stt/src/MakeSteinerTreeBuilder.cpp
src/stt/src/flt/flute.cpp

stt only init flute LUTs if it is used

---

.github/workflows/github-actions-macos.yml

Add macOS action to build OR

---

etc/DependencyInstaller.sh

Generating new Docker images now -- will wait to merge, but should be ok to review since this is a small change.
Public CI and Private CI have already been updated.

Add qt plugin to save webp images

---

src/rsz/src/Resizer.cc
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_design1.ok
src/rsz/test/resize_slack3.ok
src/rsz/test/resize_slack3.tcl
test/Nangate45/fakeram45_64x7.lib

rsz td gpl with no wire rc

---

src/rsz/src/Resizer.cc
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_hold12.ok
src/rsz/test/repair_hold12.tcl
src/rsz/test/repair_hold2.ok
src/rsz/test/repair_hold8.ok

rsz repair hold with no setup constraint

---

src/dbSta/include/db_sta/dbNetwork.hh
src/dbSta/include/db_sta/dbSta.hh
src/dbSta/src/dbNetwork.cc
src/dbSta/src/dbSta.cc

dbSta init

---

src/ppl/README.md
src/ppl/src/IOPlacer.tcl
src/ppl/test/pin_extension.defok
src/ppl/test/pin_extension.ok
src/ppl/test/pin_extension.tcl
src/ppl/test/pin_length.defok
src/ppl/test/pin_length.ok
src/ppl/test/pin_length.tcl
src/ppl/test/pin_thick_multiplier.defok
src/ppl/test/pin_thick_multiplier.ok
src/ppl/test/pin_thick_multiplier.tcl
src/ppl/test/regression_tests.tcl

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/1326

ppl: more Tcl commands

---

src/ppl/README.md

ppl: add units to readme

---

src/grt/include/grt/GlobalRouter.h

grt: sort db_net_map_ by net id

---

src/rsz/src/Resizer.cc
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_slew12.def
src/rsz/test/repair_slew12.ok
src/rsz/test/repair_slew12.tcl

OR-1156 rsz: segfault in repair_design

---

cmake/FindTCL.cmake

Signed-off-by: James Cherry <cherry@CerezoM1Book.local>

tcl homebrew search path

---

src/grt/src/GlobalRouter.cpp

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/1385

grt: delete db_net in routes_

---

src/cts/include/cts/TritonCTS.h
src/cts/src/CMakeLists.txt
src/cts/src/Clock.cpp
src/cts/src/Clock.h
src/cts/src/Clustering.cpp
src/cts/src/Clustering.h
src/cts/src/CtsOptions.h
src/cts/src/HTreeBuilder.cpp
src/cts/src/HTreeBuilder.h
src/cts/src/LevelBalancer.cpp
src/cts/src/LevelBalancer.h
src/cts/src/MakeTritoncts.cpp
src/cts/src/PostCtsOpt.cpp
src/cts/src/PostCtsOpt.h
src/cts/src/SinkClustering.cpp
src/cts/src/SinkClustering.h
src/cts/src/TechChar.cpp
src/cts/src/TechChar.h
src/cts/src/TreeBuilder.h
src/cts/src/TritonCTS.cpp

cts: clang-format

---

etc/DependencyInstaller.sh

Updating boost version to 1.76

---

CMakeLists.txt

Signed-off-by: Matt Liberty <mliberty@eng.ucsd.edu>

disable LTO due to Qt issues

---

src/cts/src/TritonCTS.cpp
src/cts/test/balance_levels.ok
src/cts/test/check_buffers.ok
src/cts/test/check_wire_rc_cts.ok
src/cts/test/find_clock.ok
src/cts/test/max_cap.ok
src/cts/test/post_cts_opt.ok
src/cts/test/simple_test.ok
src/cts/test/simple_test_clustered.ok
src/cts/test/simple_test_clustered_max_cap.ok

cts: fix double in log file + update unit tests

---

src/ppl/src/IOPlacer.tcl

ppl: turn wrong layer direction into an error

---

docs/contrib/PlatformBringUp.md
docs/toc.yml
docs/user/FlowVariables.md
docs/user/GettingStarted.md

Signed-off-by: vijayank88 <paruthi143@gmail.com>
OpenROAD flow public platforms environment variables document contributed.

OpenROAD flow variables document

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp

grt mv congestion error so db congestion gets updated

---

src/drt/src/io/io.cpp

drt: fix bterms pins mismatch

---

include/ord/OpenRoad.hh
src/OpenRoad.cc
src/dpl/include/dpl/Opendp.h
src/dpl/src/Graphics.cpp
src/dpl/src/Opendp.cpp
src/dpl/src/OptMirror.cpp
src/dpl/src/Place.cpp
src/dpl/src/dbToOpendp.cpp
src/grt/include/grt/GRoute.h
src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/MakeWireParasitics.cpp
src/grt/test/tracks2.ok
src/ifp/src/InitFloorplan.cc
src/odb/include/odb/db.h
src/odb/include/odb/geom.h
src/odb/src/db/dbNet.cpp
src/rsz/src/Resizer.cc

This reverts commit efe37844ddca350c4a44eea93bf4c9ca882d6777, reversing
changes made to cd7a2f497c69a77dc056e8b966daa5de7d211a58.
Private CI is failing with segv on grt code during gpl for sky90 and
tsmc65lp platforms.

Revert "Merge pull request #1532 from jjcherry56/grt_cleanup"

---

src/grt/src/GlobalRouter.cpp
src/grt/src/RoutingTracks.h

grt coverity

---

Jenkinsfile
etc/Build.sh
jenkins/Jenkinsfile.nightly
src/CMakeLists.txt

Change default to allow warnings for regular builds

CI compile with -Werror

---

src/drt/src/dr/FlexDR_init.cpp

drt: proper error msg

---

src/rsz/src/Rebuffer.cc

rsz or1264 round 2

---

src/drt/src/dr/FlexDR_init.cpp

Passed tests:
- [ISPD](https://jenkins.openroad.tools/job/OpenROAD-ISPD-Private/job/TR_drt-boundary/)
- [SECURE CI](https://github.com/The-OpenROAD-Project-private/OpenROAD-flow-scripts/tree/secure-drt-boundary)

fixes The-OpenROAD-Project/OpenROAD#1577

---

src/grt/src/GlobalRouter.tcl

grt: print correct cmd name

---

etc/CodeCoverage.sh

Fix quotation again

---

src/grt/src/GlobalRouter.cpp

grt: fix coverity issue

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i
src/grt/src/GlobalRouter.tcl
src/grt/test/repair_antennas2.ok
src/grt/test/repair_antennas3.ok

Fix https://github.com/The-OpenROAD-Project/OpenLane/issues/929

grt: fix loops on local connections for repair_antennas

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i
src/grt/src/MakeWireParasitics.cpp
src/grt/src/MakeWireParasitics.h

grt route_layer_lengths(net) for layer cap correlation script

---

src/drt/src/io/io.cpp

fixes The-OpenROAD-Project/OpenLane#928

---

src/pdn/src/PdnGen.tcl

Fix typo index -> lindex

---

src/rsz/src/Resizer.cc

or958 report_clock_skew with combinational loops

---

src/drt/src/io/io.cpp

[OR-1351](https://openroad.atlassian.net/browse/OR-1351)

drt: split 265 warnings

---

src/grt/src/AntennaRepair.cpp
src/grt/src/AntennaRepair.h

grt: check if diodes are placed out of rows

---

src/gpl/src/initialPlace.cpp
src/gpl/test/incremental02.ok
src/gpl/test/simple01-td-tune.ok
src/gpl/test/simple01-td.ok
src/gpl/test/simple03.ok
src/gpl/test/simple04.ok
src/gpl/test/simple06.ok
src/gpl/test/simple07.ok
src/gpl/test/simple08.ok
src/mpl/test/gcd_mem1_01.ok
src/mpl/test/gcd_mem1_02.ok
src/mpl/test/gcd_mem1_03.ok
src/mpl/test/gcd_mem3_01.ok
src/mpl/test/gcd_mem3_02.ok
src/mpl/test/gcd_mem3_03.ok
src/mpl/test/gcd_mem5_01.ok
src/mpl/test/level3_02.ok

Use residual instead of error

---

src/gpl/test/large01.ok
src/gpl/test/large02.ok
src/gpl/test/medium01.ok
src/gpl/test/medium02.ok
src/gpl/test/medium03.ok
src/gpl/test/medium04.ok
src/gpl/test/medium05.ok
src/gpl/test/medium06.ok

Fix ok files for gpl large/medium tests

---

src/dbSta/src/dbNetwork.cc

DbInstanceNetIterator init coverity warning

---

src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/TritonRoute.tcl
src/drt/src/frDesign.h
src/drt/src/io/io_parser_helper.cpp

closes [OR-1350](https://openroad.atlassian.net/browse/OR-1350)

drt: detailed_route_set_default_via

---

src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/maze.cpp
src/grt/src/fastroute/src/utility.cpp

Signed-off-by: luis201420 <tauro_luisito_20@hotmail.com>

grt: Fix bug in mazeMSMD function

---

docs/contrib/CI.md
docs/toc.yml

Add docs about CI.

---

src/rsz/src/Resizer.cc

rsz handle liberty scalar slew

---

src/rsz/src/Resizer.cc
src/rsz/test/repair_slew8.ok
test/jpeg_sky130hd.metrics_limits

rsz microwatt repair_design

---

src/rsz/src/Resizer.cc
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_setup5.def
src/rsz/test/repair_setup5.ok
src/rsz/test/repair_setup5.tcl

issue1856 repair_timing -setup for set_max_delay on comb path

---

etc/deltaDebug.py
src/odb/src/db/dbDatabase.h
src/odb/src/db/dbInst.cpp
src/odb/src/db/dbInst.h
src/odb/src/db/dbModule.cpp

Adding the new script for delta debugging under etc.
Improving _dbModule::removeInst() through the use of a doubly linked list.

deltaDebug.py  & removeInst() 

---

src/dpo/src/detailed_mis.cxx
src/dpo/src/detailed_random.cxx
src/dpo/src/legalize_shift.cxx
src/drt/src/gc/FlexGC_rq.cpp
src/drt/src/gr/FlexGR_maze.cpp
src/gpl/src/placerBase.cpp
src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/src/maze.cpp
src/grt/src/fastroute/src/utility.cpp
src/mpl2/src/block_placement.cpp
src/mpl2/src/shape_engine.cpp
src/odb/src/db/dbSearch.cpp
src/odb/src/db/grids.cpp
src/odb/src/def/def/def_keywords.cpp
src/pdn/src/connect.cpp
src/pdn/src/via.cpp
src/ppl/src/IOPlacer.cpp
src/rcx/src/extBenchDB.cpp
src/rcx/src/extFlow.cpp
src/rcx/src/extRCmodel.cpp
src/rcx/src/extmeasure.cpp
src/rcx/src/netRC.cpp
src/rcx/src/powerConn.cpp

clang unused var warnings

---

src/drt/src/io/io.cpp

https://github.com/The-OpenROAD-Project/OpenROAD/issues/1872

Consider actual masterslice layer name instead of hardcoded FR_MASTERSLICE

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/RepairDesign.cc
src/rsz/src/RepairSetup.cc
src/rsz/src/Resizer.cc
src/rsz/src/Resizer.i

rsz placate coverity false positives

---

src/drt/src/io/io.cpp

closes The-OpenROAD-Project/OpenROAD#1872

---

src/drt/src/io/io.cpp

This reverts commit 6e6713724c8657e5e4e4be077c38c79910ece2d5.

Revert "closes The-OpenROAD-Project/OpenROAD#1872"

---

src/drt/src/TritonRoute.cpp
src/drt/src/db/obj/frBlock.h
src/drt/src/db/obj/frBlockage.h
src/drt/src/db/obj/frGuide.h
src/drt/src/db/obj/frInst.h
src/drt/src/db/obj/frInstBlockage.h
src/drt/src/db/obj/frInstTerm.h
src/drt/src/db/obj/frMarker.h
src/drt/src/db/obj/frMaster.h
src/drt/src/db/obj/frNet.h
src/drt/src/db/obj/frShape.cpp
src/drt/src/db/obj/frShape.h
src/drt/src/db/obj/frTerm.h
src/drt/src/db/obj/frVia.cpp
src/drt/src/db/obj/frVia.h
src/drt/src/distributed/drUpdate.cpp
src/drt/src/distributed/drUpdate.h
src/drt/src/distributed/frArchive.h
src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR.h
src/drt/src/dr/FlexDR_conn.cpp
src/drt/src/dr/FlexDR_end.cpp
src/drt/src/io/io.cpp
src/drt/src/serialization.h
src/drt/src/ta/FlexTA_end.cpp
src/dst/src/LoadBalancer.cc
src/odb/src/defin/definGroup.cpp

fix coverity warnings

---

third-party/CMakeLists.txt

Disable readline includes on abc code

---

src/odb/src/db/odb.tcl

odb: add utl logger ODB and ID

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i

grt: save_guides option

---

src/grt/src/GlobalRouter.cpp

Signed-off-by: luis201420 <tauro_luisito_20@hotmail.com>

grt: Layer index fix

---

src/gui/src/dbDescriptors.cpp

Signed-off-by: Matt Liberty <mliberty@eng.ucsd.edu>

gui: fix highlighting of a group within a region

---

src/dpl/include/dpl/Opendp.h
src/dpl/src/FillerPlacement.cpp
src/dpl/src/dbToOpendp.cpp

dpl use placement locked to distinguish spacer cell used as tapcells

---

src/grt/src/GlobalRouter.cpp

Signed-off-by: luis201420 <tauro_luisito_20@hotmail.com>

grt: Fixing function name and changing to static function

---

test/Nangate45/Nangate45.vars
test/flow.tcl
test/sky130hd/sky130hd.vars
test/sky130hs/sky130hs.vars

add layer range for pin_access and detailed_route

---

src/ppl/src/HungarianMatching.cpp

ppl: init matrix for groups with infinite to avoid invalid assignment

---

src/odb/src/swig/python/dbenums.i
src/odb/src/swig/tcl/dbenums.i

odb: typemap dbTechLayerCutSpacingTableDefRule::LOOKUP_STRATEGY

---

src/grt/src/GlobalRouter.tcl

GRT: Fix typo

---

docs/misc/AddTool.patch

I updated ./docs/misc/AddTool.patch. The previous version was outdated, and resulted in lots of hunks being lost when patching. This one should be revised so that the new tool works right after patching.

Update new tool patch

---

src/rsz/src/RepairDesign.cc

rsz gpl coyote_hier stacked instances

---

src/drt/src/TritonRoute.cpp

drt: Fix error message for invalid via in pin options

---

src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/dr/FlexDR.cpp
src/drt/test/gcd_nangate45_dump_worker.tcl

drt: fix run single worker

---

src/grt/README.md
src/grt/src/GlobalRouter.tcl
src/grt/test/regression_tests.tcl
src/grt/test/repair_antennas_error1.ok
src/grt/test/repair_antennas_error1.tcl
src/grt/test/repair_antennas_error2.ok
src/grt/test/repair_antennas_error2.tcl

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/2135

grt: fix bug when diode cell has definitions in multiple liberty files

---

src/grt/src/RepairAntennas.h

grt: fix instability on repair_antennas results

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/RepairDesign.cc
src/rsz/src/RepairHold.cc
src/rsz/src/RepairSetup.cc
src/rsz/src/Resizer.cc

or1558 rsz respect net/instance do not touch

---

src/drt/src/TritonRoute.cpp
src/drt/src/db/tech/frConstraint.h
src/drt/src/dr/FlexDR.cpp

https://openroad.atlassian.net/browse/OR-1552

DRT Report Violations at end of each iterations

---

src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/TritonRoute.tcl
src/drt/src/db/tech/frLayer.h
src/drt/src/db/tech/frTechObject.h
src/drt/src/io/io.cpp
src/drt/src/pa/FlexPA_prep.cpp

https://openroad.atlassian.net/browse/OR-1550

OR-1550 drt: set unidirectional routing layer

---

src/OpenRoad.tcl
src/README.md
src/rsz/README.md
src/rsz/include/rsz/Resizer.hh
src/rsz/src/RepairDesign.cc
src/rsz/src/RepairHold.cc
src/rsz/src/RepairSetup.cc
src/rsz/src/Resizer.cc
src/rsz/src/Resizer.i
src/rsz/src/Resizer.tcl
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_design4.ok
src/rsz/test/repair_design4.tcl
src/rsz/test/repair_design5.ok
src/rsz/test/repair_design5.tcl

Set dont touch

---

src/Main.cc

Include -metrics in showUsage

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/Resizer.cc
src/rsz/test/repair_setup2.ok

rsz journal buffer restore order

---

src/drt/src/dr/FlexGridGraph_maze.cpp
src/drt/src/rp/FlexRP_prep.cpp

dr: fix via2via forbidden len

---

src/drt/src/db/tech/frConstraint.h

drt: fix check for second layer

---

src/drt/src/db/tech/frConstraint.h
src/drt/src/io/io.cpp

drt fix coverity issue

---

src/ppl/src/HungarianMatching.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2314

ppl: fix access to invalid positions on slots_

---

src/ppl/src/HungarianMatching.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2320

ppl: fix crash by checking if matrix is not empty

---

src/rsz/src/RepairDesign.cc

rsz: or1613 rsz stuck in infinite loop in gf180/aes

---

src/utl/src/LoggerCommon.cpp
src/utl/src/LoggerCommon.h

Signed-off-by: Don MacMillen <don@macmillen.net>

Fix Coverity issues

---

etc/DependencyInstaller.sh
etc/DockerHelper.sh

adding dependencies support for ubuntu 22

---

src/drt/src/pa/FlexPA_prep.cpp

drt: Fix double -> int narrowing warning

---

docs/contrib/PlatformBringUp.md

Addresses https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/613

Clarify ORFS platform bringup for clkgates/latches

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/src/RipUp.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2395

grt: fixes for read_guides cmd

---

include/ord/Design.h
src/CMakeLists.txt
src/Design.cc
src/Main.cc
src/grt/CMakeLists.txt
src/grt/README.md
src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter-py.i
src/grt/test/clock_route.py
src/grt/test/clock_route_error1.py
src/grt/test/congestion1.py
src/grt/test/congestion2.py
src/grt/test/critical_nets_percentage.py
src/grt/test/est_rc1.py
src/grt/test/gcd_flute.py
src/grt/test/grt_aux.py
src/grt/test/helpers.py
src/grt/test/macro_obs_not_aligned.py
src/grt/test/multiple_calls.py
src/grt/test/ndr_1w_3s.py
src/grt/test/obs_out_of_die.py
src/grt/test/pd1.py
src/grt/test/pin_access1.py
src/grt/test/pre_routed1.py
src/grt/test/region_adjustment.py
src/grt/test/repair_antennas1.py
src/grt/test/tracks1.py

Not all the tcl tests have a Python version yet, but there is a good variety of Python regressions.

Grt python

---

src/drt/src/io/io_guide.cpp

drt: Add net name to genGuides_final error messages

---

src/README.md

Signed-off-by: niv280 <niv280@gmail.com>
I update the write_abstract_lef description, let me know if it is clear enough or it needed to make some changes.

Update write_abstract_lef in README

---

etc/DependencyInstaller.sh

Add or-tools as a dependency

---

src/grt/src/GlobalRouter.cpp
src/grt/test/inst_pin_out_of_die.ok

grt: Print pin name in findInstancesObstructions() error

---

src/rsz/test/remove_buffers2.def
src/rsz/test/remove_buffers2.ok

Signed-off-by: Austin Rovinski <rovinski@umich.edu>

[rsz] fix remove_buffers2 test case

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/Slots.h

ppl: fix compile warning messages

---

src/drt/src/db/tech/frLayer.cc
src/drt/src/db/tech/frLayer.h
src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexGridGraph.h
src/drt/src/dr/FlexGridGraph_maze.cpp

drt: Consolidate spacing calculation code

---

src/drt/src/dr/FlexDR_graphics.cpp
src/drt/src/pa/FlexPA_graphics.cpp

drt: Use getDbLayer()

---

src/README.md

Removing out of date Abstract LEF documentation

---

src/drt/CMakeLists.txt
src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/TritonRoute.tcl
src/drt/src/frBaseTypes.h
src/drt/src/ta/FlexTA.cpp
src/drt/src/ta/FlexTA.h
src/drt/src/ta/FlexTA_graphics.cpp
src/drt/src/ta/FlexTA_graphics.h

drt/ta: Add gui debug

---

src/drt/src/ta/FlexTA_assign.cpp
src/drt/src/ta/FlexTA_init.cpp

drt/ta: Use getMinSpacingValue()

---

src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.tcl
src/ppl/test/place_pin6.defok
src/ppl/test/place_pin6.ok
src/ppl/test/place_pin6.tcl
src/ppl/test/regression_tests.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2565

ppl: make place_pin -pin_size optional

---

include/ord/Tech.h
src/CMakeLists.txt
src/Design.cc
src/Main.cc
src/OpenRoad-py.i
src/Tech.cc
src/drt/CMakeLists.txt
src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute-py.i
src/drt/test/aes_nangate45.py
src/drt/test/drt_aux.py
src/drt/test/helpers.py
src/drt/test/ispd18_sample.py
src/drt/test/single_step.py

Python wrapper and Python regression for TritonRoute

Drt python

---

src/gui/src/clockWidget.cpp
src/gui/src/clockWidget.h

Adds:
- inverter graphics item for the CTS viewer incase the output port is inverting.

gui: add inverter shape to CTS viewer

---

src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR.h
src/drt/src/dr/FlexDR_conn.cpp
src/drt/src/dr/FlexDR_maze.cpp
src/drt/src/dr/FlexGridGraph.cpp
src/drt/src/dr/FlexGridGraph_maze.cpp
src/drt/src/io/io.cpp
src/drt/src/pa/FlexPA_prep.cpp
src/drt/src/ta/FlexTA.h

drt: Fix a few typos

---

src/drt/src/dr/FlexDR_maze.cpp

drt/dr: Use getMinSpacingValue()

---

etc/DependencyInstaller.sh

etc: add wget as dep to download or-tools

---

src/drt/test/aes_nangate45_distributed.tcl
src/drt/test/gcd_nangate45_distributed.tcl
src/dst/src/BalancerConnection.cc
src/dst/src/LoadBalancer.cc

exception changes with different boost versions.

dst: fix error

---

src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/TritonRoute.tcl
src/drt/src/gc/FlexGC.cpp
src/drt/src/gc/FlexGC.h
src/drt/src/gc/FlexGC_impl.h

drt: parallelize the standalone drc check

---

src/rsz/src/RepairDesign.cc

rsz more bad fakeram insulation

---

src/gui/src/clockWidget.cpp
src/gui/src/clockWidget.h

https://github.com/The-OpenROAD-Project/OpenROAD/issues/2637

gui: change CTS viewer to default to only showing the currently active clock

---

src/pdn/src/grid.cpp
src/pdn/src/via_repair.cpp

pdn: account for vias in macro pins

---

src/gui/src/dbDescriptors.cpp
src/gui/src/layoutViewer.cpp
src/pdn/src/grid.cpp

Fixes:
- Lack of support for vias in mpins
- Missing XY transform in PDN on mpins

gui: account for vias in mpins

---

.github/workflows/github-actions-test-installer.yml
etc/DependencyInstaller.sh

test build in test installer GHA

---

docs/toc.yml

rename tool categories in documentation

---

.github/workflows/github-actions-format-on-push.yml

gha: fix runs-on statement

---

src/gui/src/browserWidget.cpp
src/gui/src/browserWidget.h
src/gui/src/mainWindow.cpp

Addresses: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2632
Adds:
- button to indicate module view is not enabled and allow for enabling

gui: add warning button in hierarchy browser to enable view

---

src/pdn/src/PdnGen.cc

Fixes: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2678

pdn: check if region is null

---

src/pad/src/PdnGen.tcl

pdn: spelling fixes in error messages

---

src/dbSta/src/dbNetwork.cc

dbSta OR2677 ODB is clueless about tristates

---

src/mpl2/src/hier_rtlmp.cpp

mpl2: fix unnecessary copy warning

---

src/gui/src/staGui.cpp
src/gui/src/staGui.h
src/gui/src/staGuiInterface.cpp
src/gui/src/staGuiInterface.h
src/gui/src/timingWidget.cpp

Adds to gui sta interface:
- Option to just get one path per endpoint
- Total number of endpoints

gui: add option to select just one path per endpoint in staGui

---

README.md

Signed-off-by: vijayank88 <paruthi143@gmail.com>
GF180 PDK moved to public PDK list.

move GF180 to public PDK

---

include/ord/Design.h
src/CMakeLists.txt
src/Design.cc
src/Main.cc
src/psm/include/psm/pdnsim.h
src/psm/src/CMakeLists.txt
src/psm/src/pdnsim-py.i
src/psm/test/aes_asap7_vdd.py
src/psm/test/aes_test_vdd.py
src/psm/test/aes_test_vdd_set_node_density.py
src/psm/test/aes_test_vdd_set_node_density_fact.py
src/psm/test/aes_test_vss.py
src/psm/test/gcd_all_vss.py
src/psm/test/gcd_em_test_vdd.py
src/psm/test/gcd_no_vsrc.py
src/psm/test/gcd_sky130_vdd.py
src/psm/test/gcd_test_vdd.py
src/psm/test/gcd_vss_no_vsrc.py
src/psm/test/gcd_write_sp_test_vdd.py
src/psm/test/helpers.py
src/psm/test/pdnsim_aux.py

This was another easy one. Still had to use evalTclString for the read_sdc command, though.

Psm python

---

include/ord/OpenRoad.hh
src/OpenRoad.cc
src/OpenRoad.i
src/dbSta/src/dbReadVerilog.tcl
src/dbSta/src/dbSta.i
src/dbSta/test/find_clks1.ok
src/dbSta/test/find_clks1.tcl
src/dbSta/test/find_clks2.ok
src/dbSta/test/find_clks2.tcl

or2687 write_timing_model ignore derating

---

etc/DependencyInstaller.sh

This makes it build on Ubuntu 22.10

Add Ubuntu 22.10 support

---

src/ppl/src/IOPlacer.cpp

ppl: fix pin counting in mirrored pins to fix infinite loop

---

src/drt/src/dr/FlexDR_maze.cpp

drt: avoid creating unnecessary patch metal

---

src/Metrics.tcl

metrics: fix timing metrics

---

src/gui/src/staGui.cpp
src/gui/src/staGui.h

Addresses: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2728

gui: add controls for timing renderer to control data path, launch, and capture clocks

---

src/drt/test/regression_tests.tcl
src/drt/test/ta_ap_aligned.ok
src/drt/test/ta_ap_aligned.tcl
src/drt/test/ta_pin_aligned.ok
src/drt/test/ta_pin_aligned.tcl

I forgot to enable the TA tests when adding them.

drt: Enable TA tests

---

src/dst/src/WorkerConnection.cc
src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.h
src/grt/src/fastroute/include/FastRoute.h
src/utl/include/utl/algorithms.h

Search for boost libraries in system directories only

---

src/odb/src/def/def/def.y
src/odb/src/lef/lef/lef.y

odb: Add missing braces

---

src/ppl/src/IOPlacer.cpp

ppl: add assert when pin assignment goes off the rails

---

src/grt/src/fastroute/include/DataType.h
src/grt/src/fastroute/src/FastRoute.cpp

grt: Remove unused red field from h_edges_3D_

---

etc/DependencyInstaller.sh

rename os argument for _installOrTools

---

src/grt/src/GlobalRouter.cpp

grt: add load congestion report tip routing failure

---

src/ppl/src/Slots.h

Update PPL for C++20 support

---

src/drt/src/TritonRoute.cpp
src/drt/src/TritonRoute.i
src/drt/src/TritonRoute.tcl
src/drt/src/dr/FlexDR.cpp
src/drt/test/gcd_nangate45_dump_worker.tcl
src/drt/test/gcd_nangate45_test_worker.tcl

drt: dump multiple workers

---

src/grt/src/GlobalRouter.cpp

grt: save out empty congestion report file to erase old report

---

src/gui/src/tclCmdInputWidget.cpp

Fixes:
- missing error message when errors occur on startup

gui: fix startup behavior to show error message in supplied script

---

.github/workflows/github-actions-test-installer.yml
etc/Build.sh
etc/DependencyInstaller.sh
etc/DockerHelper.sh

macOS installer fixes and GHA

---

src/drt/src/dr/FlexDR_init.cpp

closes The-OpenROAD-Project/OpenROAD#2805

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/HungarianMatching.cpp
src/ppl/src/HungarianMatching.h
src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.tcl
src/ppl/test/random9.defok
src/ppl/test/random9.ok
src/ppl/test/random9.tcl
src/ppl/test/regression_tests.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2819

ppl: fix mirrored_pins during random placement

---

src/odb/src/swig/python/dbtypes.i

Same fix from https://github.com/The-OpenROAD-Project/OpenROAD/pull/2793 but for python swig

odb: fix for swig 4.1.0

---

cmake/FindTCL.cmake
src/Exception.i
test/regression
test/regression.tcl
test/regression_vars.tcl
test/save_ok

revert illegal copyright/license in src copied from opensta

---

.github/workflows/github-actions-macos.yml
.github/workflows/github-actions-on-push.yml

CI: Update actions/checkout version

---

src/ant/src/AntennaChecker.cc
src/dpo/src/detailed_manager.cxx
src/dpo/src/detailed_mis.cxx
src/drt/src/gc/FlexGC_init.cpp
src/drt/src/gc/FlexGC_rq.cpp
src/drt/src/gr/FlexGR.cpp
src/grt/src/fastroute/src/FastRoute.cpp
src/mpl2/src/hier_rtlmp.cpp
src/odb/src/db/grids.cpp
src/par/src/MLPart/mlpart/ClusteredHGraph/bhemClustHG.cxx
src/par/src/MLPart/mlpart/ClusteredHGraph/grhemClustHG.cxx
src/par/src/MLPart/mlpart/ClusteredHGraph/hemClustHG.cxx
src/ppl/src/IOPlacer.cpp
src/psm/src/ir_solver.cpp
src/rcx/src/extSpef.cpp

This reduces the number of warnings seen when building with a recent version of clang.

Fix a few more compiler warnings

---

src/drt/src/db/taObj/taPin.h
src/drt/src/ta/FlexTA.h
src/drt/src/ta/FlexTA_assign.cpp
src/drt/src/ta/FlexTA_init.cpp

wlen2 is a cryptic name, and every time I look at TA I have to reacquaint myself with what it is.

Rename wlen2 to pinCoord

---

src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR_init.cpp
src/drt/src/dr/FlexDR_maze.cpp
src/drt/src/dr/FlexGridGraph_maze.cpp

Based on a patch by Austin Rovinski

drt: Use Point::manhattanDistance

---

src/drt/src/dr/FlexDR_maze.cpp

Based on a patch by Austin Rovinski

drt: Use Point::squaredDistance

---

src/drt/src/dr/FlexDR_graphics.cpp
src/drt/src/dr/FlexDR_init.cpp
src/drt/src/dr/FlexGridGraph_maze.cpp
src/drt/src/frBaseTypes.h

Signed-off-by: Austin Rovinski <rovinski@umich.edu>

[DRT] Use range for on frDirEnum

---

src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR_init.cpp
src/drt/src/dr/FlexGridGraph.cpp

Some commits that rebased cleanly from #1533

Some rovinski cleanup rebased

---

src/dpl/CMakeLists.txt
src/dpo/CMakeLists.txt
src/grt/CMakeLists.txt

Adds library structure to DPL following the standard convention.

Adds library structure to DPL

---

src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR_init.cpp
src/drt/src/dr/FlexDR_maze.cpp
src/drt/src/ta/FlexTA_assign.cpp

drt: Use rect.area()

---

src/grt/src/heatMap.cpp
src/grt/src/heatMap.h

This is what I mocked up to view the GCells in #2924 
If it's of interest to include.

grt: add usage and capacity to heatmap

---

src/grt/src/GlobalRouter.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2924

grt: fix averageTrackPattern function

---

src/OpenRoad.cc
src/dbSta/src/dbSta.cc

Found this while running Valgrind.

Fixing memory leak in STA

---

src/ppl/README.md
src/ppl/include/ppl/IOPlacer.h
src/ppl/src/HungarianMatching.cpp
src/ppl/src/HungarianMatching.h
src/ppl/src/IOPlacer-py.i
src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.i
src/ppl/src/IOPlacer.tcl
src/ppl/src/Netlist.cpp
src/ppl/src/Netlist.h
src/ppl/src/Slots.h
src/ppl/test/group_pins8.defok
src/ppl/test/group_pins8.ok
src/ppl/test/group_pins8.py
src/ppl/test/group_pins8.tcl
src/ppl/test/group_pins9.defok
src/ppl/test/group_pins9.ok
src/ppl/test/group_pins9.py
src/ppl/test/group_pins9.tcl
src/ppl/test/ppl_aux.py
src/ppl/test/regression_tests.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2904

ppl: add -group and -order flags to set_io_pin_constraint

---

.github/workflows/github-actions-clang-tidy-post.yml
.github/workflows/github-actions-clang-tidy.yml

Fixes execution problem with forks.

Using Split Workflow for Clang Tidy

---

src/psm/test/aes_test_vdd.ok
src/psm/test/aes_test_vdd_set_node_density.ok
src/psm/test/aes_test_vdd_set_node_density_fact.ok
src/psm/test/aes_test_vss.ok
src/psm/test/gcd_all_vss.ok
src/psm/test/gcd_em_test_vdd.ok
src/psm/test/gcd_no_vsrc.ok
src/psm/test/gcd_test_vdd.ok
src/psm/test/gcd_vss_no_vsrc.ok
src/psm/test/gcd_write_sp_test_vdd.ok
src/rsz/test/resize6.ok

Latest OpenSTA code + regression ok file update. PSM and RSZ regressions are passing

Update to latest OpenSTA 

---

src/drt/src/gc/FlexGC_init.cpp

Use find() instead of iterating through the set.

drt/gc: Don't iterate through targetObjs_ in initDesign_skipObj

---

src/drt/src/dr/FlexDR_maze.cpp

Add/fix some comments explaining how the src and dst pins are selected. Also make some small cleanups to the code.

drt/dr: Small cleanups to src and dst pin selection

---

src/drt/src/db/taObj/taPin.h
src/drt/src/ta/FlexTA.h
src/drt/src/ta/FlexTA_assign.cpp
src/drt/src/ta/FlexTA_init.cpp

It's completely unclear what wlen is, so rename it and add some comments explaining what it does.

drt/ta: Rename wlen to nextIrouteDir

---

src/drt/src/io/io.h
src/drt/src/io/io_parser_helper.cpp

Restore part of commit a965d53f6e7d ("drt: improve via selection"), avoiding the GF14 specific changes.

drt: improve via selection

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/HungarianMatching.cpp
src/ppl/src/HungarianMatching.h
src/ppl/src/IOPlacer.cpp
src/ppl/test/add_constraint11.defok
src/ppl/test/add_constraint11.ok
src/ppl/test/add_constraint11.tcl
src/ppl/test/regression_tests.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3055

ppl: fix assignment of mirrored pins when one of them is inside a pin group

---

src/odb/src/defin/definReader.cpp

odb: read NDRs in INCREMENTAL mode

---

etc/DependencyInstaller.sh

Without this there will be no GUI.
Tested on RHEL8.

Add RHEL requirements for building GUI

---

etc/deltaDebug.py

deltaDebug: ignore irrelevant errors

---

src/gpl/src/graphics.cpp
src/gpl/src/nesterovBase.cpp
src/gpl/src/nesterovBase.h

Removed binStor concept. Having a vector of Bin objects is faster due to cache locality considerations.

[gpl]: Improve performance of GPL by 13%

---

src/cts/src/HTreeBuilder.cpp
src/cts/test/balance_levels.ok
src/cts/test/check_buffers.ok
src/cts/test/check_wire_rc_cts.ok
src/cts/test/simple_test_clustered.ok

See https://github.com/The-OpenROAD-Project/OpenROAD/pull/2823#issuecomment-1407308584 for details

cts: Fix divide by zero error

---

src/drt/src/io/io.cpp

drt: fix boxes of bterms above top routing layer

---

src/drt/src/db/obj/frBTerm.h
src/drt/src/db/obj/frBlock.h

drt: Remove block_ from frBTerm

---

README.md

Hammer from Berkeley added to `README.md`
https://docs.hammer-eda.org/en/latest/Examples/openroad-nangate45.html

Hammer flow link included

---

src/gui/src/displayControls.cpp
src/gui/src/displayControls.h
src/gui/src/layoutViewer.cpp
src/gui/src/options.h

@maliberty try this out and see if this works as you want
Closes: #3201

gui: add site based controls to rows

---

src/gui/src/displayControls.cpp
src/gui/src/displayControls.h

gui: save row settings save and restore for group

---

src/ppl/src/IOPlacer.cpp
src/ppl/src/munkres/src/Hungarian.cpp
src/ppl/src/munkres/src/Hungarian.h

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3244

ppl: fix int overflow

---

src/gui/src/displayControls.cpp
src/gui/src/displayControls.h
src/gui/src/layoutViewer.cpp
src/gui/src/options.h

gui: check if rows are visible before iterating over rows

---

src/gui/src/heatMapPlacementDensity.cpp

Walks tree of blocks to render heatmap.

Adds hierarchical support to placement density heatmap

---

src/Main.cc

solving utf-8 bug when run GUI

---

etc/Env.sh

@maliberty  Good to go I think.
Motivation, easier to file github issues correctly: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/1081

etc/Env.sh: run from anywhere

---

src/ant/src/AntennaChecker.cc

FIxes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3369

ant: check if layer has antenna rules before calculating PAR and variants

---

src/grt/src/RepairAntennas.cpp
src/grt/src/RepairAntennas.h

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3391

grt: get correct row orientation when diode is connected to pad or macro

---

src/grt/src/GlobalRouter.i
src/grt/src/fastroute/include/AbstractFastRouteRenderer.h
src/grt/src/fastroute/include/FastRouteRenderer.h
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/src/fastroute/src/FastRouteRenderer.cpp

Fixing bug found when using debug mode in GRT.

Grt debug fix

---

docs/user/Build.md

Added instructions to Build.md for building with Address Sanitizer. Fixes #3433

Update Build.md with ASAN instructions

---

src/gui/src/displayControls.cpp
src/gui/src/gui.cpp

Changes:
- fix segfault in display controls on tool tip
- fix segfault when running save_image interactively from the commandline
- prevent exiting from OR when returning from interactive session

gui: fix segfaults

---

src/grt/src/fastroute/include/DataType.h

To fix issue: https://github.com/The-OpenROAD-Project/OpenROAD/issues/3450

Fix compiling error with GCC v13.

---

src/drt/include/triton_route/TritonRoute.h
src/drt/src/TritonRoute.cpp
src/drt/src/dr/FlexDR.cpp
src/drt/src/io/io.cpp
src/drt/src/io/io.h

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3425

drt: destroy db wires when using debug drt snapshot

---

src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/mainWindow.cpp
src/odb/include/odb/db.h

This PR is related to #3404.
I left same-net rules without a link to Tech, because there was no API to get tech directly from it. If it's desirable to have this link, just let me know, as I can add it by getting the tech from the database instance db_.

Gui: Add inspector for dbBlock and dbTech

---

src/rsz/src/RepairDesign.cc

Don't touch pins connected to don't touch instances when fixing fanout.

Fix for openlane #1823

---

etc/DependencyInstaller.sh

This change is to avoid recent intermittent network issues.
Closes #2791

Use our own fork of lemon

---

src/dpl/src/Grid.cpp

Checks that the row heights of double height cells match the row height of the current cell. If they don't, it means that this pixel is partially filled by a single-height or shorter cell, which is allowed. However, if they do match, it means that we are trying to overwrite a double-height cell placement, which is an error.

dpl: Fixes double height placement already present error

---

src/dbSta/src/dbSta.cc
src/dst/src/BalancerConnection.cc
src/gui/src/renderThread.h
src/gui/src/search.h

Fixes https://github.com/hdl/conda-eda/issues/340

gui,dst,dbSta: add missing include

---

src/rsz/src/RepairSetup.cc
src/rsz/src/RepairSetup.hh
src/rsz/test/repair_fanout7.ok

Use the centroid of all receivers and driver pin to pick a location for the cloned gate.

pick the centroid of targets and driver pin to insert new cloned cell

---

README.md

Also fixed the line thickness in simple flow first box.

[Docs] fix <br> tags

---

README.md
docs/index.md
docs/toc.yml
src/psm/README.md
src/rcx/README.md

[Docs] Fix gitguide broken links + remove unnecessary shields

---

src/dbSta/src/MakeDbSta.cc

Changes:
- make sure the power density heatmap is available when invoked via `gui::show`

sta: ensure heatmap and renderer is installed

---

src/OpenRoad.tcl
src/utl/include/utl/Logger.h
src/utl/src/Logger.cpp
src/utl/src/LoggerCommon.cpp
src/utl/src/LoggerCommon.h

Adds:
- `unsuppress_message` to provide a method to undo `suppress_message`

utl: add unsuppress_message to mirror suppress_message

---

src/utl/src/Logger.i
src/utl/src/LoggerCommon.cpp
src/utl/src/LoggerCommon.h

Exposes the return value of pop_metrics_stage to the script.

utl: provide pop_metrics_stage return value

---

src/gui/src/displayControls.cpp
src/gui/src/displayControls.h
src/gui/src/layoutViewer.cpp
src/gui/src/options.h
src/gui/src/renderThread.cpp

Fixes #3409 
I am having some trouble getting clang-tidy to run locally, but I want to finish with this issue first.
BTW I asked some questions on the issue page if someone could take a look at those! thanks

gui dbITerm selection

---

src/rsz/src/Resizer.tcl
src/rsz/test/regression_tests.tcl
src/rsz/test/set_dont_touch1.ok
src/rsz/test/set_dont_touch1.tcl

Possible fix for #3655 
cc: @gadfort

rsz: fix warning about cells that do not exist

---

README.md

[Docs] Permalink for OR_messages in github

---

src/pdn/src/shape.cpp

Fixes:
- ppl removing Power ground nets because they didn't get marked fixed correctly.

pdn: ensure pins are marked fixed and special if the bterm and bpin already exists

---

src/Main.cc

src/Main: use Py_RunMain on python >= 3.8

---

.readthedocs.yaml

docs: add config file

---

src/fin/LICENSE
src/fin/README.md

Added License and missing params

[Docs] fin documentation

---

src/grt/README.md
src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i
src/grt/src/GlobalRouter.tcl
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/src/fastroute/src/utility.cpp

Report the DRC on each iteration of overflow. By default only the final report is generated. (Discussed in #3583)

Grt: Add -drc_report_iter_step option

---

README.md

update regression tests guide

---

src/dpl/src/CheckPlacement.cpp
src/dpl/src/Opendp.tcl

very simple PR
Solves issue #3727

no report unless asked explicitly

---

src/grt/src/RepairAntennas.cpp
src/grt/src/RepairAntennas.h

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3752

grt: check jct_id before creating new path or virtual path

---

src/rsz/src/Resizer.tcl
src/rsz/test/regression_tests.tcl
src/rsz/test/set_dont_use1.ok
src/rsz/test/set_dont_use1.tcl

rsz: fix set_dont_use if cell is misspelled

---

etc/DependencyInstaller.sh

A few adjustments necessary to accommodate development on newer Ubuntu versions

Support Ubuntu 23.04++

---

src/ppl/src/SimulatedAnnealing.cpp

@eder-matheus I'm shooting from the hip here, but there does seem to be an infinite loop...

ppl: fix infinite loop in simulated annealing

---

docs/toc.yml
docs/user/ORFS.md

@dralabeing Pending your input for the ORFS link page.

[Docs] add link to ORFS

---

src/ppl/src/IOPlacer.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1355

ppl: error out when constraint does not have enough slots for its pins

---

src/ant/README.md
src/ant/src/AntennaChecker.tcl

Update documentation for consistency in formatting
@dralabeing 
https://openroad--3696.org.readthedocs.build/en/3696/main/src/ant/README.html

[Docs] ant documentation

---

src/ifp/README.md

Fix missing documentation and formatting issues
https://openroad--3716.org.readthedocs.build/en/3716/main/src/ifp/README.html

[Docs] ifp documentation

---

src/mpl/README.md
src/mpl/src/MacroPlacer.tcl

Fix missing documentation and formatting issues
https://openroad--3713.org.readthedocs.build/en/3713/main/src/mpl/README.html

[Docs] mpl documentation 

---

src/rsz/src/RepairDesign.cc

do not repair nets which are connected by abutment

---

docs/toc.yml
src/pdn/README.md
src/upf/README.md

Fix missing documentation and formatting issues

[Docs] upf documentation

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/RepairSetup.cc
src/rsz/src/Resizer.cc

Clean up gate cloning undo code prior to moving to the new undo infrastructure.

refactor cloning undo code

---

.readthedocs.yaml
README.md
docs/conf.py
docs/puppeteer-config.json

Continuing here because the RTD docs stopped uploading changes to the commits.

[Docs] Mermaid anchor fix test 2

---

src/stt/src/flt/README.md

Addresses this comment @dralabeing 
5. Flute Flute: https://openroad.readthedocs.io/en/latest/main/src/stt/src/flt/README.html#flute3, mention that the Global router and resizer use it internally in OpenROAD.

[Docs] flt documentation

---

docs/conf.py

Similar to ORFS parallel PR https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1395

[Docs] Fix Show source bug

---

src/ppl/src/IOPlacer.cpp
src/ppl/test/no_instance_pins.ok

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3922

ppl: check available slots agains number of pins in the correct place

---

src/gui/src/gui.cpp
src/gui/src/mainWindow.cpp

Reverts The-OpenROAD-Project/OpenROAD#3940
Per @gadfort in https://github.com/The-OpenROAD-Project/OpenROAD/issues/3945

Revert "gui: restore gui hide behavior"

---

src/cts/README.md

Addresses https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3955 @vvbandeira

[Docs] update cts docs

---

src/rsz/test/eqy_repair_setup2.ok
src/rsz/test/eqy_repair_setup2.tcl
src/rsz/test/eqy_repair_setup5.ok
src/rsz/test/eqy_repair_setup5.tcl
src/rsz/test/regression_tests.tcl
test/helpers.tcl

Add negative equivalence tests

Eqy negative check

---

src/grt/src/GlobalRouter.cpp
src/grt/test/inst_pin_out_of_die.def
src/grt/test/inst_pin_out_of_die.ok

Address comment on https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3974#discussioncomment-6983001.

grt: ignore power pins out of die

---

src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h

Resolves #3840
Layout can be dragged by holding middle mouse button like in KLayout.

gui: allow layout view to be dragged while holding middle mouse button

---

src/gui/src/renderThread.cpp
src/gui/src/renderThread.h

Resolves #3937
Just drawing a string in the center of the layout viewer.

gui: display message to inform that design is loading before first render

---

src/mpl2/src/hier_rtlmp.cpp

Solves [#3938](https://github.com/The-OpenROAD-Project/OpenROAD/issues/3938) .
Make reports that are not useful for users debug prints.

Mpl2 change output prints

---

.github/workflows/github-actions-test-installer.yml
etc/DependencyInstaller.sh
etc/DockerHelper.sh

(draft for now, will likely add a switch to turn on/off as it is not required for now)

etc: add yosys, eqy and sby as deps

---

docker/test_wrapper.sh
etc/DependencyInstaller.sh

Required for some features of `eqy`

etc: min version of python is now 3.8

---

src/gui/src/layoutTabs.cpp
src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h

gui: zoom triggered by keyboard now focus on cursor

---

src/cts/src/HTreeBuilder.cpp
src/cts/src/HTreeBuilder.h
src/cts/src/TreeBuilder.h
src/cts/src/Util.h
src/cts/test/array.ok
src/cts/test/array_no_blockages.ok
src/cts/test/check_buffers_blockages.ok

This is a minor change off the public branch.  Inside blockage now includes boundary points.

modified inside blockage criteria and added debug codes

---

src/ppl/README.md
src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp

Address issues reported in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/4061.

ppl: fix check for available positions in the top layer

---

src/drt/src/dr/FlexDR_init.cpp

Remove unreachable conditions in drt/FlexDR_init.cpp

---

src/gui/src/layoutViewer.cpp

Resolves #4000 
What was happening was: If the user put a resolution small enough to make `Utils::adjustMaxImageSize` resize the image, we were not adapting the resolution again based on this adjusted size.

gui: fix save image black output when using small resolution

---

src/CMakeLists.txt
src/gpl/CMakeLists.txt
src/gpl/README.md
src/gpl/include/gpl/Replace.h
src/gpl/src/mbff.cpp
src/gpl/src/mbff.h
src/gpl/src/replace.cpp
src/gpl/src/replace.i
src/gpl/src/replace.tcl
src/gpl/src/routeBase.cpp
src/mpl2/CMakeLists.txt

flip-flop clustering based on https://vlsicad.ucsd.edu/Publications/Conferences/344/c344.pdf

flip-flop clustering

---

src/ppl/README.md
src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.tcl
src/ppl/test/regression_tests.tcl
src/ppl/test/top_layer_error2.ok
src/ppl/test/top_layer_error2.tcl
src/ppl/test/write_pin_placement4.tcl

Address comments from other PRs.

ppl: small fixes

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/src/fastroute/src/maze3D.cpp
src/grt/src/fastroute/src/utility.cpp

Following discussion in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/4080

grt: add check for adjacent layers direction

---

src/grt/src/GlobalRouter.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4070

grt: check if layer exists in map when looking for macro obstructions

---

src/ppl/src/IOPlacer.cpp

ppl: remove unused sections_ initialization during random placement

---

src/gui/README.md
src/gui/include/gui/gui.h
src/gui/src/gui.cpp
src/gui/src/gui.i
src/gui/src/gui.tcl
src/gui/src/gui_utils.cpp
src/gui/src/gui_utils.h
src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h

Resolves #3999
@rovinski FYI, I'm making the correction you pointed out by creating a cache of the max size.

gui: add support for entering -width in save_image

---

src/odb/include/odb/db.h
src/odb/src/db/dbDatabase.h
src/odb/src/db/dbObstruction.cpp
src/odb/src/db/dbObstruction.h
src/odb/src/defin/definBlockage.cpp
src/odb/src/defin/definBlockage.h
src/odb/src/defin/definReader.cpp

Adds support for DEF blockages with EXCEPTPGNETS flag

odb: add support for exceptpgnets on dbObstructions

---

src/dpl/src/Place.cpp

Fixing bug when avoiding moving legal cells.

dpl: Avoiding moving cells that are outside of macros and inside the die

---

src/grt/src/GlobalRouter.cpp

Fix the crash reported by @precisionmoon when using NDRs.

grt: check net layer range when calculating NDR costs

---

src/mpl2/src/Mpl2Observer.h
src/mpl2/src/graphics.cpp
src/mpl2/src/graphics.h
src/mpl2/src/hier_rtlmp.cpp

Draw macro blockages during SA for SoftMacros.

mpl2: draw macro blockages in graphics

---

include/ord/Design.h
src/rsz/src/RepairDesign.cc

Also fixes header inclusion problem.

rsz: Fixes uninitialized variables in resizer.

---

src/cts/include/cts/TritonCTS.h
src/cts/src/CtsOptions.h
src/cts/src/TechChar.cpp
src/cts/src/TechChar.h
src/cts/src/TreeBuilder.h
src/cts/src/TritonCTS.cpp
src/cts/src/TritonCTS.i
src/cts/src/TritonCTS.tcl
src/rsz/README.md

Revert "Merge pull request #4239 from The-OpenROAD-Project-staging/secure-cts-auto-buffer"
This reverts commit c02333b7cf98b74a78ac70715d8157535046957c, reversing changes made to 944e225d4ed8539e80805ea66013e2a376650a44.

revert cts changes

---

src/OpenRoad.cc
src/drt/src/distributed/paUpdate.cpp
src/drt/src/pa/FlexPA.cpp
src/drt/src/pa/FlexPA_prep.cpp
src/odb/include/odb/db.h
src/odb/include/odb/dbStream.h
src/odb/src/db/dbBlock.cpp
src/odb/src/db/dbDatabase.cpp
src/odb/src/db/dbStream.cpp
src/odb/src/swig/common/swig_common.cpp
src/odb/test/cpp/TestAccessPoint.cpp
src/odb/test/cpp/TestLef58Properties.cpp
src/ppl/src/IOPlacer.cpp

In preparation for adding compression to the odb format.

odb: Migrate DB methods to generic iostreams

---

src/gpl/src/routeBase.cpp
src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4253

grt: skip layers out of min/max layer range

---

src/mpl2/src/SACoreHardMacro.cpp
src/mpl2/src/hier_rtlmp.cpp
src/mpl2/src/object.cpp

Fix #4247 
Converting some reports/infos to debugPrint (or error) and fixing error messages.

mpl2: improve output

---

src/ppl/src/IOPlacer.tcl
src/ppl/test/macro_not_placed.def
src/ppl/test/macro_not_placed.ok
src/ppl/test/macro_not_placed.tcl
src/ppl/test/macro_not_placed_random.ok
src/ppl/test/macro_not_placed_random.tcl
src/ppl/test/regression_tests.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4301

ppl: show warn message on macro not placed only for non-random runs

---

etc/deltaDebug.py

- more compact output
- you become what you measure: what is important is the time it takes to reproduce the error, not the size of the reproduction case, so print timeout at every step.
New output, less verbose. 2 lines per iteration:
```
$ openroad -python ~/OpenROAD-flow-scripts/tools/OpenROAD/etc/deltaDebug.py --persistence 4 --use_stdout --error_string "getObjectType" --base_db_path bazel-bin/build/results/asap7/BoomTile/base/3_place.odb --step ./run-me-BoomTile-asap7-base.sh 
OpenROAD v2.0-11344-g7631c468c 
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING ORD-0039] .openroad ignored with -python
Backing up original base file.
Performing a step …
```

deltaDebug: print timeout at every step, less verbose

---

src/rsz/src/Rebuffer.cc

This is done by making read-only copies and iterators const-ref. The time spent incrementing and decrementing the refcounts drops by about 6x when running the OpenROAD Gate Resize tool on a circuit we care about, as shown by the profile snippets below.
Botttom-up profile view before:
Bottom-up profile view after:
[Notice that the "before" profile corresponds to a slightly older snapshot where `slackPenalized` has not been updated to take a const-ref argument, so this change probably reduces the cost by at most 5x.]

Reduce the number of copies and destructions of std::shared_ptr.

---

src/gui/src/chartsWidget.cpp
src/gui/src/chartsWidget.h
src/gui/src/mainWindow.cpp

gui: avoid Charts crash when only loading .odb

---

.github/workflows/github-actions-lint-tcl.yml
src/gui/src/gui.tcl
src/pad/src/pad.tcl
src/pdn/src/pdn.tcl
src/psm/src/pdnsim.tcl

No functional changes, just adding gui/pad/pdn/psm to tclint github action

tcl: enable tclint for gui/pad/pdn/psm

---

src/ifp/test/regression_tests.tcl
src/ifp/test/upf/mpd_shifter.upf
src/ifp/test/upf_shifter_test.ok
src/ifp/test/upf_shifter_test.tcl
src/odb/include/odb/db.h
src/odb/src/codeGenerator/schema/chip/dbLevelShifter.json
src/odb/src/codeGenerator/schema/chip/dbPowerDomain.json
src/odb/src/db/dbDatabase.h
src/odb/src/db/dbLevelShifter.cpp
src/odb/src/db/dbLevelShifter.h
src/odb/src/db/dbPowerDomain.cpp
src/odb/src/db/dbPowerDomain.h
src/upf/include/upf/upf.h
src/upf/src/upf.cpp
src/upf/src/upf.i
src/upf/src/upf.tcl

Inserting level shifters based on defined strategies in UPF.

inserting level shifter cells

---

src/mpl2/src/hier_rtlmp.cpp
src/par/src/TritonPart.cpp
src/par/test/partition_gcd.ok

mpl2 & par: clear logger

---

src/grt/src/fastroute/src/RSMT.cpp

It moves variables and a call to `coeffADJ` to the scopes where their values are needed. It isn't a big optimization. As I checked by running black_parrot under callgrind, program spends 0.57% of time of grt phase in that call.

grt: evalue coeffADJ only if needed

---

src/grt/src/fastroute/src/utility.cpp

It removes unnecessary if statements from nested loops.

grt: Remove unnecessary ifs

---

src/gui/src/timingWidget.cpp

Fix #4487 
Write clock nodes in situations where the path is made only of clock nodes.
Paths with only clock nodes will be written with `-through` for all nodes. Using `-from` for the first and `-to` would lead to not finding the path in report_checks.

gui: fix crash in CLOSEST_MATCH for paths with only clock nodes

---

docs/conf.py
docs/contrib/DeveloperGuide.md
docs/getPatch.py
docs/misc/AddTool.patch
docs/misc/AddToolFiles.patch

@vvbandeira @maliberty 
This addresses the issue in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3735#discussioncomment-6569842
How it works: Instead of manually maintaining the `AddTool.patch` file I separated into static file `AddToolFiles.patch` and dynamic file `AddTool.patch`, the latter will be programmatically generated by running `python getPatch.py`.

[Docs] Addtool patch

---

README.md
docs/contrib/DeveloperGuide.md
docs/contrib/GitGuide.md
docs/user/Build.md
etc/find_messages.py
src/grt/README.md
src/grt/doc/messages/0118.md
src/grt/doc/messages/0119.md
src/ifp/README.md
src/mpl2/README.md
src/ppl/README.md

According to the google [docs ](https://docs.google.com/document/d/1UQ-UbyEPy9UKQAtiVg6x9kPvOg-eeLFHYf_F6QHOhh0/edit)
Changes made:
- 1,5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18
Changes in progress:
- 2, 3, 4
@vvbandeira @dralabeing @vijayank88

[Docs] OR review

---

src/pdn/README.md

Target
- Fix missing functions
- Formatting issues
- Update function signature to improve clarity, for example: `[-macro|-existing]`, and also check required/optional variables ordering 
https://openroad--3710.org.readthedocs.build/en/3710/main/src/pdn/README.html
Review pending merge https://github.com/The-OpenROAD-Project/OpenROAD/pull/3722

[Docs] pdn documentation

---

src/odb/include/odb/db.h
src/odb/src/db/dbBox.cpp
src/odb/src/db/dbBox.h
src/odb/src/db/dbDatabase.h
src/odb/src/defin/definPin.cpp
src/odb/src/defin/definPin.h
src/odb/src/defin/definReader.cpp
src/odb/src/defout/defout_impl.cpp
src/odb/test/data/design58.def
src/odb/test/write_def58.defok

Adds:
- support for layer mask in dbBox
- adds DEF in and out support for LAYER x MASK x for PINS
- test case for def

odb: add support for MASK on bpins

---

src/odb/src/defin/definComponent.cpp
src/odb/src/defin/definReader.cpp
src/odb/test/data/design.def
src/odb/test/write_lef_and_def.defok
src/odb/test/write_lef_and_def.lefok
src/odb/test/write_lef_and_def.ok
src/odb/test/write_lef_and_def.tcl

Adds:
- HALO support to COMPONENTS
- Adds test for LEFout and DEFout file diffs.

odb: add support to DEFin COMPONENT HALO

---

src/mpl2/src/hier_rtlmp.cpp

mpl2: fix mixed leaves splitting

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp
src/ppl/test/add_constraint_error7.ok

Partial fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/4436

ppl: add change suggestions in the error messages

---

src/grt/src/GlobalRouter.cpp
src/grt/src/RepairAntennas.cpp
src/grt/test/report_wire_length4.rptok

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4560

grt: fix bug in updateVias

---

src/mpl/src/ParquetFP/src/basepacking.cxx
src/mpl/src/ParquetFP/src/basepacking.h
src/mpl/src/ParquetFP/src/btree.cxx
src/mpl/src/ParquetFP/src/btree.h
src/mpl/src/ParquetFP/src/plsptobtree.cxx
src/mpl/src/ParquetFP/src/plsptobtree.h

Fixes ASAN violations at Google

mpl: Fixes static init order across translation units

---

src/tap/include/tap/tapcell.h
src/tap/src/tapcell.cpp

tap: avoid placing tapcells out of the rows

---

etc/DependencyInstaller.sh

Adds:
- qtcharts to Ubuntu and RHEL/CentOS installs

etc: add qtcharts to Dependency installer

---

src/rsz/src/Rebuffer.cc

This PR optimizes `RepairSetup::rebufferBottomUp` with three types of changes:
1. Vectors are preallocated wherever their size can be predicted
2. Slack values, used in sorting, are precalculated.
3. Option pruning is modified from pessimistically quadratic to linear complexity.
I gathered averaged outcomes from 10 runs on chosen designs (`cts` target):
Version \ Design | Ariane | BlackParrot | TinyRocket | Ibex
-|-|-|-|-
Unoptimized | 63m40s | 3m39s | 0m27s | 1m24s
Optimized | 12m32s | 2m57s | 0m21s | 0m28s

Optimize rebuffering

---

etc/deltaDebug.py
etc/test_deltaDebug.py

To run unittests:
```
cd etc
python -m unittest
```

Add unittests and simplify deltaDebug.py

---

src/gui/src/heatMap.cpp

Display busy cursor during heatmap calculations.

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.cpp
src/grt/src/Grid.h

Fixes https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1788

grt: get proper track spacing for tracks with multiple patterns

---

src/rsz/src/RepairSetup.cc

It adds caching results of `vertexSlack`, so it isn't called in `sort` function.
I measured times of cts stage in 7 runs of ariane133:
|                     | min time [min]   | avg time [min]   | med time [min]   | max time [min]   | sum time [min]   |
|:--------------------------|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|
| master               | 21:36            | 22:33            | 22:45            | 23:17            | 157:51           |
| my changes               | 21:23            | 22:01            | 21:50            | 22:52            | 154:08           |
So it speeds up cts by ~2.4%.

rsz: cache results of vertexSlack

---

src/gpl/src/nesterovBase.cpp
src/gpl/src/solver.cpp

This PR fixes a bug in GPU solver for initial placement (incorrect return value) plus removes redundant accumulation in Nesterov solver loop.

Minor GPL optimization + bugfix

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.h
src/grt/src/MakeWireParasitics.cpp
src/grt/test/congestion1.ok
src/grt/test/congestion2.ok
src/grt/test/congestion3.ok
src/grt/test/congestion4.ok
src/grt/test/congestion5.ok
src/grt/test/congestion6.ok
src/grt/test/congestion7.ok
src/grt/test/gcd.ok
src/grt/test/gcd_flute.ok
src/grt/test/inst_pin_out_of_die.ok
src/grt/test/invalid_pin_placement.ok
src/grt/test/macro_obs_not_aligned.ok
src/grt/test/modeling_instance_obs.ok
src/grt/test/multiple_calls.ok
src/grt/test/obstruction.ok
src/grt/test/overlapping_edges.ok
src/grt/test/pd3.ok
src/grt/test/region_adjustment.ok
src/grt/test/set_nets_to_route1.ok
src/grt/test/top_level_term1.ok
src/grt/test/top_level_term2.ok
src/grt/test/top_level_term3.ok
src/grt/test/upper_layer_net.ok

A few changes in the GRT code are needed before moving the congestion data from obstructions to ODB. Functional changes are not expected.

grt: small changes and refactoring

---

src/grt/src/GlobalRouter.cpp

grt: check max routing layer before fetching blockage data

---

etc/DependencyInstaller.sh

etc: check for yosys-config

---

src/odb/src/codeGenerator/gen.py
src/odb/src/codeGenerator/schema/chip/dbGCellGrid.json
src/odb/src/codeGenerator/templates/impl.cpp
src/odb/src/codeGenerator/templates/serializer_in.cpp
src/odb/src/codeGenerator/templates/serializer_out.cpp
src/odb/src/db/dbGCellGrid.cpp
src/odb/src/db/dbGCellGrid.h

* Adds serializers for structs
* Avoids forward declaring public structs

Add serializers to structs for code generator

---

src/mpl2/src/SACoreHardMacro.cpp
src/mpl2/src/SACoreHardMacro.h
src/mpl2/src/SACoreSoftMacro.cpp
src/mpl2/src/SACoreSoftMacro.h
src/mpl2/src/SimulatedAnnealingCore.cpp
src/mpl2/src/SimulatedAnnealingCore.h
src/mpl2/src/hier_rtlmp.cpp

This reverts commit c13d49185c6d15938f4fa276513e1f9e35bcca00, reversing changes made to 200ff70dc0247482a47db794c3d036ef903d58a7.
Fixes two timeouts in our CI. I'll keep looking at the designs with a timeout to understand what mpl2 triggered.

Revert "Merge pull request #4704 from AcKoucher/mpl2_boundary"

---

src/drt/src/io/io_parser_helper.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/4763
Fixes https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1786

drt: fix bug when checking if pin has tracks in its center

---

src/gui/src/layoutViewer.cpp
src/gui/src/renderThread.cpp

This needs to be validated for correct behavior

gui: ensure setLoadingState is called from layout viewer thread

---

src/mpl2/src/hier_rtlmp.cpp

Fix #4836 
We were not taking into account the case where we might have IO pins in the empty region in between the core and the die.
This should fix CI. (Failing in asap7/swerv_wrapper)

mpl2: ensure io blockages are created only when there are io pins in the boundary

---

etc/test_deltaDebug.py

deltaDebug: add mocking of openroad import in anticipation of future work

---

src/gui/src/chartsWidget.cpp
src/gui/src/chartsWidget.h

gui: create minimum number of bins for Charts

---

src/pdn/src/PdnGen.cc
src/pdn/src/connect.h
src/pdn/src/grid.cpp
src/pdn/src/grid.h
src/pdn/src/grid_component.cpp
src/pdn/src/grid_component.h
src/pdn/src/power_cells.cpp
src/pdn/src/power_cells.h
src/pdn/src/renderer.cpp
src/pdn/src/renderer.h
src/pdn/src/rings.cpp
src/pdn/src/rings.h
src/pdn/src/shape.cpp
src/pdn/src/shape.h
src/pdn/src/sroute.cpp
src/pdn/src/straps.cpp
src/pdn/src/straps.h
src/pdn/src/via.cpp
src/pdn/src/via.h
src/pdn/src/via_repair.cpp
src/pdn/src/via_repair.h

No functional changes expected, just cleaning up the rtree to use the odb boost geom.

pdn: switch pdn to use geom boost structures

---

src/gui/src/staGui.cpp

gui: allow sorting by skew in timing report

---

docs/user/Build.md

[Docs] add sudo to make install instructions docs

---

src/gui/src/inspector.cpp
src/gui/src/inspector.h
src/gui/src/mainWindow.cpp

gui: add context menu to write report command based on ITerms in the inspector

---

etc/DependencyInstaller.sh
include/ord/OpenRoad.hh
src/CMakeLists.txt
src/Main.cc
src/OpenRoad-py.i
src/OpenRoad.cc
src/OpenRoad.i

Reopening this as it was accidentally merged before without applying the changes.

etc: use brew to install or-tools in macOS

---

docker/Dockerfile.dev
etc/DependencyInstaller.sh

This reverts commit 391c9dfb8906659b9cc782fafd3a3835a069ca06.

Revert "etc: remove strip command from installer (#4950)"

---

src/grt/src/heatMapRudy.cpp

avoid crash when clicking on rudy heatmap and there are unplaced cells.

rudy: avoid heatmap crash 

---

docs/toc.yml
docs/user/Build.md
src/utl/README.md
src/utl/manREADME.md
src/utl/src/Utl.tcl

[Docs] Add manpages to Readthedocs

---

src/Main.cc

We see this banner all the time, so nice to remove a nit :-)

banner: nit, remove superfluous space

---

src/gui/include/gui/gui.h
src/gui/src/browserWidget.cpp
src/gui/src/bufferTreeDescriptor.cpp
src/gui/src/clockWidget.cpp
src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/displayControls.cpp
src/gui/src/drcWidget.cpp
src/gui/src/gui.cpp
src/gui/src/heatMap.cpp
src/gui/src/heatMapSetup.cpp
src/gui/src/inspector.cpp
src/gui/src/mainWindow.cpp
src/gui/src/renderThread.cpp
src/gui/src/staGui.cpp
src/gui/src/staGuiInterface.cpp
src/gui/src/tclCmdHighlighter.cpp
src/gui/src/timingWidget.cpp
src/pdn/src/PdnGen.cc
src/pdn/src/grid_component.cpp
src/pdn/src/straps.cpp
src/psm/include/psm/pdnsim.h
src/psm/src/debug_gui.cpp
src/psm/src/debug_gui.h
src/psm/src/pdnsim.cpp

No functional changes expected, only addressing issues identified by coverity

pdn/psm/gui: coverity report

---

src/gui/include/gui/gui.h
src/gui/src/bufferTreeDescriptor.cpp
src/gui/src/dbDescriptors.cpp
src/gui/src/staGuiInterface.cpp

No functional changes expected

gui: address coverity report

---

src/odb/include/odb/db.h
src/odb/src/db/dbBlock.cpp

Conversion functions between micron and DBUs.
Added bidirectional conversion functions for both length and area measurements.

odb: dbu and micron converters

---

src/ppl/src/IOPlacer.tcl
src/ppl/test/place_pin1.tcl

ppl: clear_io_pin_constraints failed

---

src/drt/src/dr/FlexDR.cpp

No functional changes, just a cosmetic fix

drt: remove stray . after :

---

src/OpenRoad.tcl
src/ant/src/AntennaChecker.tcl
src/pdn/src/pdn.tcl

Fixes [#5057](https://github.com/The-OpenROAD-Project/OpenROAD/issues/5057)

add missing arguments on help command

---

src/grt/src/GlobalRouter.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5085

grt: write congestion report when it fails during incremental grt

---

src/gui/src/staGui.cpp
src/gui/src/staGui.h
src/gui/src/staGuiInterface.cpp
src/gui/src/staGuiInterface.h
src/gui/src/timingWidget.cpp
src/gui/src/timingWidget.h

Resolve #4973 
Add to Timing Report:
- Column Visibility control
- Logic Delay
- Logic Depth 
*Also fix crash when right clicking timing report if no odb is loaded.

gui: add logic depth, logic delay and implement column visibility in timing report

---

src/grt/src/GlobalRouter.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5096

grt: legalize cells when every congestion iteration failed

---

src/OpenRoad.cc
src/dbSta/include/db_sta/dbNetwork.hh
src/dbSta/src/dbNetwork.cc
src/dbSta/src/dbReadVerilog.cc
src/dbSta/test/hier2.ok
src/dbSta/test/hier2.tcl
src/dbSta/test/hier2.v
src/dbSta/test/hier2_out.vok

Propagation of hierarchy flag from linker to dbNetwork.

Dbnetwork part1 attempt4

---

src/mpl2/src/mpl.tcl

mpl2: reduce log spam

---

include/ord/Timing.h
src/OpenRoad-py.i
src/Timing.cc
src/rsz/include/rsz/Resizer.hh
test/regression_tests.tcl
test/timing_api_4.ok
test/timing_api_4.py

Move makeEquivCells from protected to public in rsz::Resizer and call it in Timing::makeEquivCells. Create Timing::equivCells.

Adding Timing::equivCells and Timing::makeEquivCells python APIs

---

src/mpl2/README.md
src/mpl2/src/hier_rtlmp.cpp

mpl2: update flag to use odb method

---

src/gui/src/chartsWidget.cpp
src/gui/src/chartsWidget.h
src/gui/src/staGuiInterface.cpp
src/gui/src/staGuiInterface.h

gui: add filter to Charts based on Start/End path type

---

src/ppl/src/IOPlacer.cpp
src/ppl/test/large_groups1.ok
src/ppl/test/large_groups2.ok
src/ppl/test/large_groups3.ok
src/ppl/test/large_groups4.ok

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5148

ppl: convert warn message to debug print

---

src/dbSta/src/dbNetwork.cc

…-off-by: Andy Fox <andy@rushc.com>

initialization of next_ field to null ptr to silence coverity. 

---

src/cts/test/array.ok
src/cts/test/array_ins_delay.ok
src/cts/test/array_no_blockages.ok
src/rsz/src/RepairDesign.cc
src/rsz/test/repair_wire2.ok

Fixing the merge error mentioned in [#4801](https://github.com/The-OpenROAD-Project/OpenROAD/pull/4801)

Rsz fix longwire split length

---

src/dpl/include/dpl/Opendp.h
src/dpl/src/CheckPlacement.cpp
src/dpl/src/Objects.cpp
src/dpl/src/Objects.h
src/dpl/src/Opendp.cpp
src/dpl/src/Place.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5205

dpl: check if db_inst_ exists before accessing it

---

src/dpl/src/Place.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5204

dpl: don't touch fixed cells inside groups

---

src/grt/src/GlobalRouter.cpp
src/grt/test/single_row.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5211

grt: check if routing layer has track grid defined

---

src/grt/src/GlobalRouter.cpp

Fixes failing testcase when using incremental grt in PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/5100

grt: avoid adding special nets to dirty nets list

---

src/ppl/src/IOPlacer.tcl
src/ppl/test/place_pin_error1.ok
src/ppl/test/top_layer_error.ok

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5236

ppl: update error message

---

src/gui/src/staGui.cpp
src/gui/src/staGui.h
src/gui/src/staGuiInterface.cpp
src/gui/src/staGuiInterface.h

gui: add fanout to timing report

---

src/gpl/README.md

Fixed a missing flag in readme @maliberty

[Docs] Docs CI fix

---

src/odb/include/odb/db.h
src/odb/src/db/dbBTerm.cpp
src/odb/src/db/dbBTerm.h
src/odb/src/db/dbDatabase.h
src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5263

ppl: add constraint information to odb::dbBTerm

---

src/gui/src/staGui.cpp

Resolve #5083 
Adding tool tips to logic delay/depth and skew.

gui: add tooltips to Timing Report

---

src/grt/src/GlobalRouter.cpp
src/grt/src/Grid.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5286

grt: handle die area with non zero origin

---

src/grt/src/fastroute/src/maze.cpp
src/grt/src/fastroute/src/maze3D.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5294

grt: turn warn messages into debug print

---

Jenkinsfile

~all tests that can be parallel are so
+labels to 'sh' steps to improve readability in Jenkins
+more stages to improve readability in Jenkins
+global timeout of 2h
+individual steps timeout for build and regression tests

ci: misc improvements

---

Jenkinsfile

Add back test from PR 5165
Fixes #5351

ci: confirm cmake can be run w/o building tests

---

etc/CodeCoverage.sh
jenkins/Jenkinsfile.coverity

@maliberty FYI:
Next submission permitted on or after 2024-Jul-10  8:16 PM UTC

ci: fix coverity

---

src/pdn/src/straps.cpp

Fixes:
- corrects the limits for strap generation to use the correct axis

pdn: correct limits for straps

---

src/gui/src/layoutTabs.cpp
src/gui/src/layoutTabs.h
src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h
src/gui/src/mainWindow.cpp
src/gui/src/mainWindow.h

For issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/5329.

gui: Add option to map mouse wheel to zoom in/out by default in layout view

---

src/gui/src/mainWindow.cpp
src/gui/src/mainWindow.h

Adds save option in GUI toolbar menu to write out the database (mirrors open option).

gui: add save DB action

---

src/gui/src/layoutTabs.cpp
src/gui/src/layoutTabs.h
src/gui/src/layoutViewer.cpp
src/gui/src/layoutViewer.h
src/gui/src/mainWindow.cpp
src/gui/src/mainWindow.h

Default value is 20. The one from QScrollView.
By setting it to 500 which is the value when scrolling with with mouse wheel, I get a navigation similar to Innovus.

gui: Add option to configure scroll step of arrows key.

---

src/gui/src/gui.cpp
src/pdn/src/straps.cpp

Corrects the behavior of the GUI when hide is selected.
Fixes one bad format error in PDN debug print.

gui: fix exit logic on hide

---

src/odb/src/db/dbBox.cpp

Noticed some inconsistencies in the dbBox code.

odb: minor fix dbBox operators

---

src/gui/src/inspector.cpp
src/gui/src/timingWidget.cpp
src/gui/src/timingWidget.h

gui: Make critical path inspection ergonomic

---

test/flow.tcl

Temporary change until repair_antennas instability is fixed.

test: use multithreading only for drt

---

src/mpl2/src/hier_rtlmp.cpp
src/mpl2/src/hier_rtlmp.h

Use automated memory management.

mpl2: fix sa cores' leaks

---

src/mpl2/src/clusterEngine.cpp

Resolve #5522 
This had already been fixed in #5478. I didn't update #5493 with master, that's why it got in again.

mpl2: fix halo height

---

src/drt/src/TritonRoute.cpp
src/grt/src/GlobalRouter.cpp

For https://github.com/The-OpenROAD-Project/OpenROAD/issues/5486.

Issue an error if design does not have any routable net (with at least 2 terms) for grt and drt

---

src/drt/src/TritonRoute.cpp
src/drt/src/dr/FlexDR.cpp
src/drt/src/dr/FlexDR_conn.cpp
src/drt/src/dr/FlexDR_graphics.cpp
src/drt/src/dr/FlexDR_init.cpp
src/drt/src/dr/FlexDR_maze.cpp
src/drt/src/gc/FlexGC_cut.cpp
src/drt/src/gc/FlexGC_main.cpp
src/drt/src/io/io.cpp
src/drt/src/io/io_guide.cpp
src/drt/src/io/io_parser_helper.cpp
src/drt/src/pa/FlexPA_graphics.cpp
src/drt/src/pa/FlexPA_prep.cpp
src/drt/src/rp/FlexRP_prep.cpp
src/drt/test/gcTest.cpp
src/odb/src/db/dbITerm.cpp

This PR fixes most of the remaining coverity issues. The issues related to FlexGR were left untouched as they are low priority. A couple of false positives regarding serialization were left too.

drt: coverity fixes (2)

---

src/psm/src/ir_network.cpp

Closes: https://github.com/The-OpenROAD-Project/OpenROAD/issues/5605
Issue:
- the new abstract lef handling with vias creates a bunch of additional shapes in the macro lef which appear to be disconnected. this ensures the vias get PSM nodes assigned to them so they appear connected to PSM.

psm: extract nodes from vias in pin shapes

---

etc/DependencyInstaller.sh

etc: add gtest to DependencyInstaller

---

etc/DependencyInstaller.sh
src/CMakeLists.txt
src/cts/test/CMakeLists.txt
src/dft/test/cpp/CMakeLists.txt
src/dpl/test/CMakeLists.txt
src/gpl/test/CMakeLists.txt
src/mpl2/test/cpp/CMakeLists.txt
src/odb/test/cpp/scan/CMakeLists.txt
src/rmp/test/cpp/CMakeLists.txt
src/rsz/test/cpp/CMakeLists.txt
src/utl/test/cpp/CMakeLists.txt
third-party/CMakeLists.txt
third-party/gtest/CMakeLists.txt

For https://github.com/The-OpenROAD-Project/OpenROAD/issues/5530.
Tested with clean build and make test.

Move install of gtest to DependencyInstaller.sh.

---

etc/DependencyInstaller.sh

Every now and then I get issue with certificates so add an option to workaround it.
"eval" is added before wget as alias are expanded when reading the commands and not executed.

etc: Add option to disable certificate checks

---

src/rsz/README.md

Added a new functionality to the _estimate_parastics_ command with my last PR, but forgot to edit the description with how to use the new functionality.

rsz: update README with new estimated parasitics description

---

src/dbSta/src/dbNetwork.cc

dbNetwork.cc coverity fix (nullptr check)

dbNetwork.cc:getOwningInstanceParent fix for nullptr test

---

src/grt/src/GlobalRouter.cpp

Related to issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/5769

grt: clear dirty net previous routing and guides

---

src/tap/include/tap/tapcell.h
src/tap/src/tapcell.cpp

No functional changes.
Changes:
- over iterate over fixed instances once in when placing tapcells
On a 16mm^2 floorplan this takes the tapcell insertion from 158s to 1.9s, most of that extra time was repeatedly iterating over the number of instances.

tap: avoid iterating over insts multiple times when placing tapcells

---

src/grt/src/GlobalRouter.cpp
src/grt/src/Net.cpp
src/grt/src/Net.h

This reverts commit 69bd23c3778e5b7a81c414ddabab2ca81f6776d4, reversing changes made to 8aa1cddf798ab0df6d5a12fa87985d09583a643a.
Fixes a bunch of CI failures.

Revert "Merge pull request #5794 from eder-matheus/grt_incr"

---

etc/deltaDebug.py

no change, just fewer red lines in python editors while wandering through the code.

deltaDebug.py: fewer red lines in editor, no change

---

docs/src/test/man_tcl_params.py
src/odb/src/db/odb.tcl

Fix docs tests, add clearer error messages

---

src/ppl/src/IOPlacer.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5853.

ppl: check if mirrored position is available during random pin placement

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/RepairAntennas.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5849

grt: ignore odb APs when incremental changes are made

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i
src/grt/src/GlobalRouter.tcl

Fix necessary for ORFS post-DRT repair_antennas.

grt: return the diodes count on repair_antennas command

---

src/gui/src/chartsWidget.cpp
src/gui/src/staDescriptors.cpp

Just 2 minor coverity items in the report.

gui: coverity fixes 

---

src/dbSta/src/dbNetwork.cc

Has fix for ariane136 regression

Fix for ariane136 regression

---

src/ppl/src/SimulatedAnnealing.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5926

ppl: fix random assignment to respect constraints

---

src/pad/src/RDLRoute.cpp
src/pad/test/rdl_route_failed.ok
src/pad/test/rdl_route_max_iterations.ok

Fixes:
- platform instability cause by sorting changes

pad: ensure sorting order is stable when routing distances are equal

---

src/drt/src/pa/FlexPA.h
src/drt/src/pa/FlexPA_prep.cpp

Secure CI: Running...
ISPD CI: Running...
Creates the functions `isViaViolationFree()` and `isPlanarViolationFree()` to separate Design Rule Checks from the rest of the code.

drt: separation of drc checking in pin access

---

src/grt/src/GlobalRouter.cpp

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/5973

grt: add error message when odb::dbBlock is not initialized

---

src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/mainWindow.cpp

Adds gui descriptor to `dbBPin`

gui: add bpin descriptor

---

src/grt/src/GlobalRouter.cpp

Additional fix for PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/5997.

grt: initialize fastroute in start_incremental

---

src/rsz/src/Resizer.tcl
src/rsz/test/regression_tests.tcl
src/rsz/test/repair_hold15.ok
src/rsz/test/repair_hold15.tcl
src/rsz/test/repair_setup8.ok
src/rsz/test/repair_setup8.tcl

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/6001

rsz: allow negative hold and setup margins

---

src/gui/README.md
src/gui/include/gui/gui.h
src/gui/src/clockWidget.cpp
src/gui/src/clockWidget.h
src/gui/src/gui.cpp
src/gui/src/gui.i

Adds:
- tcl access change the selected clocked in the clocktree viewer

gui: add tcl access to clocktree viewer

---

src/rsz/include/rsz/Resizer.hh
src/rsz/src/PreChecks.cc
src/rsz/src/RecoverPower.cc
src/rsz/src/RecoverPower.hh
src/rsz/src/RepairDesign.cc
src/rsz/src/RepairSetup.cc
src/rsz/src/Resizer.cc
src/rsz/src/Resizer.i
src/rsz/src/Resizer.tcl

Resolve one of the tasks in #5577.
New flags in repair_design and repair_timing needed for @precisionmoon proposal.
We'll have a new ORFS varialbe HONOR_CELL_FOOTPRINT that will turn on these flags.

rsz: add option to honor cell footprint in repair_design and repair_timing

---

src/gui/src/drcWidget.cpp
src/gui/src/drcWidget.h
src/odb/include/odb/db.h
src/odb/src/db/dbMarkerCategory.cpp

gui: select newly loaded markers

---

src/drt/src/dr/FlexDR_maze.cpp
src/drt/src/dr/FlexGridGraph_maze.cpp

Developer can modify/un-const as needed locally.

drt: make global beginDebugIter & debugMazeIter const

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/MakeWireParasitics.cpp

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/6228

grt: MakeWireParasitics consider segments out of range when the design is congested

---

src/dpl/README.md
src/dpl/include/dpl/Opendp.h
src/dpl/src/FillerPlacement.cpp
src/dpl/src/Opendp.i
src/dpl/src/Opendp.tcl
src/dpl/test/CMakeLists.txt
src/dpl/test/dpl_aux.py
src/dpl/test/fillers2_verbose.ok
src/dpl/test/fillers2_verbose.py
src/dpl/test/fillers2_verbose.tcl
src/dpl/test/fillers9_verbose.ok
src/dpl/test/fillers9_verbose.py
src/dpl/test/fillers9_verbose.tcl
src/dpl/test/regression_tests.tcl

Adds:
- -verbose to filler_placement to print a report of which cells were inserted.

dpl: add verbose flag to filler_placement to print filler cell usage

---

src/psm/README.md
src/psm/include/psm/pdnsim.h
src/psm/src/ir_solver.cpp
src/psm/src/ir_solver.h
src/psm/src/pdnsim.cpp
src/psm/src/pdnsim.i
src/psm/src/pdnsim.tcl
src/psm/test/CMakeLists.txt
src/psm/test/corners_assign_power.ok
src/psm/test/corners_assign_power.tcl
src/psm/test/gcd_test_assign_power.ok
src/psm/test/gcd_test_assign_power.tcl
src/psm/test/regression_tests.tcl

Adds:
- capability to assign power to specific instances for analysis
Notes:
- this is currently not a user facing function, I think we can debate if we want it to be one, but it's mainly there for debugging.

psm: add ability to assign power to instances

---

src/gpl/src/nesterovBase.cpp

This PR should resolve issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/6324

gpl: remove unecessary log messages

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/6316

grt: check if design is placed for grt::have_routes

---

src/grt/src/GlobalRouter.tcl

Fix https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/2608.

grt: check if -net key exists before fetching the net

---

src/drt/src/pa/FlexPA.h
src/drt/src/pa/FlexPA_prep.cpp

This PR applies the node structure change to the row patterns definition.
Something got lost during all the PR branching, rebasing on #5903, I just noticed that and reapplied what was missing. This just applies the changes of the referenced PR to the Row Patterns part of the code.

drt: nodes structure change for rows

---

src/grt/test/est_rc4_corner0.spefok
src/grt/test/est_rc4_corner1.spefok
src/rsz/src/SpefWriter.cc
src/rsz/test/make_parasitics6_ff.spefok
src/rsz/test/make_parasitics6_ss.spefok

Quick fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/6225

rsz: fix pin delimiters for estimate_parasitics -spef

---

src/gpl/src/routeBase.cpp
src/grt/README.md
src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i
src/grt/src/GlobalRouter.tcl

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/6353

grt: remove outdated argument and rename internal vars

---

src/tap/include/tap/tapcell.h
src/tap/src/tapcell.cpp

Fixed 20 misc-include-cleaner issues. Only 12199 to go :)

Fix missing includes in tapcell.{h,cpp}

---

src/grt/src/GlobalRouter.cpp
src/grt/src/Pin.cpp
src/grt/src/Pin.h

Fix https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/2656
Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/6152

grt: ensure on grid position near instance edge for macro and pad pins

---

src/gui/src/displayControls.cpp
src/gui/src/displayControls.h

Adds remaining signal types to GUI controls.

gui: fill out net signal types for gui selection

---

src/odb/test/helper.tcl
src/odb/test/test_block.tcl
src/odb/test/test_bterm.tcl
src/odb/test/test_destroy.tcl
src/odb/test/test_group.tcl
src/odb/test/test_inst.tcl
src/odb/test/test_iterm.tcl
src/odb/test/test_module.tcl
src/odb/test/test_net.tcl
src/odb/test/test_wire_codec.tcl

Found some issues with the current asserts, so creating a set of situation-specific asserts to resolve any ambiguity.

added new assert helper functions to avoid ambiguity/bad behavior

---

src/pdn/test/CMakeLists.txt

Looks like I missed this one when converting.

pdn: enable ctest

---

src/pdn/src/connect.cpp
src/pdn/test/CMakeLists.txt
src/pdn/test/core_grid_check_connect_layers.ok
src/pdn/test/core_grid_check_connect_layers.tcl

Adds:
- additional error checking to connect rules in PDN

pdn: add error checking for layers in connect rules

---

src/rmp/src/CMakeLists.txt
src/rmp/src/abc_library_factory.cpp
src/rmp/src/abc_library_factory.h
src/rmp/src/delay_optimization_strategy.cpp
src/rmp/src/logic_cut.cpp
src/rmp/src/logic_cut.h
src/rmp/src/logic_extractor.cpp
src/rmp/src/logic_extractor.h
src/rmp/src/resynthesis_strategy.h
src/rmp/src/zero_slack_strategy.cpp
src/rmp/src/zero_slack_strategy.h
src/rmp/test/cpp/TestAbc.cc

This is the first working resynthesis strategy. I haven't added it to the restructure command yet, but would like to do that in a follow up PR. Right now the resynth leans a bit area heavy.
see TestAbc.cc changes for example usage.

rmp: First resynthesis strategy ZeroSlackStrategy

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/6656.

ppl: add location information when there are not enought slots

---

etc/DependencyInstaller.sh

Reverts The-OpenROAD-Project/OpenROAD#6657

Revert "etc: only download or-tools if needed"

---

.readthedocs.yaml

Fixes https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/2818

docs: clone submodules to generate sta docs

---

src/mpl/src/SACoreHardMacro.cpp
src/mpl/src/SACoreSoftMacro.cpp
src/mpl/src/SACoreSoftMacro.h
src/mpl/src/SimulatedAnnealingCore.cpp
src/mpl/src/SimulatedAnnealingCore.h
src/mpl/src/hier_rtlmp.cpp
src/mpl/src/hier_rtlmp.h
src/mpl/src/util.h

Resolve #6669 
Small steps into making MPL more readable and organized.

mpl: use core weights struct when creating cores

---

src/odb/src/zutil/util.cpp

odb: check for master type and site type before confirming one site master

---

src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp

Code refactoring for clarity. No functional changes.

ppl: small code refactoring

---

src/psm/src/ir_network.cpp
src/psm/src/ir_network.h
src/psm/src/ir_solver.cpp
src/psm/src/ir_solver.h
src/psm/test/CMakeLists.txt
src/psm/test/missing_resistance.ok
src/psm/test/missing_resistance.tcl

Adds:
- check for layer resistances before attempting to solve the network

psm: check for resistances before attempting to solve network

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/src/FastRoute.cpp

Adds:
- wirelength and via to metrics collected for global router

grt: add global route wirelength and number of vias to metrics

---

src/rmp/src/delay_optimization_strategy.cpp
src/rmp/src/delay_optimization_strategy.h
src/rmp/src/logic_cut.cpp
src/rmp/src/logic_optimization_strategy.h
src/rmp/src/zero_slack_strategy.cpp
src/rmp/test/cpp/TestAbc.cc
src/rmp/test/sky130_const_cell.v

Also includes bug fix for unconnected pins on standard cells.

rmp: General optimization of remapper

---

src/pdn/src/rings.cpp
src/pdn/test/core_grid_with_rings_outside_die.ok

pdn: add error about ring area

---

src/odb/src/db/odb.tcl
src/ppl/README.md
src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.tcl
src/ppl/test/CMakeLists.txt
src/ppl/test/exclude4.defok
src/ppl/test/exclude4.ok
src/ppl/test/exclude4.tcl

Necessary to remove random pin placement from ORFS.

ppl/odb: add function to define excluded regions for pin placement

---

src/odb/src/db/odb.tcl
src/ppl/README.md

Follow up on https://github.com/The-OpenROAD-Project/OpenROAD/pull/6870#discussion_r2001907073

odb: make -region mandatory for exclude_io_pin_region command

---

.bazelrc
README.md
docs/user/Bazel.md
etc/cred_helper.py
etc/cred_helper_test.py

megaboom that started first will copy-cat the setup and the canonical home for the documentation will
be in OpenROAD.

bazel: OpenROAD has the canonical Bazel setup

---

src/mpl/src/hier_rtlmp.cpp

mpl: remove unused terminal output

---

.bazelrc
.gitignore
docs/user/Bazel.md
etc/cred_helper.py
etc/cred_helper_test.py

bazel: user-bazelrc name per Bazel best practice

---

src/rsz/src/Resizer.cc

Support for hierarchy in resizer routines:
canRemoveBuffer
removeBuffer

Can remove buffer rsz hier

---

src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/search.cpp
src/gui/src/search.h
src/odb/include/odb/db.h
src/odb/include/odb/dbBlockCallBackObj.h
src/odb/src/db/dbBlockage.cpp
src/odb/test/cpp/CallBack.h
src/odb/test/cpp/TestCallBacks.cpp

No functional changes, just allow users to destroy blockages.
FYI @QuantamHD

add blockage destroy for symmetry with obstruction

---

src/odb/src/db/dbName.h
src/odb/src/lefin/CellEdgeSpacingTableParser.cpp
src/odb/src/lefin/KeepOutZoneParser.cpp
src/odb/src/lefin/MetalWidthViaMapParser.cpp
src/odb/src/lefin/MinCutParser.cpp
src/odb/src/lefin/lefMacroEdgeTypeParser.cpp
src/odb/src/lefin/lefTechLayerAreaRuleParser.cpp
src/odb/src/lefin/lefTechLayerCutEnclosureParser.cpp
src/odb/src/lefin/lefTechLayerEolExtensionParser.cpp
src/odb/src/lefin/lefTechLayerEolKeepOutRuleParser.cpp
src/odb/src/lefin/lefTechLayerForbiddenSpacingRuleParser.cpp
src/odb/src/lefin/lefTechLayerPitchRuleParser.cpp
src/odb/src/lefin/lefTechLayerSpacingEolParser.cpp
src/odb/src/lefin/lefTechLayerTwoWiresForbiddenSpcRuleParser.cpp
src/odb/src/lefin/lefTechLayerWrongDirSpacingParser.cpp

Fixed propery -> property in ODB LEF messages

property message typo fix

---

src/drt/test/aes_nangate45.tcl
src/drt/test/aes_nangate45_distributed.tcl
src/drt/test/gcd_nangate45.tcl
src/drt/test/gcd_nangate45_distributed.tcl
src/drt/test/gcd_nangate45_dump_worker.tcl
src/drt/test/server1.tcl
src/drt/test/server2.tcl
test/flow.tcl

Replace calls to `getconf` with cpu_count

---

src/ppl/src/IOPlacer.cpp
src/ppl/src/Slots.cpp
src/ppl/src/Slots.h

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/7028.

ppl: clear constraints container before initialization

---

src/odb/include/odb/db.h
src/odb/src/db/dbBlock.cpp
src/odb/src/db/odb.tcl
src/ppl/include/ppl/IOPlacer.h
src/ppl/src/IOPlacer.cpp
src/ppl/src/IOPlacer.i
src/ppl/src/IOPlacer.tcl
src/ppl/test/CMakeLists.txt
src/ppl/test/add_constraint17.ok
src/ppl/test/add_constraint17.tcl
src/ppl/test/add_constraint17_1.defok
src/ppl/test/add_constraint17_2.defok
src/ppl/test/add_constraint18.ok
src/ppl/test/add_constraint18.tcl
src/ppl/test/add_constraint18_1.defok
src/ppl/test/add_constraint18_2.defok
src/ppl/test/ppl_aux.py
src/ppl/test/random5.ok
src/ppl/test/random6.ok
src/ppl/test/top_layer1.ok
src/ppl/test/top_layer2.ok
src/ppl/test/top_layer3.ok
src/ppl/test/top_layer4.ok
src/ppl/test/top_layer5.ok
src/ppl/test/top_layer6.ok
src/ppl/test/top_layer7.ok
src/ppl/test/top_layer_error2.ok

Follow up on https://github.com/The-OpenROAD-Project/OpenROAD/pull/7044.

ppl: move top layer pins to odb + unit tests

---

src/ppl/src/IOPlacer.cpp

ppl: remove stray comma in message

---

src/dpl/src/CheckPlacement.cpp
src/dpl/test/check2.ok
src/dpl/test/check3.ok
src/dpl/test/check7.ok
src/drt/src/pa/FlexPA_acc_point.cpp

Added the master name to a couple of messages to improve debugging of design/platform configuration issues.

Added the master name to a couple of messages

---

src/gpl/test/large01.ok
src/gpl/test/large02.ok
src/gpl/test/macro01.ok
src/gpl/test/macro02.ok
src/gpl/test/macro03.ok
src/gpl/test/medium01.ok
src/gpl/test/medium02.ok
src/gpl/test/medium03.ok
src/gpl/test/medium04.ok
src/gpl/test/medium05.ok
src/gpl/test/medium06.ok

This change is required due to changes in PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/6922

gpl: update large tests after log change

---

src/Main.cc

Without adding any dependencies

bazel: make OpenROAD in path work

---

src/gpl/README.md

include the addition of -gui flag to run-me file

gpl: update readme for debug mode

---

src/rsz/src/Rebuffer.cc
src/rsz/src/RepairSetup.cc

Fixes: disconnects on load pins which are marked dont touch

rsz: honor dont touch in rebuffer for :load

---

BUILD

bazel: use BUILD consistently and run buildifier

---

src/gui/src/heatMap.cpp

@gudeh this resolves the looping behavior you were seeing.

gui: avoid inf loop in heatmap due to repeated calls to redraw

---

src/odb/src/db/dbModInst.cpp
src/odb/src/db/dbModule.cpp

repair the dbModInst destroy in odb so dbModInst destroyed after the dbModITerms so restore with journalling order ok.

Delete module inst after moditerms

---

src/mpl/src/hier_rtlmp.cpp

mpl: fix coverity issue

---

src/rcx/include/rcx/ext.h
src/rcx/src/ext.cpp

Update Ext destructor to fix a memory leak

Fix a memory leak

---

src/rcx/include/rcx/extRCap.h
src/rcx/src/extmain.cpp

Clean up the context and avoid leaks

Remove a leak of context in extmain

---

BUILD.bazel
bazel/BUILD
bazel/InitRunFiles.cpp
src/Main.cc

No need to modify OpenROAD or OpenSTA source code
@hzeller @QuantamHD Thoughts?

bazel: handle runfiles init with global constructor

---

MODULE.bazel
MODULE.bazel.lock

https://github.com/bazelbuild/bazel-central-registry/commit/2c02baa4dfaec3a202ffa55608a1c08d22ddaa28
Fixes trouble downloading 3.4.0.bcr.2:
```
Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip] to
eigen-3.4.0.zip: Checksum was sha256-66Pz1BTS+MuikZx47G2qsI/HG6K6SuUCt+XU2Z/ALNo=
but wanted sha256-HMqrv+hw9grz1qUZxT4J89z2MCBzId/6VTVkqOdcT8g=
```

Bazel eigen trouble

---

etc/DependencyInstaller.sh

Setup fixes

---

src/odb/src/db/dbTechLayerAntennaRule.cpp
src/odb/src/db/dbTechLayerAntennaRule.h

Add a destructor to _dbTechAntennaPinModel

---

src/rcx/src/extmain.cpp

Delete members created in the .h file

Remove leak in extMain

---

src/rcx/include/rcx/extRCap.h
src/rcx/src/extRCmodel.cpp

Cache the size of the arrays to ensure that every allocated element is deleted

Fix leak of rcDistTable

---

src/odb/include/odb/array1.h
src/rcx/src/extmain_v2.cpp
src/rcx/src/netRC.cpp

I mistakenly deleted the branch and closed #7312

Fix leak in model table

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/RepairAntennas.cpp
src/grt/src/RepairAntennas.h

Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/7408

grt: do not overwrite guides for nets that weren't modified

---

MODULE.bazel
MODULE.bazel.lock

Bazel llvm 20 1 0

---

MODULE.bazel
MODULE.bazel.lock
test/orfs/mock-array/BUILD
test/orfs/mock-array/chisel.bzl
test/orfs/mock-array/src/main/scala/MockArray.scala

@oharboe This replaces the bootleg `chisel` build by an upstream build.

test/orfs/mock-array: Build using upstream chisel

---

src/mpl/src/hier_rtlmp.cpp
src/mpl/src/hier_rtlmp.h
src/mpl/src/object.cpp
src/mpl/src/object.h

1. Add some missing const;
2. Improve comments;
3. Renaming.
Also some minor clean up.

mpl: refactor and preps for new blockages work

---

src/rsz/src/BufferMove.cc
src/rsz/src/BufferMove.hh

Fix non-static class member arrival_paths_ is not initialized in constructor warning.

Fix non-static class member arrival_paths_ is not initialized in constructor warning.

---

MODULE.bazel

No change, just less PR noise for later PRs.

bazel: MODULE.bazel buildifier

---

src/grt/src/GlobalRouter.cpp
src/grt/src/fastroute/include/FastRoute.h
src/grt/src/fastroute/src/FastRoute.cpp
src/grt/test/single_row.ok
src/grt/test/top_level_term2.ok

grt: allow merge nets with local nets

---

src/gpl/src/nesterovBase.cpp
src/gpl/test/error01.ok

Related to PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/7692

gpl: fix message typo

---

etc/DependencyInstaller.sh

Useful for systems with not enough resources.

etc: allow fewer threads

---

src/gpl/src/nesterovBase.cpp
src/gpl/src/nesterovBase.h

This PR addresses issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/7802

gpl: move header declaration

---

MODULE.bazel
MODULE.bazel.lock

Ran:
bazelisk run @bazel-orfs//:bump

bazel-orfs: bump

---

test/orfs/README.md

For convenience, excerpt from bazel-orfs documentation

bazel: document debugging use-case

---

src/grt/include/grt/GlobalRouter.h
src/grt/src/GlobalRouter.cpp
src/grt/src/GlobalRouter.i

Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/7555.

grt: add function to write pin locations on the groute grid

---

src/odb/include/odb/db.h
src/odb/src/db/dbGuide.cpp

Noticed this while working on the gui guide drawing.

odb: make guide access const

---

src/gui/src/dbDescriptors.cpp
src/gui/src/inspector.cpp
src/gui/src/inspector.h
src/gui/src/layoutTabs.cpp
src/gui/src/layoutTabs.h
src/gui/src/mainWindow.cpp

Part 1 of #7833
Before turning on: 
After turning on:

gui: update actions in inspector and change button for route guides based on visibility

---

src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/mainWindow.cpp

Adds:
- list of masters to site properties
- dbBox descriptor and add obstructions to instance descriptor properties

gui: dbBox descriptor

---

src/gui/src/dbDescriptors.cpp
src/gui/src/dbDescriptors.h
src/gui/src/mainWindow.cpp

gui: add descriptor for dbScanPartition

---

src/odb/include/odb/dbTypes.h
src/odb/src/db/dbTypes.cpp
src/odb/src/swig/tcl/dbenums.i

So that we can merge #7986 in order to allow the changes in #7968.

odb: add dbGroupType for visual debug

---

src/odb/src/codeGenerator/schema/chip/dbChip.json
src/odb/src/db/dbChip.h

Addresses https://github.com/The-OpenROAD-Project/OpenROAD/pull/8002#discussion_r2274703214

odb: Use more common interval notation in dbChip.json

---

src/dpl/src/PlacementDRC.cpp

Following the comments from https://github.com/The-OpenROAD-Project/OpenROAD/pull/8053#discussion_r2285384764

dpl: ignore padding with core edge

---

docker/Dockerfile.binary
docs/user/Build.md
etc/DockerHelper.sh
jenkins/Jenkinsfile.nightly
src/CMakeLists.txt
src/rcx/calibration/run.sh
test/regression_vars.tcl

Refactor(Binary): Specify binary path

---

src/cts/src/TritonCTS.cpp
src/cut/src/blif.cpp
src/grt/src/cugr/src/robin_hood.h
src/mpl/src/hier_rtlmp.cpp
src/odb/include/odb/dbMatrix.h
src/par/include/par/PartitionMgr.h
src/par/src/ArtNetSpec.cpp
src/par/src/PartitionMgr.cpp
src/par/src/TritonPart.cpp
src/ppl/src/Core.cpp
src/ppl/src/IOPlacer.cpp
src/rmp/src/Restructure.cpp

Fix some missing includes.

---

test/orfs/mock-array/BUILD
test/orfs/mock-array/power_instances.tcl

Test orfs mock array power per module reporting

---

docs/user/Bazel.md

bazel: add ORFS hacking use-case
